### ISSUE TITLE
Stabilize command and package API

### ISSUE THREAD

**Issue by gaillard** [kardianos/govendor#10]
I was wondering if you intend to keep the package, not the command stable so those that want to programatically call into the code can rely on it? I notice there is missing documentation on key functions which is why I am asking. Thanks !

**Comment by kardianos** [comment]
@gaillard The command API will probably stay the same for awhile, however there is a planned rewrite of the Go API.

**Comment by anonx** [comment]
@kardianos Haven't you thought about simplification of command API? Probably by creating aliases for the most common use-cases. Just as an example:

1. Create `internal/` and `internal/vendor.json`, if they don't exist **+** replace all external paths by their internal versions: `vendor save`.
2. Replace all external paths by their internal versions **+** delete unused internal paths: `vendor save` again.
3. Update all internal packages: `vendor update`.
4. Remove all internal packages, use external ones instead: `vendor remove`.

So, everything usual user will have to know is `vendor save`, `vendor update`, and `vendor remove`.
What do you think?

**Comment by kardianos** [comment]
I've updated the API considerably. checkout "github.com/kardianos/govendor/context" on the "importmap" branch. I'd be interested in your feedback. I would be willing to commit to that API as being mostly stable. I say mostly because of the unknown of the 1.5 vendor experiment.

**Comment by kardianos** [comment]
@gaillard I can't yet commit to the API being 100% stable, but the package is now structured how I want it to be, so it should be relatively stable. Look in the "context" package and how it is used in tests and the migrate and main packages.

**Comment by anonx** [comment]
@kardianos Sorry for too late reply. I think the new API is waaay better than the old one. Well done. :+1:
