### ISSUE TITLE
Updating with /... and /^ seems broken

### ISSUE THREAD

**Issue by iancoffey** [kardianos/govendor#104]
The update command documentation references the /... and /^ command for specifying packages under the location specified.

When using this today however, both commands result in an error like so:

Error: Package "Import: \"github.com/somerepo/someproject\" relative: \"\"" not a go package or not in GOPATH.

The GOPATH is correct, the command is being run from a proper location inside the GOPATH, and the referenced project seems to exist where it should as well. 

If the packages are updated individually, it works as normal.

**Comment by kardianos** [comment]
I'm wondering if this has to do with import path handling. If this didn't fix it, is there a test case I could run to encounter it?

**Comment by lstoll** [comment]
So I think the issue here is when the specified path has nothing buildable in it.

i.e
```
project/
project/pkga/pkga.go
project/pkgb/pkgb.go
```

running `govendor update project/...` will return `Error: Package "Import: \"project\" relative: \"\"" not a go package or not in GOPATH.` Which is true, but not the intent of the command

**Comment by kardianos** [comment]
I think you're correct. This shouldn't be too hard to fix.
