### ISSUE TITLE
Skip files with "package documentation"

### ISSUE THREAD

**Issue by neelance** [kardianos/govendor#106]
I want to vendor some program packages that are used by `go generate`. Those currently show up as `unused`. Could that be avoided by having a list in `vendor.json` that manually marks some packages as used?

**Comment by kardianos** [comment]
Hmmm, That's actually a bug in the status marking (heads off to add/update test). `main` packages should never be marked as unused.

**Comment by kardianos** [comment]
Do you have the latest version on the master branch? I just updated a test but it was already passing.

**Comment by neelance** [comment]
I just realized that the package `github.com/gogo/protobuf/protoc-gen-gogo` is not recognized as a `main` package. It has a file that uses `package documentation`, which is skipped by the Go compiler. The other file has `package main`.

This special case is described in `go help packages`:
```
The name documentation indicates documentation for
a non-Go program in the directory. Files in package documentation
are ignored by the go command.
```
Another mention is here: https://golang.org/pkg/go/build/#Context.Import

Seems like the `protoc-gen-gogo` package is using this not in the intended way. Nevertheless, govendor should behave the same as the Go compiler.

**Comment by kardianos** [comment]
Agreed. Will fix. Thanks for tracking it down.
