### ISSUE TITLE
`govendor update` missing and external conflicts...

### ISSUE THREAD

**Issue by sean-** [kardianos/govendor#111]
When attempting to `govendor update` external packages, if the package is missing in `GOPATH` but exists in `vendor/` then the `update` fails:

```
% govendor update +external
Error: Package "github.com/go-ini/ini" not a go package or not in GOPATH.
[1]    66635 exit 2     govendor update +external
% govendor list -v
 v  github.com/go-ini/ini ::/vendor/github.com/go-ini/ini
    └── github.com/hashicorp/vault/vendor/github.com/aws/aws-sdk-go/aws/credentials
[snip]
 e  github.com/go-ini/ini ::github.com/aws/aws-sdk-go/vendor/github.com/go-ini/ini
    └── github.com/aws/aws-sdk-go/aws/credentials
```

The workaround is to copy `vendor/` to `$GOPATH` and try again: `cp -pr vendor/* $GOPATH/src/ && govendor update +external` (wtb `govendor export` ?)

**Comment by kardianos** [comment]
`govendor {add,update}` pull from $GOPATH.

`govendor fetch` adds and updates from remotes. :/ I know that seems counter intuitive, but ... backwards compatibility for now.

**Comment by kardianos** [comment]
If you haven't seen it already, you may find the [FAQ](https://github.com/kardianos/govendor/blob/master/doc/faq.md) useful. I will close for now, but feel free to open again.

**Comment by sean-** [comment]
The FAQ is fantastic, thank you, and yes, I know `{add,update}` move data from `GOPATH`.  The issue I was having above was `go-ini` already existed in `vendor/` but didn't exist in `GOPATH`.  When doing a `govendor update +missing`, I would expect `govendor` to add the packages in `vendor/` to the solution set if the package exists in `vendor/` but not in `GOPATH`.  Does that make sense?
