### ISSUE TITLE
"govendor add +e" not equivalent to specifying packages manually

### ISSUE THREAD

**Issue by neelance** [kardianos/govendor#116]
I have several packages listed via `govendor list +e`, but if I do `govendor add +e` nothing gets changed. If I do an explicit `govendor add [package]` with one of the packages of the list, then it gets added properly. Why?

**Comment by kardianos** [comment]
Probably a bug. I've modified the status matching logic recently and while it still passes my test cases, I probably don't test every permutation possible. Is it possible for you to add a little more detail, or add reproducible steps?

Some key information? Can you confirm if files exist in that location in the vendor directory? Can you confirm if there is or is not an existing entry in the vendor file?

Thanks.

**Comment by neelance** [comment]
```
> govendor add +e
Error: Package "sourcegraph.com/sourcegraph/sourcegraph/vendor/github.com/gengo/grpc-gateway/utilities" already in vendor.
```
Should this ever happen?

**Comment by kardianos** [comment]
No. I think it was related to the recent change in make "/..." and "/^" function correctly, even on empty folder roots. I've got a guess as to the situation, but I'll need to confirm. As always, I'll add a testcase for this once found.

Thanks.
