### ISSUE TITLE
Add Status (p) Program for vendored main packages.

### ISSUE THREAD

**Issue by noonien** [kardianos/govendor#12]
I use go.rice to embed static files into my binaries and would like to vendor the rice main package.

I already did this using vendor add github.com/GeertJohan/go.rice/rice and the package was successfully vendored, however, the package status is listed as "unused".

I figure this is because the package is not imported anywhere, nor could it be.

Would it perhaps be a good idea to consider packages that are named "main" as internal and pull their dependencies as well when vendoring them?

**Comment by kardianos** [comment]
That's an excellent point. I would consider adding a new status called
"main" (m) just for this situation. Considering it an internal status would
also be acceptable.

**Comment by noonien** [comment]
Having a special status for this would be great, however, (m) already means missing, does it not?

**Comment by kardianos** [comment]
True. I'be been trying to pick statuses with unique initial letters. I've got some work to do before I can get to this. Thinking for now on how to best handle it.

**Comment by kardianos** [comment]
Thinking:
Program (p) - status for copied main package and it's dependencies that otherwise the project wouldn't have.

**Comment by noonien** [comment]
Yes, that looks fine. I believe 'program' is what the Go language specification declares as the result of compiling the main package.

**Comment by noonien** [comment]
Any updates on this? Should I fork and submit a pull requests?

**Comment by kardianos** [comment]
In the works. Look at the importmap branch. It will co-release with vendor
exp change.

**Comment by kardianos** [comment]
@noonien This is now completed.
