### ISSUE TITLE
Migrate from vendor-directory Godep?

### ISSUE THREAD

**Issue by glasser** [kardianos/govendor#125]
I've been using Godep on a project. We used to use rewritten dependencies but now that Godep supports it we just use the `vendor` directory.  So there's a Godeps.json file but the vendored code is under `vendor`.

I'm considering switching to govendor.  It looks like `govendor migrate godep` does not detect this setup: it deletes my Godeps.json but the vendor.json that it creates has empty `package`.  How can I import this setup?

**Comment by glasser** [comment]
Oh, hmm, I guess I can first `godep restore ./...`, delete my vendor directory (and Godeps.json), and `govendor add +external` a few times...

**Comment by kardianos** [comment]
I bet migrate is broken. I need to update, it is on my list to-do.

**Comment by freeformz** [comment]
These steps should do it if you are using godep with the vendor experiment.

```console
$ godep restore
$ rm -rf Godep vendor
$ govendor init
$ govendor add +ex
```
