### ISSUE TITLE
WTB: `govendor licensees -print +vendor`

### ISSUE THREAD

**Issue by sean-** [kardianos/govendor#126]
It would be *REALLY* nice if `govendor` grew the ability to aggregate all of the licenses either `LICENSE` or `COPYING` and print them to standard out so ppl could do something like:

```
% govendor licenses +vendor > LICENSES
```

Or a flag that would automatically do that on `govendor sync`.  Where each license is separated by 80 characters of `=` and a newline.

**Comment by kardianos** [comment]
Actually I was thinking the same thing, even for just usage within govendor. I like your command syntax.

I was thinking it should also include the go BSD license as well, as it requires reproduction within binary distributions too.
