### ISSUE TITLE
Dupes in govendor list

### ISSUE THREAD

**Issue by lcaballero** [kardianos/govendor#127]
I see duplicates when running `$> govendor list`, I don't expect there to be dupes, but maybe I'm wrong.  What is the __true__ expected behavior?  See the image below where pborman/uuid is listed twice.  There could be two version, and if that's what this indicates it might be good to somehow indicate that, but I'm not sure what is **correct**.

![screen shot 2016-04-01 at 2 42 35 pm](https://cloud.githubusercontent.com/assets/251297/14219540/16250b8a-f818-11e5-8efe-c7941e613b51.png)

**Comment by kardianos** [comment]
What does `govendor list -v` say?

**Comment by lcaballero** [comment]
Ok, well `govendor list -v` does show the library is a dependency of two separate packages.  The one that's part of hitman/vendor appears suffixed as `::github.com/lcaballero/hitman/vendor/github.com/pborman/uuid`.  Is this the indication of two different version like I was looking for, and so listed twice in the `govendor list` without -v?

<img width="640" alt="screen shot 2016-04-01 at 9 20 21 pm" src="https://cloud.githubusercontent.com/assets/251297/14224161/c8b3f00e-f84f-11e5-8c63-e57597b16134.png">

**Comment by kardianos** [comment]
Yes.
