### ISSUE TITLE
'govendor add some/pkg' sometimes doesn't do anything if some/pkg is not a dep of anything

### ISSUE THREAD

**Issue by cespare** [kardianos/govendor#130]
I'm using govendor to vendor some programs (package main) that we need which aren't otherwise dependencies of any other packages. This sometimes works, but sometimes govendor exits without any errors and without making any changes.

The problem isn't specific to package main; I can also see the issue if I try to `govendor add` a library package that isn't a dependency of anything else.

I traced through the code and the problem seems to be that `Context.addSingleImport` returns `nil, nil` if the last file in the package directory through which it iterates happens to not be a `.go` file (for example, README.md).

https://github.com/kardianos/govendor/blob/47229b693f03e029f04badcc81a9babd30d716a3/context/resolve.go#L366-L384

Thus the problem manifests on some packages but not others (and varies from computer to computer); it's sensitive to the order of readdir output.

The following patch seems to fix the issue, but it's probably not the correct way to solve the problem.

``` diff
--- a/context/resolve.go
+++ b/context/resolve.go
@@ -376,9 +376,12 @@ func (ctx *Context) addSingleImport(pkgInDir, imp string, tree bool) (*Package,
                        continue
                }
                path := filepath.Join(dir, fi.Name())
-               pkg, err = ctx.addFileImports(path, gopath)
+               p, err := ctx.addFileImports(path, gopath)
                if err != nil {
-                       return pkg, err
+                       return nil, err
+               }
+               if pkg == nil {
+                       pkg = p
                }
        }
        return pkg, nil
```

Sorry for the not-particularly-great bug report; please let me know if you don't see the issue and I can give more detailed repro steps.

**Comment by gaillard** [comment]
I would like to see this fixed too

**Comment by kardianos** [comment]
Acknoledged. I'll look into it.

**Comment by kardianos** [comment]
@cespare I appreciate you looking into this in depth. Due intermittent nature of the bug, I'm working to get a repeatable failure, add a test, and then fix the code.

Is there any public repo that I could use as an example where it sometimes fails to add?

**Comment by cespare** [comment]
@kardianos I'll make a repro case for you.

In my tests, filesystems return listings in a consistent order, so I doubt it's possible to make a test that consistently fails on every machine unless you add a testing hook to override Readdir or something.

**Comment by cespare** [comment]
Here's an example:

```
$ mkdir -p /tmp/gopath/src/repro
$ cd /tmp/gopath/src/repro/
$ GOPATH=/tmp/gopath go get github.com/cespare/misc/govendorrepro
$ mkdir vendor
$ GOPATH=/tmp/gopath govendor add github.com/cespare/misc/govendorrepro 
$ find vendor
vendor
vendor/vendor.json                                                                                                                                  
$ cat vendor/vendor.json 
{
        "comment": "",
        "ignore": "",
        "package": [],
        "rootPath": "repro"
}
```

**Comment by kardianos** [comment]
@cespare Your test case was awesome in understanding the root cause and instrumental for creating a test case. Thanks! You rock :).
