### ISSUE TITLE
feature: Diff between vendored deps and Gopath

### ISSUE THREAD

**Issue by boyand** [kardianos/govendor#131]
It would be great to be able to see the difference between vendored dependency versions/commit hashes and what is in the Gopath.

**Comment by kardianos** [comment]
I'm not entirely sure I want to add this, but...

What precisely would you like to see in the diff? Should test files and other tags that have been ignored show up in the diff?

**Comment by boyand** [comment]
I was thinking more in the lines of comparing revisions i.e. what is available in your Gopath vs which version has been vendored. It is quite helpful when you manage a lot of different projects and you want to be able to bump dependencies.

**Comment by kardianos** [comment]
I have an open "thinking" issue for something like that https://github.com/kardianos/govendor/issues/122 . Should I merge this into that?

Case being, I might report on both the remote and GOPATH, rather than just the remote.
Yes?

**Comment by boyand** [comment]
Makes perfect sense 👍
