### ISSUE TITLE
Overridden github URL not honored for subpackages

### ISSUE THREAD

**Issue by charles-dyfis-net** [kardianos/govendor#133]
> $ govendor fetch golang.org/x/crypto/...::github.com/charles-dyfis-net/crypto@external-signing
> goError: Failed to fetch package "golang.org/x/crypto/openpgp": No label found for specified version "external-signing" from golang.org/x/crypto/openpgp::golang.org/x/crypto/openpgp@external-signing

Note the `::golang.org/x/crypto/openpgp@external-signing`, whereas the user-specified URL was `github.com/charles-dyfis-net/crypto`.

**Comment by kardianos** [comment]
Acknowledged. I'm a little bit busy, but I plan to address this very soon.

**Comment by charles-dyfis-net** [comment]
Thank you. In the interim, I've worked around this by fixing up my `vendor.json` by hand.
