### ISSUE TITLE
Error adding package

### ISSUE THREAD

**Issue by sjezewski** [kardianos/govendor#135]
I'm getting a funny parse error when trying to add a specific package.

```shell
$ govendor add google.golang.org/cloud/internal/transport
Error: Package "google.golang.org/cloud/internal/transpor" not a go package or not in GOPATH.
$ ls $GOPATH/src/google.golang.org/cloud/internal/transport/
cancelreq.go  cancelreq_legacy.go  dial.go  proto.go
```

Has the 'feel' of a funny bash input buffer error (bash input just messed up when i entered the command), but I've run it in separate bash shells and I get the same result.

**Comment by kardianos** [comment]
I suspect you are running an old version; that looks like a known (fixed) bug. Could you update to latest and try again?

**Comment by sjezewski** [comment]
Yup, that was it. Thanks!

I looked for something like a `govendor --version` command, but couldn't find one. Might be helpful in the future for checking what version a user / bug is on.

**Comment by kardianos** [comment]
The default help message now includes a version number.

**Comment by sjezewski** [comment]
Aha! Missed that too! Thanks for the help.
