### ISSUE TITLE
Respect build tags

### ISSUE THREAD

**Issue by kaedys** [kardianos/govendor#142]
Not _sure_ if this qualifies as an issue, but here goes.  Most of our projects vendor `golang.org/x/net/context`.  However, for a recent project, we did a fresh `go get` before vendoring, just to make sure we were up to date.  The current version of that context package now includes this commit:

https://github.com/golang/net/commit/afc22ee9133171570a267463982b542fb3edff5a#diff-22b1e0bcbf56beea47fa8ad88e890286R5

Now, the biggest piece of that commit was that it split the context package, with different implementations being included in a build based on the version of Go being used.  Go 1.7 is apparently making the context package standard library, so as of that commit, if one is using Go 1.7, it builds using the `go17.go` file instead of the `pre_go17.go` file (which contains the prior implementation of the package).

The problem comes in that `go17.go` references the import `context`, which will be standard library in Go 1.7, but is obviously missing from older version of the runtime.  However, govendor sees this package and flags it as missing.

Would it be possible for govendor to read the build tags and adjust its "missing" list based on them?  Frankly, I don't know if this will be possible, or practical, but it would be nice to not have that package flagged as "missing" every time we run `govendor list`, since we're still using Go 1.6 (and 1.7 hasn't been released yet), and thus not even using that file in our builds.

**Comment by kardianos** [comment]
You could edit the "govendor.json" file and include go1.7 to the ignore tag list.

There may be some general improvement of how we handle go specific build tags in particular.

**Comment by kaedys** [comment]
Roger, I'll add that in there for now.

**Comment by kaedys** [comment]
Hrm...it appears that adding that to the ignore field didn't alter behavior.  Here's our vendor.json:

https://gist.github.com/kaedys/53740134020a3dfe118203beece0baa6

And we're still getting this:
```
$ govendor list +e +m +u
  m context    
```

**Comment by kardianos** [comment]
You would need to re add the x/net/context package for it to take effect. Can also verify what is using it with `govendor list -v +v`. I can take a look at this soonish.

**Comment by kardianos** [comment]
@kaedys I just tagged a new version (v1.0.2). In my testing, if my vendor file ignored go1.7 it didn't report context as missing, at least in a simple case.

Could you verify on your end?

**Comment by kaedys** [comment]
Not sure what version I'm on (is there a `-version` flag I'm not seeing?), but your previous suggestion of adding `go1.7` to the ignore and readding `/x/net/context` did the trick, it no longer reports `context` as missing.

**Comment by kardianos** [comment]
`govendor -h` reports version in the first line.
