### ISSUE TITLE
Wording clarification for fetch and sync.

### ISSUE THREAD

**Issue by lcaballero** [kardianos/govendor#143]
Not sure if this is clear wording:
```
fetch    (beta) Add new or update existing packages from remote repository.
sync     (beta) Pull in packages from remote respository to match vendor.json file.
```
Does sync only pull the remote into GOPATH based on vendor.json?  While fetch skips GOPATH and adds them directly to the vendor directory?  Basically for fetch what is being added to?  For sync: pulled into what?

I wanted to test this, but the repos I'm currently concerned about live on private repo, which doesn't yet allow go get (lacks meta tag with go-import).

**Comment by kardianos** [comment]
What do you think of this wording:
```
    fetch    Add new or update vendor folder packages from remote repository.
    sync    Pull packages into vendor folder from remote repository to match vendor.json file.
```

**Comment by lcaballero** [comment]
Excellent.   Thanks for the added clarity.

**Comment by kardianos** [comment]
Opening to remind me to apply wording changes.
