### ISSUE TITLE
govendor fetch a fork not working

### ISSUE THREAD

**Issue by mmindenhall** [kardianos/govendor#147]
My project uses [beego](https://github.com/astaxie/beego) for REST APIs and a small web app.  I recently forked the project and submitted a PR on the `develop` branch, which has yet to be accepted.  I tried using govendor to fetch my fork as beego, but nothing has worked.  I've tried many permutations of `/^` vs `/...`, different version specs (`@develop`, `@=develop`, `@commit-hash-of-my-develop`), but nothing seems to work.  Finally, I even tried the exact syntax from README.md, which fetched from beego's master instead of my fork's master.

A few examples of what I've tried:

```sh
# Ran this command before each of those below, to start from clean slate
$ govendor remove github.com/astaxie/beego; rm -rf $GOPATH/.cache/govendor/github.com/astaxie; rm -rf $GOPATH/.cache/govendor/github.com/MachineShop-IOT/beego


# Based on example in README.md, this was the syntax I tried first.
# Command succeeds, but fetches `@develop` from astaxie.
$ govendor fetch github.com/astaxie/beego/^::github.com/MachineShop-IOT/beego@develop

# latest commit hash of fork develop branch
$ govendor fetch github.com/astaxie/beego/^::github.com/MachineShop-IOT/beego@153d76e20071f4e963088c9f815aa003e15c4eb9
# cd /Users/mmindenhall/golang/.cache/govendor/github.com/astaxie/beego; git reset --hard 153d76e20071f4e963088c9f815aa003e15c4eb9
fatal: Could not parse object '153d76e20071f4e963088c9f815aa003e15c4eb9'.
Error: Failed to fetch package "github.com/astaxie/beego": failed to sync repo to revision "153d76e20071f4e963088c9f815aa003e15c4eb9" exit status 128

# Syntax from README.md, would expect this to fetch beego and all subfolders, but from 
# MachineShop-IOT/beego@master.  Revision fetched is from astaxie/beego@master.
$ govendor fetch github.com/astaxie/beego/^::github.com/MachineShop-IOT/beego
```

Is there a bug/regression here, or am I doing something wrong?

**Comment by kardianos** [comment]
I'm not sure what the problem is.

When I run the following in a new repo:
```
govendor init
govendor fetch github.com/astaxie/beego/^::github.com/MachineShop-IOT/beego@develop
```
It pulls down your changes from the develop branch into the `vendor/github.com/astaxie/beego` folder. I can see the change you made to the "template.go" file. Am I missing something?

**Comment by mmindenhall** [comment]
Doing that in an _empty_ repo works.  However, if there's code in the repo that imports the package, something goes awry.  

Easy steps to reproduce:

1.  Start with a new empty repo
1.  `govendor init`
1.  Create `hello.go`:

    ```go
    package main
    
    import "github.com/astaxie/beego"
    
    func main() {
        beego.Run()
    }
    ```
1. `govendor fetch github.com/astaxie/beego/^::github.com/MachineShop-IOT/beego@develop`

The entry in vendor.json will look like this (latest from astaxie/beego@develop):

```json
                {
                        "checksumSHA1": "WjlsvYkIKEUqT60fyO7XfNJ7Uow=",
                        "path": "github.com/astaxie/beego",
                        "revision": "dae2a36eb544ed828c146d8edbf892b405a62f05",
                        "revisionTime": "2016-05-06T05:58:29Z",
                        "tree": true,
                        "version": "develop",
                        "versionExact": "develop"
                },
```

**Comment by kardianos** [comment]
You know what? You are correct. I just realized what change that was made recently that probably caused this. I should be able to add a specific test and fix this.
