### ISSUE TITLE
bug: govendor shows unused and non-existing dependencies as missed

### ISSUE THREAD

**Issue by edganiukov** [kardianos/govendor#152]
Hi,
I faced with problem, when govendor fetchs dependecies that actually has no reference in code and does exist at all.
For example: `govendor fetch golang.org/x/net/context` additionally creates empty `vendor/context` dir and empty `context` entry in `vendor.json`.
When I remove wrong "context" lib (not golang.org/x/net/context), govendor list shows that it is messed:
```shell
$ govendor list
....
m context
```
and
```shell
$ govendor list -v context
  m context
    ├──  v  ...../vendor/golang.org/x/net/context
    └──  v  ..../vendor/golang.org/x/net/http2
```

**Comment by kardianos** [comment]
context is a new package in 1.7. the other x context pkg references. The
empty folder is a bug.

**Comment by edganiukov** [comment]
Thanks for replay. So, if I understand correct, I can ignore it, because I don't it right now, with:
`"ignore": "go1.7"`

**Comment by kardianos** [comment]
Yes
