### ISSUE TITLE
when fetching dependent packages in the same base repo, revision is not respected

### ISSUE THREAD

**Issue by termie** [kardianos/govendor#153]
Happened to me with kubernetes, I did a 

`govendor fetch k8s.io/kubernetes/pkg/kubectl/cmd@01e79b88e1fd589861f92f0d7e2f8b236988a441` 

But many of the other k8s.90/kubernetes dependencies that were added used the most recent revision

**Comment by kardianos** [comment]
Thank you. I need to have fetch default to the specified revision. Right now you need to use `cmd/...@1e7` to specify all the packages.

**Comment by kardianos** [comment]
This should now be fixed on master HEAD.
