### ISSUE TITLE
Support /vendor/ directory

### ISSUE THREAD

**Issue by kardianos** [kardianos/govendor#16]
Determine the ramification of the go tool adding experimental support for the /vendor/ directory.

**Comment by kardianos** [comment]
Support must involve searching for dependencies.

Support will probably allow vendoring by copying into the /vendor/ directory.
We need to move the vendor.json file into the project root to support either location. Rewrites cannot go into the /vendor/ folder.

**Comment by ngrilly** [comment]
> Rewrites cannot go into the /vendor/ folder.

But import path rewriting will not be necessary anymore with the improvements proposed by Russ Cox a few hours ago on golang-dev?

**Comment by kardianos** [comment]
@ngrilly Import path rewriting might go away eventually. However it won't be until 1.6 it could be the default and not until 1.7 until the option becomes mandatory. That's a while yet, and until then I will continue to treat it as an experiment (one I fully support).

For clarity, the following changes need to be made:
1. Move the "vendor.json" file to the root of the project directory.
2. Update "vendor init" to "vendor init {rewrite | copy}". Record in the vendor.json file.
3. Even for rewrites, dependent packages can now be found in the /vendor/ folder. Look in it if found.
4. Support vendoring by copying into /vendor/.

**Comment by kardianos** [comment]
Most of this work has been done in the "importmap" branch. More work remains.

Before merging I want a good path forward (migration) and better output for listing current status.

**Comment by kardianos** [comment]
This is now merged.
