### ISSUE TITLE
Understanding go get if dependencies are checked in

### ISSUE THREAD

**Issue by pawanrawal** [kardianos/govendor#161]
We use govendor to check in all our vendor dependencies in the repo. Now when someone want to install our project should they run

go get -u github.com/dgraph-io/dgraph/... or not have the -u. My thinking is that -u would update deps to latest version which we dont want. We want the version of deps thats checked in. Am i thinking right?

**Comment by abijr** [comment]
Yes, you're thinking right, the correct way is to just use `govendor sync`.  It will download your deps to the `vendor` folder according to your configuration.

The complete process will be to install govendor, run the `govendor sync` and thats it, you've got your deps as recorded in the vendor.json file.

**Comment by pawanrawal** [comment]
I am not sure I even need to run `govendor sync` as all our dependencies are already checked in the repo.

**Comment by kardianos** [comment]
`go get` won't touch the vendor folder. So if you have copied all dependencies locally, a go get will download your repo, install the commands, and be done. Nothing else needed.
