### ISSUE TITLE
Allow status to be passed to sync?

### ISSUE THREAD

**Issue by kris-runzer** [kardianos/govendor#163]
Would it make sense to allow status to be passed to sync?  I find myself wanting to perform a sync operation but only on missing projects.  

The problem I run into is having private repo dependencies.  The private repos may not always be checked in (we pass then into our build server, Concourse CI, to run an isolated build to make sure things will work when pushed).  I managed to get close but find myself stalled:

1. Container is initialized with empty GOPATH
2. Private dependencies are copied to the GOPATH
3. **govendor update +e** copies the private repos into /vendor
4. **govendor list** will show all the other dependencies missing; as expected
5.  Here I would like to be able to run **govendor sync +missing** to have it sync all missing repos at the specified versions into the /vendor folder.

Does this sound like a reasonable request?  Or is the an order of operations that I'm just not seeing that could make this work?

Thanks

**Comment by kardianos** [comment]
`govendor sync` will only operate on missing or outdated packages already by using a checksum hash.

In other words, it should do what you want already without any additional flags.

**Comment by kris-runzer** [comment]
Strange.  I'll re-confirm what I was running into and post a follow up.
