### ISSUE TITLE
Better message (or interactive choice) for conflict.

### ISSUE THREAD

**Issue by tmc** [kardianos/govendor#170]
I want to update all vendored deps ala `govendor update +vendor`

```
Different Canonical Packages for golang.org/x/net/context
    github.com/foo/bar/vendor/golang.org/x/net/context
    github.com/foo/bar/vendor/golang.org/x/net/context
```

what's the right way to update all vendored packages (other than using list and xargs)?

**Comment by kardianos** [comment]
what does `tree -d` say?

**Comment by tmc** [comment]
is `-d` a valid option?

**Comment by kardianos** [comment]
on my tree command. I just want to list directories.

**Comment by mheese** [comment]
Did you guys figure out what to do? I'm seeing the exact same issue currently.

**Comment by kardianos** [comment]
Vendor the vendored package by itself, then re-run the command perhaps.

**Comment by geoffhendrey** [comment]
What is the root cause of this? I see "Different Canonical Packages" when I try to do a "govendor add" and "govendor remove"

**Comment by kaey** [comment]
@geoffhendrey What does `govendor list -v` says?

**Comment by kardianos** [comment]
The root cause is when there is another package in a sub-vendor folder that it is trying to flatten.

I have a prompting lib and routines in govendor, and I have conflict resolution code,  but I have not finished hooking them up together. It would probably be a small change, but I'm somewhat busy at the moment. I would review a PR on the subject.

**Comment by feifei435** [comment]
For those who still don't understand why this happend, let me describe my scenario as an example:
I want to compile project-A which depends on project-B, govendor shold copy project-B's code to project-A's vendor folder in the directory of project-A, but when there is already a vendor folder in project-B's directory, the error [Different Canonical Packages for xxxx] will happend.
What we should do is to delete the vendor folder in project-B's directory, and vendor these deleted files in project-A's vendor folder.
Hope my suggestion will help someone.
