### ISSUE TITLE
govendor fetch ^ fails if package uses vendoring

### ISSUE THREAD

**Issue by nmiyake** [kardianos/govendor#173]
`govendor fetch` calls that use `^` on packages that themselves have a `vendor` directory consistently fail:

```
➜  goapp git:(master) govendor init   
➜  goapp git:(master) ✗ govendor fetch github.com/cloudflare/cfssl/^
Error: Failed to fetch package "github.com/cloudflare/cfssl": copy failed. dest: "/Volumes/git/go/src/github.com/nmiyake/goapp/vendor/github.com/cloudflare/cfssl", src: "/Volumes/git/go/.cache/govendor/github.com/cloudflare/cfssl", pkgPath "/Volumes/git/go/.cache/govendor", err open /Volumes/git/go/src/github.com/nmiyake/goapp/vendor/github.com/GeertJohan/go.rice/LICENSE: no such file or directory
```

Every repo that I've tried with a `vendor` folder so far has failed:
* `github.com/cloudflare/cfssl/^`
* `github.com/aws/aws-sdk-go/^`
* `github.com/nmiyake/govendortest/^`

This issue is a more general version of #168

**Comment by kardianos** [comment]
Thanks for the report. This is reflected in two other issues and a PR. I'll have a fix soon.
