### ISSUE TITLE
govendor fetch on Windows/git: \r\n line endings

### ISSUE THREAD

**Issue by judwhite** [kardianos/govendor#175]
I have `git config --global core.autocrlf false` and the files use `\n` in the repo I'm trying to vendor.

I noticed a lot of changed files in my `./vendor` while migrating from manual to `govendor` related to line endings. The repo containing the vendor folder doesn't override `core.autocrlf`.

I tried using Cygwin bash to run `govendor` and got the same results.

Any ideas what could be causing this?

**Comment by kardianos** [comment]
Maybe they are getting gofmt formatted, which uses \n?
Generally I use checkin,checkout, as-is.

**Comment by judwhite** [comment]
My mistake, I completely failed to mention what's happening other than in the less-than-clear title :)

Expected: `\n` Actual: `\r\n`

`core.autocrlf false` is checkin,checkout as-is. It's `\n` in the source repo, I'm getting `\r\n` on disk using `govendor`. Use `git` or `go get` I get the expected `\n` line endings.

**Comment by kardianos** [comment]
uhhh, I don't know. There is nothing that I know of in govendor that would
alter the line endings. I can look into it a bit, especially if you can
make a repo case, I do have a windows box with msys git.

**Comment by judwhite** [comment]
Tried on another computer with a fresh repo and couldn't reproduce using the same dependencies. I'll try on the computer where I saw this and see if I can repro again tonight.

**Comment by kardianos** [comment]
If you can reproduce, feel free to reopen this issue.
