### ISSUE TITLE
Is there any plan to merge "rewrite" branch into master?

### ISSUE THREAD

**Issue by bshi** [kardianos/govendor#177]

**Comment by kardianos** [comment]
The rewrite branch is historical when we vendored into "internal", before the vendor folder existed.

Why do you ask?

**Comment by bshi** [comment]
Ah, sounds like I misinterpreted what the branch was doing.  I ask because I was curious if there is (planned?) support for rewriting import paths ala [1] as a workaround to issues like https://github.com/golang/go/issues/12432

[1] https://groups.google.com/forum/#!topic/golang-dev/nMWoEAG55v8%5B1-25%5D

**Comment by kardianos** [comment]
Yes, this rewrite branch dates to when this thread was authored. That thread is outdated.

The issue you stated isn't an "issue". You can have the same problem regardless of whether you rewrite the import path explicitly or put it in the vendor folder.

You can use the "rewrite" branch if you'd like to, it should still work, but I don't plan to maintain it more. I just didn't want someone who might need it for legacy reasons to be out of luck finding it.
