### ISSUE TITLE
fetch should default to stated revision for all sub packages.

### ISSUE THREAD

**Issue by VojtechVitek** [kardianos/govendor#179]
Hi,
I'm trying to update one dependency using:

```bash
$ govendor fetch upper.io/db@v2-beta1
```

I need the latest v2-beta branch to be checked out. The latest commit on remote branch is a5a03b3179af11bb6e0ccb65cde85919de0a959e btw.

---

After running the command:

```diff
diff --git a/vendor/upper.io/db/db.go b/vendor/upper.io/db/db.go
index 49705a3..8dd71af 100644
--- a/vendor/upper.io/db/db.go
+++ b/vendor/upper.io/db/db.go
@@ -209,6 +209,9 @@ type Database interface {
        // WithSession returns a clone of the session on the given sess context. sess
        // can be a sql.DB or sql.Tx.
        WithSession(sess interface{}) (Database, error)
+
+       // ClearCache clears all caches the session is using.
+       ClearCache()
 }

 // Tx is an interface that provides the same methods that the `db.Database`
diff --git a/vendor/vendor.json b/vendor/vendor.json
index 6a092b2..45e711b 100644
--- a/vendor/vendor.json
+++ b/vendor/vendor.json
@@ -910,10 +910,10 @@
                        "revisionTime": "2016-02-23T11:51:14Z"
                },
                {
-                       "checksumSHA1": "M9DVhFLrSM9WibjU6vstj/IQiEg=",
+                       "checksumSHA1": "DfPCZ3rRCdzpVfX+M10iRiYbmSA=",
                        "path": "upper.io/db",
-                       "revision": "ed1140f598c7f6f54bd4764b6a9de5d964ef2570",
-                       "revisionTime": "2016-04-13T12:54:26Z",
+                       "revision": "a5a03b3179af11bb6e0ccb65cde85919de0a959e",
+                       "revisionTime": "2016-06-29T17:38:24Z",
                        "version": "v2-beta1",
                        "versionExact": "v2-beta1"
                },
```

Everything seems correct, govendor pulled the right revision a5a03b3179af11bb6e0ccb65cde85919de0a959e -- but it **failed to pull all the new commits from that revision**. In other words, some commits/changes are missing. How can I fix this? Am I doing something wrong?

**Comment by VojtechVitek** [comment]
Actually, I think I found a fix:

```bash
$ govendor fetch upper.io/db/...@v2-beta1
```

I didn't fetch all subpackages before. So this is not a bug -- but something not really obvious :-/

@kardianos Do you think we should update README / CLI help to make this behavior more clear? I bet there're more people like me doing the same mistake. :) Thanks!

**Comment by kardianos** [comment]
I actually want to change this behavior in govendor, so that it defaults to what you expected initially. I just haven't made the time to begin that modification.

**Comment by VojtechVitek** [comment]
Nice, that'd be great!

**Comment by VojtechVitek** [comment]
Thank you!
