### ISSUE TITLE
Fetch private repo using SSH

### ISSUE THREAD

**Issue by ly-william** [kardianos/govendor#180]
I have a private project that I want to depend on. In order to fetch it I do:
```
govendor fetch gitlab.com/path/to/my/project
```
It works but it asks me for my gitlab credential. The thing is that I want to automate it on my CI instance as well. I would like to know if it's possible to indicate govendor to fetch the project over SSH (using ssh key only) instead without being prompted anything.

**Comment by kardianos** [comment]
That I don't know. Can you place the ssh key in an ssh agent prior to fetching?

**Comment by ly-william** [comment]
Added my key with `ssh-add ~/.ssh/id_rsa` but govendor still asks for my credential when fetching my repo.

**Comment by ypaq** [comment]
use `git config --global url."git@github.com:".insteadOf "https://github.com/"`

**Comment by kardianos** [comment]
@ly-william Can you confirm if @ypaq 's fix worked (a change or the git remote)?

**Comment by ly-william** [comment]
Yeah seems to work fine. Thanks for the tip @ypaq :+1:
