### ISSUE TITLE
govendor update ignores modified files

### ISSUE THREAD

**Issue by vrischmann** [kardianos/govendor#181]
Hi,

In some cases when I try to update some dep using `govendor update git.example.com/stuff` govendor doesn't update anything.

I've dug around in the code and I believe it's because it stops here: https://github.com/kardianos/govendor/blob/master/context/modify.go#L381

I've set debug to true and added a dprintf just before the return, this is what I get:

    found import: "/Users/sphax/dev/go/src/git.example.com/foobar/vendor/git.example.com/stuff"
    src:  /Users/sphax/dev/go/src/git.example.com/foobar/vendor/git.example.com/stuff
    dest: /Users/sphax/dev/go/src/git.example.com/foobar/vendor/git.example.com/stuff

This looks wrong to me. I stopped digging here, but I'll try to go further today

**Comment by kardianos** [comment]
Hi, could you try to make a test case of this? Thanks.

**Comment by kardianos** [comment]
@vrischmann I think this is fixed at HEAD now. Can you retest please?

**Comment by vrischmann** [comment]
Hi,

sorry I didn't reply earlier. I just did a quick test and it appears to be fixed !

Thanks a lot
