### ISSUE TITLE
govendor test +local not tesing subpackages anymore

### ISSUE THREAD

**Issue by santagada** [kardianos/govendor#185]
I had this line to run all tests on my project:
govendor test +local

and it was running all tests, but at some point after an update it only runs the . package and no subpackages.
go get -u github.com/kardianos/govendor doesn't fixes it.

**Comment by kardianos** [comment]
Can you post the output of `govendor list +local` ?

**Comment by santagada** [comment]
sub <org> <module> for the two folders because this is a private repo

```
govendor list +local
pl  github.com/<org>/<module>
 l  github.com/<org>/<module>/auth
 l  github.com/<org>/<module>/models
 l  github.com/<org>/<module>/perm
 l  github.com/<org>/<module>/permission
 l  github.com/<org>/<module>/plist
 l  github.com/<org>/<module>/tokenverifier
 l  github.com/<org>/<module>/utils
```

It looks correct and in an old version of govendor it worked, It was failing on ci because it had a more up to date version of govendor and now that I updated mine it also fails on my machine (should have look at which version I had before, but I thought there was a way to fix it)

**Comment by santagada** [comment]
any insight @kardianos ?

**Comment by kardianos** [comment]
I'll look into this today. Hang tight. Thanks for the ping.

**Comment by kardianos** [comment]
When I run `govendor fmt -n +local` it matches `govendor list +local`. All the go wrapped commands use the same code paths, so fmt would be the same as test. If in double, you can also run `govendor test -n +local`. At least on the repo example I used, it appeared to work.

Maybe something else changed? Is the repo you are experiencing this on public or can you reproduce it on a public repo?

**Comment by santagada** [comment]
the problem appears to be with passing flags to tests:
govendor -v +local (and -n) works fine but govendor -v +local -config config.drone.cfg only runs the root package test binary for some reason.

**Comment by kardianos** [comment]
Thank you for the additional information. I'll look into it in a day or so.

**Comment by kardianos** [comment]
Please try the latest on master.
I've updated the behavior so it expands the status flags in place without affecting ordering.

**Comment by santagada** [comment]
in the end I removed the options from my project so no easy way to test this, but thanks for fixing it, we might need options again
