### ISSUE TITLE
Add verbose flag

### ISSUE THREAD

**Issue by romeovs** [kardianos/govendor#186]
It would be great to have a `-v` flag for the `govendor` commands, to be able to know what it is doing. For instance, my `govendor sync` takes quite a while because of the number of packages I'm vendoring, so some feedback on where it's at would really be nice (like `go install -v`).

**Comment by johanbrandhorst** [comment]
Seconded

**Comment by onuryilmaz** [comment]
👍

**Comment by lrsmith** [comment]
👍

**Comment by echophage** [comment]
👍

**Comment by asciifaceman** [comment]
👍  for govendor sync, it really sucks when you have *many* deps and it is totally silent during a testing run

**Comment by hasAdamr** [comment]
@kardianos I think this issue could be closed now.

**Comment by adamryman** [comment]
@kardianos I think this issue could be closed now.

**Comment by hsluoyz** [comment]
+1

**Comment by rjansen** [comment]
+1

**Comment by romeovs** [comment]
Looks like it's implemented! Closing.
