### ISSUE TITLE
govendor hangs when the package dir has a node_modules folder on Windows

### ISSUE THREAD

**Issue by andreynering** [kardianos/govendor#187]
Node has a well-known bug on Windows: when the node_modules folder get too deep (almost always), Windows can't handle it anymore and some errors can happen. Ref: https://github.com/nodejs/node-v0.x-archive/issues/6960

So, we have a webapp where we use Gulp to build assets, and govendor refuses to work with the node_modules present:

> govendor update github.com/foo/bar
Error: GetFileAttributesEx D:\...\Go\src\myPackage\node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\node_modules\spdx-license-ids\spdx-license-ids.json: O sistema não pode encontrar o caminho especificado.

As a workaround, if I temporarely move node_modules to another place, then govendor works again.

I know this is not a govendor bug, but a Windows's bug, but maybe you could blacklist `node_modules` while searching for packages? I think govendor probably already do it for, as example, `.git`, `.svn` and other folders.

**Comment by kardianos** [comment]
To me it sounds like a path max length issue. One way I can get around this is to test if the path is longer then MAX_PATH and if so, prefix with `\\?\`. See https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx (search for "Maximum Path Length Limitation"), does that sound like your issue?

**Comment by andreynering** [comment]
Thanks for the fast response.

Yes, this is exactly a path length issue.

I don't know enough to tell if your suggestion will work, but feel free to ask me to test a possible solution.

**Comment by rasky** [comment]
Blacklisting `node_modules` is a good idea anyway, as it's usually a very very deep and large tree of files that contain no Go source code. It can easily waste seconds of execution time. `goimports` has recently added it to the blacklist as well, as speed was suffering (https://github.com/golang/tools/commit/d4a8e583a10c1e702d1accc9e66c104f992115c8)

**Comment by andreynering** [comment]
@kardianos Thanks, tested and working fine! :tada:
