### ISSUE TITLE
`update` does nothing

### ISSUE THREAD

**Issue by alicebob** [kardianos/govendor#190]
Hi,

I can't seem to get `update` do anything.

`govendor` is the latest, `go` is from tip

I have a library in the vendor file, previously vendored with govendor:

```
$ grep -C2 mini vendor/vendor.json 
                {
                        "checksumSHA1": "t2r34bX17qn247TC5GBhJldHU7U=",
                        "origin": "<my repo>/vendor/github.com/alicebob/miniredis",
                        "path": "github.com/alicebob/miniredis",
                        "revision": "739acf22b3b30d1a215153f511f5263896940ab2",
                        "revisionTime": "2016-06-01T13:00:36Z"
```

the repo in GOPATH is newer and on master:

```
$ (cd $GOPATH/src/github.com/alicebob/miniredis && git status && git show)
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
commit dfffc834d6fe472b3097f1bf85b3339678411c67
Author: <me>
Date:   Wed Jul 20 10:12:29 2016 +0200
<etc>
```

but running govendor doesn't update it:

```

$ govendor update github.com/alicebob/miniredis`
$ grep -C2 mini vendor/vendor.json                                                                                          
                {
                        "checksumSHA1": "t2r34bX17qn247TC5GBhJldHU7U=",
                        "origin": "<my repo>/vendor/github.com/alicebob/miniredis",
                        "path": "github.com/alicebob/miniredis",
                        "revision": "739acf22b3b30d1a215153f511f5263896940ab2",
                        "revisionTime": "2016-06-01T13:00:36Z"
```

Did I miss anything? Thanks!

**Comment by gpitfield** [comment]
I've been having this problem as well.

**Comment by alicebob** [comment]
Bisect points to a979ca595b8450cb8fd8b3fa050376bf3f9b6bea being the first broken commit.

**Comment by alicebob** [comment]
Disabling this `if` block:
https://github.com/kardianos/govendor/commit/a979ca595b8450cb8fd8b3fa050376bf3f9b6bea#diff-4ee7a03f4c324f11635a82bbfcbfbddcR289

xor this line:

https://github.com/kardianos/govendor/commit/a979ca595b8450cb8fd8b3fa050376bf3f9b6bea#diff-4ee7a03f4c324f11635a82bbfcbfbddcR287

makes the update seem to work. Tests won't pass anymore, though.

@kardianos you have any idea?

**Comment by kardianos** [comment]
Assuming tip is broken still? I'll look at today.

**Comment by kardianos** [comment]
Oh! I know why. If you remove your origin line, it will fix it.

I need to ignore the origin line if it points to self. I'll issue a fix for this soon.

**Comment by alicebob** [comment]
Seems to work. Thanks!
