### ISSUE TITLE
Documentation for vendor.json

### ISSUE THREAD

**Issue by bigdrum** [kardianos/govendor#192]
I find it much easier to work with vendor.json instead of figuring out different commands to manipulate its state. It feels more declarative and deterministic to me.

I wonder if the project can give an official documentation?

**Comment by kardianos** [comment]
https://github.com/kardianos/vendor-spec

I suppose that would work. Just ensure you run `govendor sync` after you modify it.

**Comment by bigdrum** [comment]
Cool, thanks!
