### ISSUE TITLE
govendor pulls the program package itself in the vendor folder

### ISSUE THREAD

**Issue by achille-roussel** [kardianos/govendor#194]
Hello,

I'm not sure if this is by design or a bug but I'm seeing a weird behavior where govendor pulls program package itself in the vendor folder. I believe this happens because the dependency structure look like this:
```
github.com/segmentio/ecs-logs/
  main.go (import github.com/segmentio/ecs-logs/lib and github.com/segmentio/ecs-logs/lib/package)
  lib/
    ...
    package/
      (import github.com/segmentio/ecs-logs/lib)
```

Here's an example, from the github.com/segmentio/ecs-logs package:
```
$ govendor init
$ govendor fetch -v .
Get latest revision "github.com/segmentio/ecs-logs"
...
```
```
$ ls -l vendor/github.com/segmentio/
total 0
drwxr-xr-x   9 achilleroussel  staff  306 Jul 31 13:15 ecs-logs
...
```

I've tried identifying if this could be a problem (my understanding is the sub-packages would use the sources in the repo instead of the vendor folder if they find the package they're looking for) so I made added a function to the main package and referenced it from one of the sub packages:
- building the main package still works as expected, I assume its presence in the vendor folder was ignored then
- building one of the sub-packages indepdently fails, go claims it couldn't find the new function, I'm assuming that in that case the version in the vendor folder was used instead (not really sure why go behaves differently there)

I'm not sure if there's a way to prevent govendor from downloading the main package I've tried `go fetch -v ^local` (I thought it would exclude local packages) but nothing gets downloaded then. I've also tried listing the packages in the ignore field also without success.

Right now the best option I found was to just run this:
```
$ govendor init
$ govendor fetch -v .
$ govendor remove $(pwd | sed "s~$GOPATH/src/~~")
```

Please let me know if there's a way I can just prevent the local packages from being downloaded into the vendor folder.

**Comment by kardianos** [comment]
Try "govendor fetch +v"

**Comment by achille-roussel** [comment]
Thanks for replying quickly.

I've tried this:
```
govendor init
govendor fetch +v
```
but govendor doesn't do anything and just returns right away with return code 0.

**Comment by achille-roussel** [comment]
I've also tried `govendor fetch +external` which does almost what I need, the only issue is it doesn't download a dependency that's listed as "local" although I'm not sure why:

- The package is github.com/segmentio/ecs-logs
- The dependency is named github.com/segmentio/ecs-logs-go and is seen as "local", maybe because the main package is a prefix

```
$ govendor list +local
pl  github.com/segmentio/ecs-logs
 l  github.com/segmentio/ecs-logs-go
 l  github.com/segmentio/ecs-logs-go/apex
 l  github.com/segmentio/ecs-logs/lib
 l  github.com/segmentio/ecs-logs/lib/cloudwatchlogs
 l  github.com/segmentio/ecs-logs/lib/datadog
 l  github.com/segmentio/ecs-logs/lib/journald
 l  github.com/segmentio/ecs-logs/lib/loggly
 l  github.com/segmentio/ecs-logs/lib/statsd
 l  github.com/segmentio/ecs-logs/lib/syslog
```

**Comment by kardianos** [comment]
This is an issue with how I classify dependencies. for now you can run "
github.com/segmentio/ecs-logs-go/..."

**Comment by achille-roussel** [comment]
I'm sorry I'm not sure I understand what you mean.

I've tried to track down the issue and I think I've got a fix, sending a PR now.

**Comment by wadey** [comment]
I just ran into the same issue. I expected the following to workaround it, but it still duplicates the package itself:

```
govendor fetch -v +outside,^local
```

I can confirm this workaround works though:

```
govendor fetch -v +outside
govendor remove +local
```

**Comment by achille-roussel** [comment]
`+local` kind of worked, but unfortunately it was removing another dependency that was mistakenly seen as local in my case (because the main package was a prefix of the dependency).

**Comment by wadey** [comment]
@kardianos #195 did not fix this issue, it is still occurring. #195 just fixed a bug with the workaround. `git fetch +outside` is still putting stuff that should be in `+local` into `vendor/` for the case described here.

**Comment by kardianos** [comment]
Thanks. I'll look into further myself in a bit.

**Comment by achille-roussel** [comment]
@wadey you're right sorry I had tagged the PR as fixing this issue but it's just a workaround.

**Comment by wadey** [comment]
@kardianos @achille-roussel I have created a really simple repo that reproduces the issue. See the README for reproduction steps: https://github.com/wadey/govendor194

**Comment by kardianos** [comment]
Thanks. I hope to look into it soon.

**Comment by achille-roussel** [comment]
Thanks for fixing it!
