### ISSUE TITLE
Add `-n` flag to `govendor sync`

### ISSUE THREAD

**Issue by sean-** [kardianos/govendor#196]
Instead of actually pulling in the vendored updates, when the `-n` flag is specified `govendor sync` will only show you what's outdated compared to upstream without updating anything locally.  This will allow a developer to cherrypick upstream updates without syncing the entire tree.

**Comment by kardianos** [comment]
In hindsight, I could have probably omitted `status` and just have `sync -n`.

**Comment by sean-** [comment]
!  Actually, I think we talked past each other on this one: I was hoping `govendor sync -n` would do the network IO to figure out what is out of date and only print something if it is out of date.  For instance, running:

```
$ govendor sync -n
fetch "github.com/armon/circbuf"
fetch "github.com/armon/go-metrics"
fetch "github.com/armon/go-radix"
fetch "github.com/bgentry/speakeasy"
fetch "github.com/hashicorp/errwrap"
fetch "github.com/hashicorp/go-msgpack/codec"
fetch "github.com/hashicorp/go-multierror"
fetch "github.com/hashicorp/go-syslog"
fetch "github.com/hashicorp/go.net/internal/iana"
fetch "github.com/hashicorp/go.net/ipv4"
fetch "github.com/hashicorp/go.net/ipv6"
fetch "github.com/hashicorp/logutils"
fetch "github.com/hashicorp/mdns"
fetch "github.com/mattn/go-isatty"
fetch "github.com/miekg/dns"
fetch "github.com/mitchellh/cli"
fetch "github.com/mitchellh/mapstructure"
fetch "github.com/ryanuber/columnize"
fetch "golang.org/x/sys/unix"
```

That output isn't terribly useful beyond telling me what needs to happen, but I could do that with something like `govendor list -no-status +v | xargs -n1 printf "govendor fetch %s\n"`.  The ideal is to have `govendor sync -n` pull down the sha and compare it with what's in `vendor.json` and emit something if the version is newer.  For a project that is tracking `master` I expect this to change constantly, but for something that's tracking a branch, I wouldn't expect this to change unless someone has committed to a branch.

Make sense?

**Comment by kardianos** [comment]
Are you asking for something similar to: https://github.com/kardianos/govendor/issues/122 ?

Because "sync" doesn't update packages, it only pulls down existing packages at the existing revision if they don't match the checksum (modified or missing).

**Comment by sean-** [comment]
@kardianos Oh... hrm.  I thought `govendor fetch` pulled down what was upstream ala `go get .`.  I was using `govendor sync -n` to find a list of what to update and then pulling each update via `govendor fetch pkgspec`, but that doesn't look like it was doing what I thought it was doing.

**Comment by kardianos** [comment]
There is currently no way in the govendor tool to determine which libraries could be updating, without actually updating them with `govendor fetch`. (issue #122)

`govendor sync` is designed primarily for users who do not wish to store vendor source code in the same repo, and thus need a way to pull down the exact revision (git hash) stored in the vendor.json file.

`govendor sync` never touches remotes to determine if something needs to be pulled down. It only uses the stored checksum in the vendor.json folder and compares that with the computed checksum (SHA1 of filename, import path, file content). This way both missing and manually modified code will be discovered.

Your above command will update GOPATH, but it won't update do a proper comparison. There is currently no command that will do that. Again, #122 should be resolved for this. If you have a preference for a UX for the command to do that, please comment there.
