### ISSUE TITLE
Govendor sync and get fail w/ gcloud (child deps)

### ISSUE THREAD

**Issue by tejasmanohar** [kardianos/govendor#198]
```
$ govendor sync
Error: Remotes failed for:
	Failed for "google.golang.org/cloud/internal/opts" (failed to get ignore files): open /Users/tejas/dev/.cache/govendor/google.golang.org/cloud/internal/opts: no such file or directory
```

Any idea what this is? Preventing me from moving from Godeps to Govendor. I tried deleting Godeps and just running `govendor init && govendor fetch -v +^local,^vendor,^std` but when I go get -t later, I keep getting
```
package github.com/segmentio/source-runner/vendor/google.golang.org/cloud/compute/metadata

	imports cloud.google.com/go/internal: use of internal package not allowed
```
so latest apparently isn't good

**Comment by kardianos** [comment]
I'll look into. Thanks.

**Comment by kardianos** [comment]
Hmm, I'm not sure what's going on. I think this will be hard for me to diagnose as it looks like `google.golang.org/cloud/internal/opts` doesn't exist on master. To compound it the source-runner repo isn't public.

Have you tried running `govendor migrate` in the root of the repo first? It should migrate the godep file into the vendor file so it keeps the correct revision.
