### ISSUE TITLE
govendor didn't follow symlink

### ISSUE THREAD

**Issue by nplanel** [kardianos/govendor#199]
Currently govendor didn't follow symlink :  patch #197
Now when you are deploying some script (from the CI for example) do the checkout somewhere on your home for example, for many other reason it's more simple to symlink the source (checkout by the CI) to point to $GOPATH/src/$repo

- What's the happen in the symlink configuration

  - go list ./... give you the list of subpackages
  - godep works as well
  - With govendor, govendor return nothing, not even an error, as he didn't follow symlink, even if your current directory is the repo.himself.

- The long way/story with a repo (devstack) using our repo (skydive) :

For example, in our repo we have a devstack script that is running by devstack repository (devstack.org)
When you running devstack, it will clone the repository for you github.com/skydive-project/skydive in "/opt/skydive" and launch the script in our repo "devstack/plugin.sh"

There are multiple step, but check the function "install_skydive" in this script.
As we don't want to copy the source code, we doing a symlink to the $GOPATH/src/github/skydive-project/skydive 

**Note** : make sure your are on the commit id 9e9e8296ba7d4c1783b830ba5ee25377b1c3fdcc)
git clone github.com/skydive-project/skydive ; cd .../skydive
git checkout 9e9e8296ba7d4c1783b830ba5ee25377b1c3fdcc

Before using govendor, we used GoDeps and this symlink trick was working fine with all go tools.

- The simple way to reproduce the issue

go get github.com/skydive-project/skydive
cd $GOPATH/src/github.com/skydive-project
mv skydive skydive.real ; ln -s $PWD/skydive.real skydive
cd skydive
govendor list +local  (or any other govendor command)

**Comment by kardianos** [comment]
Okay, that explains why you only follow symlinks in the beginning of walk, but not in the walk function itself. It also explains the motivation. That sounds reasonable and the code change is small.

**Comment by johanbrandhorst** [comment]
Also seeing this problem in our CI environment, would greatly appreciate this issue solved.

**Comment by nplanel** [comment]
@kardianos ping, Have you seen the latest patch ?

**Comment by kardianos** [comment]
Thanks for the patch. But the way, this is now merged.
