### ISSUE TITLE
Update Bowery/prompt to latest

### ISSUE THREAD

**Issue by qbit** [kardianos/govendor#202]
Sorry if this isn't the proper place to ask for this, but would it be possible to bump the Bower/prompt dep to [d43c2707a6c5a152a344c64bb4fed657e2908a81](https://github.com/Bowery/prompt/commit/d43c2707a6c5a152a344c64bb4fed657e2908a81)? This commit has fixes that make prompt work on OpenBSD and friends.

I would do it myself, but it seems using govendor is required to update the vendor.json file :D

If there is a different procedure I should follow, please let me know!

**Comment by kardianos** [comment]
Updated.
Thanks!
