### ISSUE TITLE
Dotfiles are ignored when copying trees

### ISSUE THREAD

**Issue by kaey** [kardianos/govendor#208]
Some npm build scripts use dotfiles.
Grafana for example requires .jscs.json to be present, when running npm run build.

**Comment by kaey** [comment]
> The only other option I can think of is to add a copy whitelist in vendor.json. Thoughts?

I thought about it and I don't like it, because it would result in manual add to whitelist, vendor, test, fail, repeat until it works cycle.
Let's see if anybody else hits this issue.

**Comment by SilverRainZ** [comment]
When copying tree from a package in $GOPATH, the `.gitignore` file will not be copied, some files which are ignored (such as binary) in the original package will be vendored - which is unreasonable.

**Comment by kaey** [comment]
Proper fix here was to blacklist .git/.svn/.etc and allow everything else. That would work because supported vcs'es are hardcoded anyway.

However vendoring ship has (thankfully) sailed, so this is no longer an issue.
