### ISSUE TITLE
local packages are being marked as external in v1.0.4

### ISSUE THREAD

**Issue by rumanhassan** [kardianos/govendor#209]
HI 
I have updated govendor to the latest version **1.0.4** . After updating the govendor version, I have updated  all the packages using "govendor update +e",  after this update it marked all my local packages as external. 

Before updating the version, i was getting "**l**" label for all my local packages. Any suggestion or help is really appreciated.

Thanks.

**Comment by kardianos** [comment]
I just tagged 1.0.5 (same as previous master). Can you either re-test? If still an issue, can you give me a way to reproduce it?

Thanks.

**Comment by rumanhassan** [comment]
Thanks for the reply.

I updated the version to 1.0,5, but still the issue persist. I followed below steps with v1.0.5

- Created New Workspace
- updated GOPATH to this new workspace
- installed govendor "go get -u github.com/kardianos/govendor"
- verified the version using "govendor -version". O/P: v1.0.5
- visited project directory "C:/<username>/<GOPATH>/src/<project>/<repository>"
- then run "govendor init"
- then "govendor list" all my local packages are marked as **"e"**
- then "govendor add +e"
- then "govendor sync" to install all third part missing packages

Did i miss anystep or did anything wrong?

**Comment by rumanhassan** [comment]
Is there a way that i can use the older version of govendor rather than latest one?

Thanks

**Comment by kardianos** [comment]
RE older version: Yes, you can go to the govendor source folder in your gopath, checkout the version you want, then run "go install".

Re procedure: If you ran "add" you don't need to run "sync" directly afterwards.  Can you send the output of `govendor list -v` please?

**Comment by rumanhassan** [comment]
reverting back to v1.0.2 resolves my issue....

**Comment by kardianos** [comment]
Okay. I'd still appreciate a listing from `govendor list -v`.

**Comment by rumanhassan** [comment]
here is my vendor list with v1.0.5

$ govendor list
 v  bitbucket-eng/bitbucket/dev/repo-name/apps                                                                                                                                         
 v  bitbucket-eng/bitbucket/dev/repo-name/awscloud                                                                                                                                     
 v  bitbucket-eng/bitbucket/dev/repo-name/commands                                                                                                                                     
 v  bitbucket-eng/bitbucket/dev/repo-name/config                                                                                                                                       
 v  bitbucket-eng/bitbucket/dev/repo-name/constants                                                                                                                                    
 v  bitbucket-eng/bitbucket/dev/repo-name/consumer                                                                                                                                     
 v  bitbucket-eng/bitbucket/dev/repo-name/controller                                                                                                                                   
 v  bitbucket-eng/bitbucket/dev/repo-name/core                                                                                                                                         
 v  bitbucket-eng/bitbucket/dev/repo-name/data                                                                                                                                         
 v  bitbucket-eng/bitbucket/dev/repo-name/global                                                                                                                                       
 v  bitbucket-eng/bitbucket/dev/repo-name/handlers                                                                                                                                     
 v  bitbucket-eng/bitbucket/dev/repo-name/helper                                                                                                                                       
 v  bitbucket-eng/bitbucket/dev/repo-name/models                                                                                                                                       
 v  bitbucket-eng/bitbucket/dev/repo-name/persist                                                                                                                                      
 v  bitbucket-eng/bitbucket/dev/repo-name/producer                                                                                                                                     
 v  bitbucket-eng/bitbucket/dev/repo-name/router                                                                                                                                       
 v  bitbucket-eng/bitbucket/dev/repo-name/version                                                                                                                                      
 v  bitbucket-eng/bitbucket/dev/kafkaclient                                                                                                                                                      
 v  bitbucket-eng/bitbucket/dev/log                                                                                                                                                              
 v  bitbucket-eng/bitbucket/dev/mdb                                                                                                                                                              
 v  bitbucket-eng/bitbucket/dev/middleware                                                                                                                                                       
 v  bitbucket-eng/bitbucket/dev/sysmodels/datapack                                                                                                                                               
 v  bitbucket-eng/bitbucket/dev/utils                                                                                                                                                            
 v  bitbucket-eng/bitbucket/dev/validate                                                                                                                                                         
 v  bitbucket-eng/bitbucket/devnl/repo-name/hyst                                                                                                                                  rix
 v  bitbucket-eng/bitbucket/devnl/repo-name/log                                                                                                                                   
 v  bitbucket-eng/bitbucket/devnl/repo-name/rbac                                                                                                                                  
 v  bitbucket-eng/bitbucket/devnl/repo-name/serv                                                                                                                                  ice_discovery
 v  github.com/Shopify/sarama                                                                                                                                                                                     
pv  github.com/Shopify/sarama/examples/http_server                                                                                                                                                                
pv  github.com/Shopify/sarama/tools/kafka-console-consumer                                                                                                                                                        
pv  github.com/Shopify/sarama/tools/kafka-console-partitionconsumer                                                                                                                                               
pv  github.com/Shopify/sarama/tools/kafka-console-producer                                                                                                                                                        
 v  github.com/Sirupsen/logrus                                                                                                                                                                                    
 v  github.com/Songmu/prompter                                                                                                                                                                                    
 v  github.com/afex/hystrix-go/hystrix                                                                                                                                                                            
 v  github.com/afex/hystrix-go/hystrix/metric_collector                                                                                                                                                           
 v  github.com/afex/hystrix-go/hystrix/rolling                                                                                                                                                                    
 v  github.com/asaskevich/govalidator                                                                                                                                                                             
 v  github.com/aws/aws-sdk-go/aws                                                                                                                                                                                 
 v  github.com/aws/aws-sdk-go/aws/awserr                                                                                                                                                                          
 v  github.com/aws/aws-sdk-go/aws/awsutil                                                                                                                                                                         
 v  github.com/aws/aws-sdk-go/aws/client                                                                                                                                                                          
 v  github.com/aws/aws-sdk-go/aws/client/metadata                                                                                                                                                                 
 v  github.com/aws/aws-sdk-go/aws/corehandlers                                                                                                                                                                    
 v  github.com/aws/aws-sdk-go/aws/credentials                                                                                                                                                                     
 v  github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds                                                                                                                                                        
 v  github.com/aws/aws-sdk-go/aws/credentials/endpointcreds                                                                                                                                                       
 v  github.com/aws/aws-sdk-go/aws/credentials/stscreds                                                                                                                                                            
 v  github.com/aws/aws-sdk-go/aws/defaults                                                                                                                                                                        
 v  github.com/aws/aws-sdk-go/aws/ec2metadata                                                                                                                                                                     
 v  github.com/aws/aws-sdk-go/aws/request                                                                                                                                                                         
 v  github.com/aws/aws-sdk-go/aws/session                                                                                                                                                                         
 v  github.com/aws/aws-sdk-go/aws/signer/v4                                                                                                                                                                       
 v  github.com/aws/aws-sdk-go/private/endpoints                                                                                                                                                                   
 v  github.com/aws/aws-sdk-go/private/protocol                                                                                                                                                                    
 v  github.com/aws/aws-sdk-go/private/protocol/json/jsonutil                                                                                                                                                      
 v  github.com/aws/aws-sdk-go/private/protocol/jsonrpc                                                                                                                                                            
 v  github.com/aws/aws-sdk-go/private/protocol/query                                                                                                                                                              
 v  github.com/aws/aws-sdk-go/private/protocol/query/queryutil                                                                                                                                                    
 v  github.com/aws/aws-sdk-go/private/protocol/rest                                                                                                                                                               
 v  github.com/aws/aws-sdk-go/private/protocol/restxml                                                                                                                                                            
 v  github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil                                                                                                                                                        
 v  github.com/aws/aws-sdk-go/private/waiter                                                                                                                                                                      
 v  github.com/aws/aws-sdk-go/service/cloudtrail                                                                                                                                                                  
 v  github.com/aws/aws-sdk-go/service/iam                                                                                                                                                                         
 v  github.com/aws/aws-sdk-go/service/s3                                                                                                                                                                          
 v  github.com/aws/aws-sdk-go/service/sts                                                                                                                                                                         
 v  github.com/benschw/dns-clb-go/clb                                                                                                                                                                             
 v  github.com/benschw/dns-clb-go/dns                                                                                                                                                                             
 v  github.com/benschw/dns-clb-go/randomclb                                                                                                                                                                       
 v  github.com/benschw/dns-clb-go/roundrobinclb                                                                                                                                                                   
 v  github.com/benschw/dns-clb-go/ttlcache                                                                                                                                                                        
 v  github.com/bsm/sarama-cluster                                                                                                                                                                                 
 v  github.com/codegangsta/negroni                                                                                                                                                                                
 v  github.com/davecgh/go-spew/spew                                                                                                                                                                               
 v  github.com/eapache/go-resiliency/breaker                                                                                                                                                                      
 v  github.com/eapache/go-xerial-snappy                                                                                                                                                                           
 v  github.com/eapache/queue                                                                                                                                                                                      
 v  github.com/go-fsnotify/fsnotify                                                                                                                                                                               
 v  github.com/go-ini/ini                                                                                                                                                                                         
 v  github.com/goanywhere/env                                                                                                                                                                                     
 v  github.com/goanywhere/fs                                                                                                                                                                                      
 v  github.com/golang/snappy                                                                                                                                                                                      
 v  github.com/gopherjs/gopherjs/js                                                                                                                                                                               
 v  github.com/gorilla/context                                                                                                                                                                                    
 v  github.com/gorilla/mux                                                                                                                                                                                        
 v  github.com/hashicorp/go-cleanhttp                                                                                                                                                                             
 v  github.com/jmespath/go-jmespath                                                                                                                                                                               
 v  github.com/jtolds/gls                                                                                                                                                                                         
 v  github.com/klauspost/crc32                                                                                                                                                                                    
 v  github.com/linkedin/goavro                                                                                                                                                                                    
 v  github.com/mattn/go-isatty                                                                                                                                                                                    
 v  github.com/miekg/dns                                                                                                                                                                                          
 v  github.com/nu7hatch/gouuid                                                                                                                                                                                    
 v  github.com/pborman/uuid                                                                                                                                                                                       
 v  github.com/smartystreets/assertions                                                                                                                                                                           
 v  github.com/smartystreets/assertions/internal/go-render/render                                                                                                                                                 
 v  github.com/smartystreets/assertions/internal/oglematchers                                                                                                                                                     
 v  github.com/smartystreets/goconvey/convey                                                                                                                                                                      
 v  github.com/smartystreets/goconvey/convey/gotest                                                                                                                                                               
 v  github.com/smartystreets/goconvey/convey/reporting                                                                                                                                                            
 v  golang.org/x/crypto/ssh/terminal                                                                                                                                                                              
 v  golang.org/x/net/context                                                                                                                                                                                      
 v  golang.org/x/net/context/ctxhttp                                                                                                                                                                              
 vu golang.org/x/net/netutil                                                                                                                                                                                      
 v  golang.org/x/sys/unix                                                                                                                                                                                         
 v  gopkg.in/mgo.v2                                                                                                                                                                                               
 v  gopkg.in/mgo.v2/bson                                                                                                                                                                                          
 v  gopkg.in/mgo.v2/internal/json                                                                                                                                                                                 
 v  gopkg.in/mgo.v2/internal/sasl                                                                                                                                                                                 
 v  gopkg.in/mgo.v2/internal/scram                                                                                                                                                                                
 v  gopkg.in/tylerb/graceful.v1                                                                                                                                                                                   
pl  bitbucket-eng/bitbucket/dev/repo-name

**Comment by rumanhassan** [comment]
As you can see all my local packages "bitbucket-eng/bitbucket/dev/repo-name/" are marked as **v**

**Comment by martinlindhe** [comment]
I too am seeing this bug on Windows

**Comment by martinlindhe** [comment]
Seeing a lot of failed tests on Windows (govendor test ./... +local), might be related so investigating. Not sure i should hijack this issue or create a new?

But my problem appears the same (on 1.0.5 - windows, and `govendor add +external` vendors my local sub-folder as external)

**Comment by kardianos** [comment]
Thanks for the report. I'll test on windows.

**Comment by martinlindhe** [comment]
@kardianos please have a look at #216, which fixes this issue. Even if the fix is not perfect, it pinpoints the cause of error.
