### ISSUE TITLE
1.0.7 not fetching into vendor folder

### ISSUE THREAD

**Issue by F21** [kardianos/govendor#219]
I just upgrade to 1.0.7 and noticed the following problems on Windows 10 (64-bit). I did not test to see if this is a problem on other platforms. Git is `2.10.0.windows.1`

My `GOPATH` is `D:/Work`.

1. I have deleted the `vendor` folder in my project as well as the `.cache` folder in my `GOPATH`.
2. I run `govendor init` in my project and `vendor/vendor.json` is created:

```json
{
	"comment": "",
	"ignore": "test",
	"package": [],
	"rootPath": "gitlab.com/me/project"
}
```

3. I run `govendor fetch github.com/hashicorp/memberlist` and the following happens:
  - govendor clones the repo into `.cache/govendor/github.com/hashicorp/memberlist`.
  - `vendor/github.com/hashicorp/memberlist` is created but is empty.
  - `vendor.json` is updated to:

```json
{
	"comment": "",
	"ignore": "test",
	"package": [
		{
			"path": "github.com/hashicorp/memberlist",
			"revision": ""
		}
	],
	"rootPath": "gitlab.com/me/project"
}
```

**Comment by kcrawley** [comment]
I can confirm this. I've spent a good 8 hours digging through the code trying to fix this issue. There are many embedded assumptions about the file system allowing `:` in the path names (which isn't allowed on windows except in the case of the drive letter identification). The real problem I've found is the mappings it seems to do with subdirs comparing (or something) to other subdirs (/foo/bar::/foo/bar). I just got to the point where the internal git repo started working and ran into that. After taking a look at `pkgspec.go` and `context_test.go` I've pretty much thrown in the towel.

I've poked around in the changelog and it appears as if this may have never worked? In any case, I may pick this back up to at least commit a "working" version over the weekend; even if it's not the solution the maintainer is interested in (it could at least save him the time I've spent troubleshooting).

**Comment by kardianos** [comment]
I'd welcome any thoughts you have on it.
At the end of the day, I think I need to track a new property or translation function in many apsects of the code to work around not allowing ":" in the normal filesystem path. On windows in most cases, the port isn't present so it isn't an issue. On the test or on custom systems, it is much more likely to be an issue.

I'll see what I can do about it. Feel free to post what you find here. Thanks for the effort!

**Comment by kardianos** [comment]
@F21 
I pushed a change to master. Could you please run `go get -u github.com/kardianos/govendor` and try it again? Please run fetch with "-v" and if it fails copy in the output log. Thanks.

**Comment by F21** [comment]
@kardianos Just tested master and it now works correctly! Thanks for fixing this 😄
