### ISSUE TITLE
Govender determines the sha from the whole repo instead of a subtree

### ISSUE THREAD

**Issue by ggeorgiev** [kardianos/govendor#223]
For example, I am using github.com/hashicorp/serf/coordinate - that did not change for more than 6 months. Yet almost every time I run govendor to update the dependencies it keeps updating the hash for it, I assume because it takes the hash for the whole git repo this package is.

I understand that the final result for the code will be exactly the same, but changing (if possible) this to track the subtree sha will reduce my changes in the vendor.json significantly.

**Comment by kardianos** [comment]
Actually, it is designed to determine the hash from just individual packages. Could you paste in your entry for coordinate from vendor.json?

**Comment by ggeorgiev** [comment]
Oh, that's great. I probably misinterpret what is going on then:

What I noticed now is that it actually picked this from some others vendor folder - `"origin": "github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/coordinate",`

 		{
  			"checksumSHA1": "BMEJLBjl91k5k3vMMzzT7G2SO1U=",
  			"path": "github.com/hashicorp/consul/api",
 -			"revision": "f57b84b8078a36f3c5f916799805a28d919a2afd",
 -			"revisionTime": "2016-09-14T17:17:23Z"
 +			"revision": "6f0a3b9bf5c7fd0673213d451bbc9e66f7a9cad9",
 +			"revisionTime": "2016-09-15T20:13:09Z"
  		},
  		{
  			"checksumSHA1": "Uzyon2091lmwacNsl1hCytjhHtg=",
  			"origin": "github.com/hashicorp/consul/vendor/github.com/hashicorp/go-cleanhttp",
  			"path": "github.com/hashicorp/go-cleanhttp",
 -			"revision": "f57b84b8078a36f3c5f916799805a28d919a2afd",
 -			"revisionTime": "2016-09-14T17:17:23Z"
 +			"revision": "6f0a3b9bf5c7fd0673213d451bbc9e66f7a9cad9",
 +			"revisionTime": "2016-09-15T20:13:09Z"
  		},
  		{
  			"checksumSHA1": "E3Xcanc9ouQwL+CZGOUyA/+giLg=",
  			"origin": "github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/coordinate",
  			"path": "github.com/hashicorp/serf/coordinate",
 -			"revision": "f57b84b8078a36f3c5f916799805a28d919a2afd",
 -			"revisionTime": "2016-09-14T17:17:23Z"
 +			"revision": "6f0a3b9bf5c7fd0673213d451bbc9e66f7a9cad9",
 +			"revisionTime": "2016-09-15T20:13:09Z"
  		},

**Comment by kardianos** [comment]
Yeah, it is picking up the revision and revision time from the origin (consul) directory. You should `govendor fetch github.com/hashicorp/serf/coordinate::github.com/hashicorp/serf/coordinate` to reset the origin if that is what you desire. The revision is the GIT hash, the checksumSHA1 is calculated by govendor to ensure freshness.

**Comment by ggeorgiev** [comment]
Nope, I am ok with that - if consul had updated their vendor directory I am ok to have it updated for me too. Hope they use a smart tool as yours and they do not do this very often - without a reason. 

Great tool by the way - thank you.
