### ISSUE TITLE
.dot files ignored?

### ISSUE THREAD

**Issue by felixge** [kardianos/govendor#225]
Hi,

we're currently looking into migrating from godeps to govendor and I noticed that if I update packages via `govendor update` that files starting with a dot (.), e.g. `".travis.yml"` are not copied into the vendor directory.

I couldn't find any mention of this by looking through the docs/issues/code, so I was wondering if this is expected behavior or not?

This isn't a problem for us, I just want to understand how this tool works :).

Thanks
Felix

**Comment by kardianos** [comment]
Yes, they are ignored.

**Comment by felixge** [comment]
Ok, thanks for the quick reply!

Might be nice if this was more explicit, perhaps via the existing ignore mechanism. Anyway, thanks for confirming, going to close this. :)

**Comment by SilverRainZ** [comment]
Hello, Is it configurable? How can I vendor a dotfile?
