### ISSUE TITLE
how to pin dependencies in libraries

### ISSUE THREAD

**Issue by tejasmanohar** [kardianos/govendor#227]
How does govendor handle libraries that use govendor and just commit `vendor/vendor.json` but not the actual dependencies? Does it cycle through each dep and fetch everything listed in `vendor.json`? If not, would you be opposed to that feature?

**Comment by kardianos** [comment]
Already support it.
add `vendor/*/` to your ignore file
Then after a clone ensure you run `govendor sync` which will bring down the deps into the vendor folder at the locked revision.
