### ISSUE TITLE
what all to clear for scratch govendor fetch?

### ISSUE THREAD

**Issue by tejasmanohar** [kardianos/govendor#228]
If I'm facing issues with versions of dependencies that others are not, what all do I need to clear out before I can
```
$ govendor init
$ govendor fetch -v +^local,^vendor,^std
```
from scratch? Switching to a new $GOPATH/workspace often solves it, but I wonder what specifically could go wrong. I've already cleared `~/dev/.cache`.

**Comment by kardianos** [comment]
What if you try `govendor fetch -v +external` ?
What does `govendor list -v` say?

**Comment by tejasmanohar** [comment]
i got it, nvm. it was actualy that other people's machines were referring to govendor cache. is there a flag to ignore ~/dev/.cache?
