### ISSUE TITLE
can fetch but not sync dependency

### ISSUE THREAD

**Issue by tejasmanohar** [kardianos/govendor#230]
see error & vendor.json here https://gist.github.com/tejasmanohar/19f14e0cf00c4bc20334ef26d8ebf215

I can `govendor fetch` testify without cache but can never get `govendor sync` to like it. Is it due to how they've committed their dependencies? Is this a bug in govendor?

**Comment by kardianos** [comment]
I suspect it is from a bug in a previous version of govendor. Please try to remove and re-add the testify/... packages.

**Comment by tejasmanohar** [comment]
you're right
