### ISSUE TITLE
flag for specifying vendor + vendor/vendor.json directory when using `init`

### ISSUE THREAD

**Issue by gerardmrk** [kardianos/govendor#232]
Would it be okay to request a feature for specifying location of the config directory `vendor` and its file `vendor/vendor.json`, maybe with a flag for the init cmd?

I like to have all my configs files in one directory called `.config` instead of configs polluting the root directory, but govendor is the only tool so far that doesn't let me specify a location. Thanks in advance and sorry for the bother!

**Comment by kardianos** [comment]
@gerardmrk It seems like the vendor.json is already out of the root directory. Also you would need to specify the location of the config file on every invocation as well.

It seems like the goal (to not pollute the root directory) is already accomplished, and the overhead of the added calls may not make it worthwhile. But response to those points welcome.

**Comment by gerardmrk** [comment]
You're right, I'm just being really fussy tbh I think I'll get used to it. Thanks anyways!
