### ISSUE TITLE
Fetching aws-sdk-go doesn't pull down all files

### ISSUE THREAD

**Issue by samprakos** [kardianos/govendor#236]
```govendor fetch github.com/aws/aws-sdk-go@v1.4``` or ```govendor fetch github.com/aws/aws-sdk-go``` only gets sdk.go and none of the sub-packages.

My vendor.json file is this:
```
{
	"comment": "",
	"ignore": "test",
	"package": [
		{
			"checksumSHA1": "IC7p6KuUzBtYTC1KOpfB+KKZTNk=",
			"path": "github.com/aws/aws-sdk-go",
			"revision": "7557129b846473b8edd52853c077d21b7934b699",
			"revisionTime": "2016-10-17T21:13:44Z",
			"version": "v1.4",
			"versionExact": "v1.4.18"
		}
	],
	"rootPath": "github.com/aocsolutions/omaha"
}
```

and my aws-sdk-go package contains this:

```
amprakos:aws-sdk-go\🖕  ls
CHANGELOG.md	Gemfile		LICENSE.txt	Makefile	NOTICE.txt	README.md	sdk.go
```

**Comment by kardianos** [comment]
@samprakos By default govendor will only copy / fetch what your packages use. If you want it to fetch everything, use this command:

`govendor fetch github.com/aws/aws-sdk-go/...@v1.4`

**Comment by samprakos** [comment]
Got it thanks!!
