### ISSUE TITLE
govendor -version exits with value 1

### ISSUE THREAD

**Issue by yanfali** [kardianos/govendor#239]
Hi,

I was wondering why govendor exits with a shell value on unix like platforms of 1? Normally for something that isn't an error and 0 is considered idiomatic on those platforms.

**Comment by adamryman** [comment]
I agree.

[Here is where the exit happens](https://github.com/adamryman/govendor/blob/6be156c795774e9e24709ae384d8f4da55e6e192/main.go#L49)

I feel is there was not an error, then it should not exit 1.

I feel those lines could be removed, or at the very least a case statement added for `GovendorVersion` and `GovendorLicence`.
