### ISSUE TITLE
Coverage Data

### ISSUE THREAD

**Issue by anopheles** [kardianos/govendor#244]
Is it possible to calculate coverage data using govendor?

I tried `govendor test -coverprofile profile.out +local`

but that produces the error: 'cannot use test profile flag with multiple packages'

Is this somehow possible?

**Comment by kardianos** [comment]
I think that is a limitation of the cover tool. I think there are other
tools you can use to get multi-package cover profiles.

**Comment by anopheles** [comment]
Do you have any pointers to multi-package coverage profile tools which handle vendoring, i.e. they ignore the vendor folder?

**Comment by kardianos** [comment]
You could use any tool that allows that, then pass in the package list from `govendor list -no-status +local`

**Comment by anopheles** [comment]
Perfect! That's what I was looking for :+1:
