### ISSUE TITLE
Issue with multiple instances of same package in separate, dependent codebases 

### ISSUE THREAD

**Issue by EwanValentine** [kardianos/govendor#248]
Hi there, I'm having issues with govendor with the same package in multiple projects and it not using the correct one? For example, I have a gRCP server running in service A, service B then makes a client connection to service A using the gRPC package. However, I’m getting an error on compilation, the type checking fails, because the client connection to service A in service B expects the argument to be the gRPC library in service-a/vendors instead of the gRPC library found in service B, if that makes sense?

So the error is something like, when I compile service B, `Argument to ClientConnection expects argument to be type /service-a/vendors/grpc instead got /service-b/vendors/grpc`

I raised an issue about this before but I can't seem to find it, so apologies if it was a dumb question or I missed something obvious, or if this is a duplicate.

Here’s the exact error…

```# bitbucket.org/bandzest/bandzest-service-artists/api
./main.go:45: cannot use conn (type *"bitbucket.org/bandzest/bandzest-service-artists/api/vendor/google.golang.org/grpc".Clien
tConn) as type *"bitbucket.org/bandzest/bandzest-service-auth/api/vendor/google.golang.org/grpc".ClientConn in argument to pro
to.NewAuthClient

**Comment by kardianos** [comment]
Yeah, ensure you only have a single vendor package and not have any dups. That will resolve all such issues.

**Comment by EwanValentine** [comment]
Yes I get that, however, I'm building my Go services using Docker on my Jenkins build server. I don't have Go installed on the Jenkins build server. So I'm including my dependencies using govendor per project, so that everything can be built within a Docker image. However, when I attempt to build the project locally I get this error, so I just wanted to check there wasn't something I was missing

**Comment by kardianos** [comment]
That all sounds good. I think somewhere there is a sub-vendor folder in your vendor folder. Otherwise you wouldn't get that error (?).

**Comment by EwanValentine** [comment]
Ahaaa that could be it actually. I'll double check and report back!

**Comment by EwanValentine** [comment]
@kardianos I needed to include dependency B as a vendor in A, and only include the exact packages I needed, and it seems to compile! Thanks for your patience and help!
