### ISSUE TITLE
same package/version, different sha1 in windows & linux

### ISSUE THREAD

**Issue by booming** [kardianos/govendor#255]
1. I got "The following packages are missing or modified locally: ..." when I try `govendor status` in a different os (I excute `govendor add +external` in windows, push vendor dir to git and pull them in linux and excute `govendor status`). After fetch the exact version of the package then I got a different checksumsha1 in vendor.json, and the error message has gone.  Does that mean Win & Lin have different sha1 implementation in govendor?
2. In some repo, commiter just change mod of some binary. If I change binary mod back and type govendor status, nothing happens. shouldn't I get "The following packages are missing or modified locally: ..." 
forgive my poor english ;)

**Comment by kardianos** [comment]
Do you have git on windows to check-out as-is, check-in as-is, or is it set to modify the line endings?

**Comment by booming** [comment]
I use the default setting(checkout windows-style, commit linux-style). If I just copy Source Code from linux, govendor status turned out to be right. My fault. Thank you.

**Comment by george-polevoy** [comment]
Turns out it's not git's fault.
Here is git config, set globally:
core.autocrlf=input
core.eol=lf
I have everything checked out in LF mode, both the project repo and the dependency project repo.

When I'm using govendor update +e, everything's fine, the files are copied over with LF. When I'm using govendor sync - I'm getting the files copied over with CRLF.

**Comment by kardianos** [comment]
That's because "govendor update +e" pulls from existing GOPATH, while
govendor sync creates a new repo in a temp folder. I would say that
confirms the issue is in fact a line ending per checkout issue.

**Comment by mtibben** [comment]
I fixed this by adding a `.gitattributes` file with
```
* text eol=lf
```
