### ISSUE TITLE
govendor fails on commit with gpg signature

### ISSUE THREAD

**Issue by magiconair** [kardianos/govendor#271]
If you configure git to show a gpg signature in the logs by setting `showSignature = true` in the `[log]` section of the `.gitconfig` file and the git commit has a gpg signature then govendor cannot parse the response from git and fails to add a dependency.

You can try this with `github.com/magiconair/go-metrics-statsd`. 

```
$ govendor add github.com/magiconair/go-metrics-statsd
Error: parsing time "go-left.com>" [ultimate]
gpg:                 aka "Frank Schroeder <frank.schroeder" as "2006-01-02 15:04:05 -0700": cannot parse "go-left.com>" [ultimate]
gpg:                 aka "Frank Schroeder <frank.schroeder" as "2006"
```

The commit log looks like this:

```
commit bcdf8bc (HEAD -> master, origin/master, origin/HEAD)
gpg: Signature made Mon Jan  9 22:45:20 2017 CET
gpg:                using RSA key 13F0C1ADBE7A838644816B1E4D65C6EAEC87DECD
gpg: Good signature from "Frank Schroeder <frank.schroeder@go-left.com>" [ultimate]
gpg:                 aka "Frank Schroeder <frank.schroeder@gmail.com>" [ultimate]
gpg:                 aka "Frank Schroeder <frschroeder@ebay.com>" [ultimate]
Author: Frank Schroeder <frschroeder@ebay.com>
Date:   Mon Jan 9 22:45:04 2017 +0100

    Fix broken mean.
```

My `[log]` section in `~/.gitconfig` looks like this:

```
[log]
	decorate = true
	abbrevCommit = true
	showSignature = true
```

A workaround is to temporarily set `showSignature` to `false`, then run the `govendor` command and revert it again.

**Comment by kardianos** [comment]
Thanks for the report. That does indeed look like an issue. Probably the best fix is to have the parser ignore the gpg lines.

**Comment by magiconair** [comment]
The question is whether gpg is the only way commits can be signed and whether the `gpg:` prefix is the only one that can appear there.

**Comment by base698** [comment]
Anyone up to fix this?!

**Comment by base698** [comment]
Appears to be here:

https://github.com/kardianos/govendor/blob/5d8180ea40937160a96b1da61b3073d021ecb8df/internal/gt/vcs.go#L196

```
	line := strings.TrimSpace(string(out))
	ss := strings.Split(line, "@")
	rev = ss[0]
	tm, err := time.Parse("2006-01-02 15:04:05 -0700", ss[1])
	if err != nil {
		panic("Failed to parse time: " + ss[1] + " : " + err.Error())
	}
```

I made a code change, but I can't get the go run main.go to pick up the change.  How do you build a version to test?  Don't see any build instructions in the readme.

**Comment by magiconair** [comment]
Try `go install` or `go build`

**Comment by base698** [comment]
running those shows version 1.0.8, also go run main.go.  I have a logging statement in and it doesn't show up, it's like it's using my installed govendor and not the built one, even running ./govendor.

**Comment by magiconair** [comment]
`which govendor` ?

**Comment by base698** [comment]
? If it use ./ Or absolute path it does the same as just running govendor

**Comment by base698** [comment]
The version is 1.0.8 in the header

**Comment by base698** [comment]
package cache issue
