### ISSUE TITLE
ignoring appengine dependency problem

### ISSUE THREAD

**Issue by chrisolsen** [kardianos/govendor#275]
I am having a hard time getting `ignore` to ignore the dependencies, primarily `appengine`, that I need it to.

When using govendor in the real-world app I get duplicate errors due to govendor fetching the already existing `$HOME$/Go/src/...` libs and vendoring them.

To try to figure things out I created two libs.

**log**
 * has a public method `Print` that calls on the appengine `log.Debugf()` method.  

**debug**
* has public method `Print` that calls on the `log.Print` method passing in a `context.Context` reference

After running `govendor fetch gitlab.com/chrisolsen/log` in the **debug** library, I get a lot of appengine dependencies. How do I prevent this?

![screenshot 2](https://cloud.githubusercontent.com/assets/41582/22409779/8a794cf8-e64c-11e6-84da-10800858d8b5.png)

**Comment by kardianos** [comment]
The "ignore" field operates only on tags. Most often packages will call out files that are only relevant on appengine. But if you try to import appengine directly, then no tag guards that. 

There could also be a missing filter for ignore packages in the fetch sub-command. Would need investigation.

**Comment by chrisolsen** [comment]
Thanks for the response. With the way things are right now I can't vendor any appengine helper libraries that I have. I will just have to not vendor them for now.

**Comment by kardianos** [comment]
Can you add a build tag to your appengine helper libraries?
```
// +build appengine

package myhelper
```

**Comment by chrisolsen** [comment]
With the appengine app code being within a child directory of the project, moving the vendor folder up to the parent project directory seems to have fixed things.
```
project
  `- app
     - app.yaml
     - app.go
  `- vendor (was app sub-folder)
 ```
Thanks for the help.
