### ISSUE TITLE
GO15VENDOREXPERIMENT support appears to be buggy

### ISSUE THREAD

**Issue by noonien** [kardianos/govendor#28]
```shell
$ govendor list
Error: Vendor file at "vendor" not found.

GO15VENDOREXPERIMENT="1"
It is possible this project requires changing the above env var
or the project is not initialized.

$ govendor init
$ govendor list
Error: Vendor file at "vendor" not found.

GO15VENDOREXPERIMENT="1"
It is possible this project requires changing the above env var
or the project is not initialized.

$ ls
vendor.json
$ mkdir vendor
$ govendor list
$ ls
vendor vendor.json
$ ls vendor
<empty>
```

**Comment by kardianos** [comment]
Oh, init is buggy. (looking for the vendor folder but failed to create in
"init") I'll fix soon.

**Comment by noonien** [comment]
Should the vendor.json file not be in the vendor folder?

```shell
$ ls        
$ rm -rf $GOPATH/bin/govendor $GOPATH/src/github.com/kardianos/govendor
$ govendor
zsh: command not found: govendor
$ go get github.com/kardianos/govendor
$ govendor init
$ tree
.
├── vendor
└── vendor.json

1 directory, 1 file
$ echo "package test\nimport \"github.com/overlordtm/generics\"" > test.go
$ govendor list
e github.com/overlordtm/generics
l test
$ govendor add +ext
$ govendor list
v test/vendor/github.com/overlordtm/generics [github.com/overlordtm/generics]
l test
$ tree
.
├── test.go
├── vendor
│   └── github.com
│       └── overlordtm
│           └── generics
│               ├── generics.go
│               └── Readme.md
└── vendor.json

4 directories, 4 files
```

**Comment by noonien** [comment]
Actually, I've just read that the README.md specified that the vendor.json file is outside the vendor directory. Why not keep the vendor.json file in the vendor folder, so we don't pollute the root package directory.

Also, it would appear govendor can read vendor/vendor.json, but when saving the file is also saved to /vendor.json.

**Comment by kardianos** [comment]
Yes, the tool will discover any "sub" vendor files and read that vendor file meta-data.

The vendor file used to be "internal/vendor.json". However when "vendor" folder was decided, I decided to move it to the root. That makes it easy to make the vendor folder a sub-repo or in the future ignore that  folder and fetch dependencies in real time.

I'm not stuck on the current locations. Implementation might also detect a vendor file in either location and use that. Please open an issue if you think it should.
