### ISSUE TITLE
fetch: Silently ignores invalid package names, but saves them on vendor.json

### ISSUE THREAD

**Issue by ahmetalpbalkan** [kardianos/govendor#281]
Note my erroneous command:

    govendor fetch go get github.com/gorilla/securecookie

It doesn't give any output (makes me think it's success) but when I go to vendor.json I see:

```
		{
			"path": "get",
			"revision": ""
		},
		{
			"path": "go",
			"revision": ""
		},
```

Bug or by design?

**Comment by kaey** [comment]
#171

**Comment by ahmetalpbalkan** [comment]
Closing as duplicate.
