### ISSUE TITLE
Excluded status does not work if package is missing from GOPATH

### ISSUE THREAD

**Issue by johanbrandhorst** [kardianos/govendor#282]
I've got a couple of packages I want to exclude from being vendored, and it seems that when these packages in installed in my $GOPATH, but not in the vendor folder, they are reported as excluded correctly:

```
$ govendor list
ex github.com/cathalgarvey/fmtless/encoding/json
```

However, if I then go and delete the package from my $GOPATH, they show up as status `missing` instead. I think `excluded` should take precedent over `missing`.

```
$ govendor list
m github.com/cathalgarvey/fmtless/encoding/json
```

**Comment by kaey** [comment]
Project can't be built with (m)issing packages.
Maybe it should report both missing and excluded states.

**Comment by johanbrandhorst** [comment]
Explicitly excluded packages should not be listed as missing, surely?

**Comment by nightlyone** [comment]
@johanbrandhorst Possible fix is here https://github.com/kardianos/govendor/issues/300
