### ISSUE TITLE
govendor list performance issue

### ISSUE THREAD

**Issue by qiukeren** [kardianos/govendor#285]
Good for govendor, but i found some issue while do govendor:

While executing govendor on some big repos,
the `govendor list` shows bad performance like:

```
10:10 govendor list start at github.com/cockroachdb/cockroach path
10:30 govendor list still running
``` 

Machine is Macbook 2015 with SSD.

**Comment by kardianos** [comment]
If you can help pinpoint the issue, that would be great. It might be an issue with govendor on osx (I only have tests that run on linux and windows). Can you confirm on a linux box?

**Comment by qiukeren** [comment]
mac using govendor with:

With `pkg/kv` dir on MAC:

```
gopath/src/github.com/cockroachdb/cockroach/pkg/kv $ time govendor list
2000+ dependencies 
real	18m29.267s
user	21m21.737s
sys	0m25.354s
```




With `pkg/util` dir on Docker on MAC (can be considered as linux in virtualbox on MAC):

```
~/gopath/src/github.com/cockroachdb/cockroach/pkg/util # time govendor list
2000 + dependencies                                             
real	0m 49.20s
user	0m 43.60s
sys	0m 7.31s
```

With `pkg/util` dir on MAC:

```
~/gopath/src/github.com/cockroachdb/cockroach/pkg/util $ time govendor list
2000+dependencies
real	18m15.359s
user	21m13.592s
sys	0m23.342s
```

**Comment by qiukeren** [comment]
![image](https://cloud.githubusercontent.com/assets/2325492/23288535/2a73501e-fa7f-11e6-9977-f560c7b6bc3b.png)

Flame graph by `https://github.com/brendangregg/FlameGraph` in dtrace mode in 60 deconds with  `govendor list ~/gopath/src/github.com/cockroachdb/cockroach/pkg/kv`

**Comment by qiukeren** [comment]
Timeout... and close
