### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Thomblin** [kardianos/govendor#296]
Hi there,

I hope you can help me with my installation. I get the following error when trying to fetch govendor 

```
go get -u github.com/kardianos/govendor
# github.com/kardianos/govendor/cliprompt
../../go/src/github.com/kardianos/govendor/cliprompt/cliPrompt.go:13: import /home/sebastian/go/pkg/linux_amd64/github.com/kardianos/govendor/prompt.a: object is [linux amd64 go1.2.1 X:none] expected [linux amd64 go1.6 X:none]
# github.com/kardianos/govendor/context
../../go/src/github.com/kardianos/govendor/context/context.go:18: import /home/sebastian/go/pkg/linux_amd64/github.com/kardianos/govendor/internal/pathos.a: object is [linux amd64 go1.2.1 X:none] expected [linux amd64 go1.6 X:none]
```

I am using Ubuntu 14.04 
3.16.0-77-generic #99~14.04.1-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
and go1.6  linux/amd64

What do I have to do?

Many Thanks in advance

**Comment by kardianos** [comment]
Two points:

 1. https://golang.org/dl/ is your friend (not apt-get) in this case.
 2. `rm $GOPATH/pkg` Then go get it.

**Comment by Thomblin** [comment]
Great. That helped. Thank you very much
