### ISSUE TITLE
feature: Update source files based on the contents of vendor.json.

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#30]
(Apologies if I'm missing this in the documentation.)

Say I have an existing repo with vendored dependencies set up by govendor, including a valid `vendor.json` file that describes exactly the current state of the vendored dependencies. Further, say that I want to update a dependency (call it `foo/bar`) to a specific revision, `123abcd`.

As I understand it, I must do the following:

    go get foo/bar
    cd $GOPATH/src/foo/bar
    git checkout 123abcd
    
    cd $GOPATH/src/dependant
    govendor update foo/bar

This will cause govendor to update `vendor.json` to give the new revision. But note that `vendor.json` is write-only here; it doesn't appear to actually be useful for anything except an audit trail.

Is it instead possible for me to manually edit `vendor.json` to say which revisions I want for my dependencies, then tell govendor to "make it so" and update the `vendor/` directly appropriately?

**Comment by kardianos** [comment]
Your analysis is correct. It currently isn't implemented but it would be good to have. It just hasn't been done yet.

**Comment by kardianos** [comment]
I've finally decided on a design. See: https://github.com/kardianos/govendor/blob/master/DESIGN.md

Feedback welcome.

**Comment by kardianos** [comment]
Added `govendor sync` to master.
