### ISSUE TITLE
excluded packages should not be reported as missing

### ISSUE THREAD

**Issue by nightlyone** [kardianos/govendor#300]
When vendoring any library that supports appengine, the recommened setup is
```json
{
  "ignore": "test appengine/ appengine_internal/",
}
```
but this leads to `govendor list +outside` complaining that we didn't vendor these packages.
```shell
$ govendor list '+outside'
  m appengine                  
  m appengine_internal         
  m appengine_internal/base
```
also govendor list '+outside,^excluded' won't change the output here, since govendor status missing trumps status excluded, which is the actual bug.

I fixed it for me be simply ignoring the fact that the packages are missing for any ignored package.
```diff
diff --git a/context/resolve.go b/context/resolve.go
index f95d3c5..9e693ce 100644
--- a/context/resolve.go
+++ b/context/resolve.go
@@ -367,10 +367,17 @@ func (ctx *Context) addSingleImport(pkgInDir, imp string, tree bool) (*Package,
        dir, gopath, err := ctx.findImportDir(pkgInDir, imp)
        if err != nil {
                if _, is := err.(ErrNotInGOPATH); is {
+                       presence := PresenceMissing
+                       // excluded packages, don't need to be present
+                       for _, exclude := range ctx.excludePackage {
+                               if imp == exclude || strings.HasPrefix(imp, exclude+"/") {
+                                       presence = PresenceExcluded
+                               }
+                       }
                        return ctx.setPackage("", imp, imp, "", Status{
                                Type:     TypePackage,
                                Location: LocationNotFound,
-                               Presence: PresenceMissing,
+                               Presence: presence,
                        }), nil
                }
                return nil, err

```

Now exclusion works as expected:
```shell
$ govendor list '+excluded'
  x appengine                  
  x appengine_internal         
  x appengine_internal/base    
```

and `govendor list '+outside'` finally reports my repository as correctly vendored (which it is as proven by tests already).

@kardianos This finally makes the important appengine use case work :tada:

**Comment by kaey** [comment]
Why don't you exclude appengine by tag?
The problem here is if you exclude some package and it's not in your GOPATH, then ```go build``` will exit with error, but ```govendor list``` will say that everything is in place.

**Comment by nightlyone** [comment]
@kaey because I need to support both: Compiling these packages with appengine and without appengine. When I exclude it by appengine tag, I need to manually all everything that this excluded. 

Everything not excluded is still in place. But exclusion is for things we don't want to vendor.

If that fix is not acceptable, there needs to be another way to specify that behavior of packages being intentionally missing. But this would be more involved, so please​ specify more clearly, why the above fix won't work for you.
