### ISSUE TITLE
Feature Request: Ignore specific files similar to .gitignore

### ISSUE THREAD

**Issue by pcman312** [kardianos/govendor#303]
I have a use case where in the code I want to vendor (project A) I have a couple of files that are test data files. When I do a govendor and pull that project into another (project B) those test files are dragged along even though I don't want them to be. I'd like the ability to specify within project A that govendor should ignore those files. Alternatively, being able to specify those files to be ignored within project B would also work but be less convenient. This is particularly important if those test files are large data files that would take up a lot of space and time to transfer.

**Comment by kardianos** [comment]
Would it work to vendor the tree of the project you want the test files? But then otherwise ignore tests?

**Comment by pcman312** [comment]
Wouldn't that require putting the test files into yet another repo and vendoring it into project A?

**Comment by kardianos** [comment]
I don't think I understand your problem...

**Comment by pcman312** [comment]
I have project A which has two non-go data files that are for unit tests only.
I have project B that vendors project A into it.
When I use govendor on project B it pulls the non-go test data files in to the vendor folder under project B.
Those test data files are unnecessary and could take up a lot of space/time to download. In my particular use case, the data files are small so it's not that big of a deal. However, if those data files were large, then govendor will end up spending time & disk space pulling those unnecessary files into the vendor folder under project B.

I'd like some way of telling either project A or project B to ignore those files when using govendor such that project B does not end up having those files in the vendor folder.

**Comment by kardianos** [comment]
Could you contrast this with just telling govendor to ignore all test files? Are you wanting to keep some test files and ignore other test files?

**Comment by pcman312** [comment]
Well, it's ignoring the test go files (*_test.go) but including the test data files (*_test).

**Comment by kardianos** [comment]
test data files should go into the folder "testdata" which govendor (and the go tool) will ignore.

**Comment by pcman312** [comment]
Ah, I wasn't aware of that. Is that mentioned in the docs somewhere? I can't find a reference to it.

**Comment by kardianos** [comment]
Oh, probably not. Feel free to file another issue or send a PR.

**Comment by pcman312** [comment]
Will do. Thanks for the help.
