### ISSUE TITLE
Install Govendor with "go get -u github.com/kardianos/govendor" on Ubuntu

### ISSUE THREAD

**Issue by themmes** [kardianos/govendor#304]
# System

- Using Ubuntu 16.04 LTS
- go version go1.8 linux/amd64

# Steps

1. Installed go, added repo because `apt` does not serve Go 1.8
```
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt-get update
sudo apt-get install golang-go
```

2. Checked `$GOPATH` by calling `echo $GOPATH`. Appeared empty, so ran `export GOPATH=/home/tom/go/`

3. Get Govendor by calling `go get -u github.com/kardianos/govendor`. Little wait... no feedback whatsoever (is this normal for go package installation?!). But creates following file structure in my `/home/tom/go/` folder:

```
/home/tom/go/
├── bin
│   └── govendor
├── pkg
│   └── linux_amd64
│       └── github.com
│           └── kardianos
│               └── govendor
│                   ├── cliprompt.a
│                   ├── context.a
│                   ...
└── src
    └── github.com
        └── kardianos
            └── govendor
                ├── appveyor.yml
                ├── cliprompt
                │   └── cliPrompt.go
                ├── context
                ...

51 directories, 138 files
```

4. But apparently Govendor is still not installed correctly: `govendor: command not found`

5. I thought it might be the `govendor` folder being in `/github.com/kardianos/`, so tried moving it up and running `go install govendor` manually.

```
tom@hemmes:~/go/src$ go install govendor
govendor/main.go:17:2: cannot find package "github.com/kardianos/govendor/cliprompt" in any of:
	/home/tom/go/src/govendor/vendor/github.com/kardianos/govendor/cliprompt (vendor tree)
	/usr/lib/go-1.8/src/github.com/kardianos/govendor/cliprompt (from $GOROOT)
	/home/tom/go/src/github.com/kardianos/govendor/cliprompt (from $GOPATH)
govendor/main.go:18:2: cannot find package "github.com/kardianos/govendor/help" in any of:
	/home/tom/go/src/govendor/vendor/github.com/kardianos/govendor/help (vendor tree)
	/usr/lib/go-1.8/src/github.com/kardianos/govendor/help (from $GOROOT)
	/home/tom/go/src/github.com/kardianos/govendor/help (from $GOPATH)
govendor/main.go:19:2: cannot find package "github.com/kardianos/govendor/run" in any of:
	/home/tom/go/src/govendor/vendor/github.com/kardianos/govendor/run (vendor tree)
	/usr/lib/go-1.8/src/github.com/kardianos/govendor/run (from $GOROOT)
	/home/tom/go/src/github.com/kardianos/govendor/run (from $GOPATH)
```

# Question

I think I made a rookie mistake somewhere in trying to install your Go package. Could you give me a tip on what's wrong with my setup?

**Comment by themmes** [comment]
As I said, a rookie mistake. The following fixed it:

```
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
sudo go get -u github.com/kardianos/govendor
```

Up and running! `govendor (v1.0.8) ... `

**Comment by spnzig** [comment]
I am facing the same issue with k8s-oidc-helper package. Apparently go is located in /usr/share directory. So i tried
 `export GOPATH=/usr/share/go
export PATH=$PATH:$GOPATH/bin
sudo go get -u github.com/micahhausler/k8s-oidc-helper`

But unfortunately still i get `k8s-oidc-helper: command not found`
Can you please help @themmes

**Comment by themmes** [comment]
@spnzig Awesome, you are getting into Kubernetes!

You get `k8s-oidc-helper: command not found` when trying to run the application I assume. What is the message you get when running `sudo go get -u github.com/micahhausler/k8s-oidc-helper`? Or does it leave you with an awkward silence? Do you have `go` correctly installed?

**Comment by spnzig** [comment]
@themmes thanks for replying. The sudo command did not give any output. But when i did a `go env` i found out that the GOROOT path was /usr/lib. All this while i was setting the GOPATH to /usr/share/go and /usr/bin/go. But then it worked when i set the path to /usr/lib/go. Is there any particular reason why this is happening?

**Comment by themmes** [comment]
@spnzig I do not know the reason for your specific case. For more on why and how of GOPATH and GOROOT see Ian's post here https://groups.google.com/d/msg/golang-nuts/jIdS-O0Rl1k/_IeR46_6XdQJ and the documentation he refers to; https://golang.org/doc/code.html#GOPATH and https://golang.org/doc/install#install

**Comment by pranoygn** [comment]
Hi I'm getting the following error while installing the govendor

`sudo go get -u github.com/kardianos/govendor
# runtime
../src/runtime/proc.go:1257:14: write barrier prohibited by caller; allocm
        /usr/lib/go-1.6/src/runtime/proc.go:1505:14: called by newm
        /usr/lib/go-1.6/src/runtime/proc.go:1596:7: called by startm
        /usr/lib/go-1.6/src/runtime/proc.go:1677:8: called by wakep
        /usr/lib/go-1.6/src/runtime/proc.go:532:8: called by ready
        /usr/lib/go-1.6/src/runtime/mgcmark.go:537:9: called by gcFlushBgCredit
../src/runtime/proc.go:1257:14: write barrier prohibited by caller; allocm
        /usr/lib/go-1.6/src/runtime/proc.go:1505:14: called by newm
        /usr/lib/go-1.6/src/runtime/proc.go:1596:7: called by startm
        /usr/lib/go-1.6/src/runtime/proc.go:2029:9: called by injectglist
        /usr/lib/go-1.6/src/runtime/proc.go:3527:16: called by sysmon
../src/runtime/proc.go:2232:17: write barrier prohibited`
