### ISSUE TITLE
`govendor update` doesn't accept import path filter as documented

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#31]
I'm using govendor at b36aaa3777d87f88818d70d8a8a39a4b462cd9ab, with `GO15VENDOREXPERIMENT` set.

`govendor -h` implies that `govendor update` should accept an import filter. It even gives this example:

    govendor update +ven github.com/company/project/... bitbucket.org/user/pkg

But it doesn't seem to work for me. To reproduce:

    rm -rf $GOPATH/src
    mkdir -p $GOPATH/src/github.com/{jacobsa,googlecloudplatform}
    git clone https://github.com/jacobsa/gcloud.git $GOPATH/src/github.com/jacobsa/gcloud
    git clone https://github.com/GoogleCloudPlatform/gcsfuse.git $GOPATH/src/github.com/googlecloudplatform/gcsfuse
    
    cd $GOPATH/src/github.com/jacobsa/gcloud
    git checkout 34c6f95
    
    cd $GOPATH/src/github.com/googlecloudplatform/gcsfuse
    git checkout 6ce14c9
    
    govendor update github.com/jacobsa/gcloud/gcs/...

The final command gives me this output:

    Error: Package "github.com/jacobsa/gcloud/gcs/..." not a go package or not in GOPATH.

Instead I have to use this awful but effective workaround:

    govendor update $(govendor list +v | ggrep -o -P '(?<=\[)github\.com/jacobsa/gcloud/gcs(/\S+)?(?=\])')

(Side note: it would be nice if `govendor list` output were more amenable to parsing for one-liners like this.)

**Comment by jacobsa** [comment]
@kardianos: at d59b782f7c62686cc3da7371ac52793424a7cd4e the above reproduction instructions are now broken for me in a new way:

```
[...]
% govendor update github.com/jacobsa/gcloud/gcs/...
panic: For package github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching/mock_gcscaching attempt to copy to same location

goroutine 1 [running]:
github.com/kardianos/govendor/context.(*Context).copy(0x820456000, 0x0, 0x0)
        /Users/jacobsa/go/src/github.com/kardianos/govendor/context/context.go:539 +0x7ca
github.com/kardianos/govendor/context.(*Context).Alter(0x820456000, 0x0, 0x0)
        /Users/jacobsa/go/src/github.com/kardianos/govendor/context/context.go:559 +0x2d
main.run(0x8820562470, 0x8203e2010, 0x8203b61b0, 0x3, 0x3, 0x7d15, 0x0, 0x0)
        /Users/jacobsa/go/src/github.com/kardianos/govendor/run.go:307 +0x107b
main.main()
        /Users/jacobsa/go/src/github.com/kardianos/govendor/main.go:14 +0x80
```

Could you please re-open and take a look?

**Comment by kardianos** [comment]
I just pushed an update that might fix or mask this issue.

Later I need to go through these issues and create some unit tests from them. Let me know if it works. If not, I'll take a look in the morning. Thanks!

**Comment by jacobsa** [comment]
That does appear to fix it, thanks. (Special note: I had to use `ba64985` instead of `6ce14c9` in the instructions because I rewrote history.)

I would appreciate it very much if you could add tests to avoid regressing, yeah. Thanks! :-)

**Comment by jacobsa** [comment]
@kardianos: I take it back, there remains a bug: If I run `govendor update foo/bar/...` that appears to update `foo/bar/baz` and `foo/bar/qux`, but not `foo/bar` itself. This is with govendor built at 421e9170c2ce937807c54475cc1a57f6a3a7be13. Could you take a look?

**Comment by kardianos** [comment]
This was a bit by design, though I could see how it is surprising as I think it is different than what the "go" tool does. Opened #32 .
