### ISSUE TITLE
Not ignoring test file when it also have "go1.8" tag

### ISSUE THREAD

**Issue by av-elier** [kardianos/govendor#312]
I expected that `"ignore": "test"` in vendor.json will ignore all `_test.go` files. But if you try to vendor github.com/lib/pq, with `"ignore": "test"` govendor will still vendor file: https://github.com/lib/pq/blob/master/go18_test.go

This file have "tags" ` AND (test OR (go1.8))`. Looks like the problem is related with that. 

A bash script to reproduce the problem:
```
cd $GOROOT/src
mkdir govendor_lib_pq
cd govendor_lib_pq
mkdir vendor
echo '{"comment": "","ignore": "test","package": [{"checksumSHA1": "R/B2oygnrr9aQSRIIujSK+oS8tk=","path": "github.com/lib/pq","revision": "2704adc878c21e1329f46f6e56a1c387d788ff94","revisionTime": "2017-03-24T20:46:54Z"},{"checksumSHA1": "q5SZBWFVC3wOIzftf+l/h5WLG1k=","path": "github.com/lib/pq/oid","revision": "2704adc878c21e1329f46f6e56a1c387d788ff94","revisionTime": "2017-03-24T20:46:54Z"}]}' > vendor/vendor.json
govendor sync
go test ./...
```
Getting `FAIL	govendor_lib_pq/vendor/github.com/lib/pq [build failed]`
Expecting to get `?   	govendor_lib_pq/vendor/github.com/lib/pq [no test files]`

**Comment by kardianos** [comment]
Thank you for catching this. Please open another issue if you find something else.
