### ISSUE TITLE
how to  modify the target path

### ISSUE THREAD

**Issue by wangzhezhe** [kardianos/govendor#313]
If the govendor provide the mechanism like [gom](https://github.com/mattn/gom) which could modify the target of packet path :
```
gom 'internal repo name/projectname',		:private=>'true', :insecure=>'true', :skipdep=>'true', :target=>'github repo name /projectname'	
```
so I could change the path of package to path on github if I down load this package from internal network environment automatically by description files.

**Comment by kaey** [comment]
```
govendor fetch github.com/team/pkg::corp.org/repo/pkg
```

**Comment by wangzhezhe** [comment]
Thanks a lot, could I define this operation in description files?@kaey

**Comment by kaey** [comment]
It's described here https://github.com/kardianos/govendor#package-specifier and in FAQ https://github.com/kardianos/govendor/blob/master/doc/faq.md#q-ive-forked-a-package-and-i-havent-upstreamed-the-changes-yet-what-should-i-do

**Comment by wangzhezhe** [comment]
Thanks for your patience !
