### ISSUE TITLE
Complex build tags broken again

### ISSUE THREAD

**Issue by johanbrandhorst** [kardianos/govendor#315]
The fix for #312 broke the resolver for the `github.com/lib/pq` package with `solaris` ignored. Whereas before the fix it would download `user_posix.go` appropriately on linux systems, with the fix it doesn't include it anymore.

Steps to reproduce:

1. Add vendor.json with `solaris` ignored.
2. `govendor fetch -v github.com/lib/pq`

The fetched library won't build because `user_posix.go` was not added.

**Comment by kardianos** [comment]
I'm unable to reproduce with latest version.
The test at: https://github.com/kardianos/govendor/blob/master/context/tags_test.go#L68
should specifically test this case.

Could you ensure you have the latest master govendor and try again?

**Comment by johanbrandhorst** [comment]
Weird, can't reproduce now. Alright, that's good news! Sorry about the issue :).
