### ISSUE TITLE
Govendor fetch doesn't take "tree":true value when updating dependencies.

### ISSUE THREAD

**Issue by antoniomtz** [kardianos/govendor#324]
I have the following dependency:

{
   "origin": "enterprisegithub/account/project.git",
   "path": "enterprisegithub/account/project",
   "tree": true
}

when I want to update it: govendor fetch enterprisegithub/account/project 
it doesn't update subfolders, even though I have set "tree":true

I need to add the -tree parameter again in the command to update all subfolders as well:
govendor fetch -tree enterprisegithub/account/project 

Thanks.

**Comment by kardianos** [comment]
Can you try `govendor fetch enterprisegithub/account/project/^` ?

**Comment by antoniomtz** [comment]
It worked like that. 
Thanks.
