### ISSUE TITLE
Fetching from private github repos within docker container

### ISSUE THREAD

**Issue by khalliday7** [kardianos/govendor#326]
To get to the point, is there a way to configure govendor so that when it encounters a private repository, it provides a username and password? 

To my understanding, you can configure git to work with ssh instead of https, so that no username and password are required. Please correct me if I'm wrong, but this would not work within a docker container, because the container would not have access to your ssh keys. Just as the docker container would not be able to access your cached git username and password.

Currently, at the entrypoint to the docker container, I am manually installing my private repository (if not already in the image) by providing username and password through environment variables, and then git cloning the dependency directly into the vendor file. I then run govendor update +vendor (which I think is necessary because I manually copied the depedency), and the use govendor fetch out+ for the rest of the remote dependencies. But the process would be much cleaner if I just had to configure govendor so that it could handle both private and public repos.

**Comment by fahernandez** [comment]
In order to fetch private dependencies inside a container you will need to specify as github access token to be used inside the container as key, somenthing similar to:
```
docker run --rm -v "$PWD":/go/src/github.com/{user}/{project} -w /go/src/github.com/{user}/{project} {golang_container} sh -c "git config --global url.'https://<GITHUB_ACCESS_TOKEN>:x-oauth-basic@github.com/'.inst
eadOf 'https://github.com/' && go get . && govendor init && govendor add +external"
```
You can create your Access Token from https://github.com/settings/tokens/new

I hope that this can fix your problem, regards!

**Comment by Arnold1** [comment]
hi,
any idea why i still see the following error using your trick?
```
docker run --rm=true --name=$(CONTAINER_NAME).test $(VOLUMES) $(PORTS) --entrypoint=/go/src/github.com/blabla/test-price-engine/test-entrypoint.sh ${IMAGE_NAME} sh -c "git config --global url.'https://15366e174e58534233:x-oauth-basic@github.com/'.insteadOf 'https://github.com/'"
```

still get the error:
```
Successfully tagged byoa-price-engine:latest
docker run --rm=true --name=byoa-price-engine.test -v /Users/gstanje/intelligence/src/github.com/byoa-integration/byoa-price-engine:/go/src/github.com/blabla/byoa-price-engine -p 8083:8083 -p 6060:6060 --entrypoint=/go/src/github.com/blabla/byoa-price-engine/test-entrypoint.sh byoa-price-engine sh -c "git config --global url.'https://1566e174e585c11da80e2ea2cfb1c1cd3b9ed0d8:x-oauth-basic@github.com/'.insteadOf 'https://github.com/'"
go-bindata -pkg env -prefix ../ -o configData.go ../config/
# cd .; git clone https://github.com/blabla/intell-go-common /go/.cache/govendor/github.com/blabla/intell-go-common
Cloning into '/go/.cache/govendor/github.com/blabla/intell-go-common'...
fatal: could not read Username for 'https://github.com': No such device or address
Error: failed to create repo "https://github.com/blabla/intell-go-common" in "/go/.cache/govendor/github.com/blabla/intell-go-common" exit status 128
Failed to fetch package "github.com/blabla/intell-go-common/mempool"
github.com/kardianos/govendor/context.(*Context).Alter
	/go/src/github.com/kardianos/govendor/context/modify.go:712
github.com/kardianos/govendor/run.(*runner).Modify
	/go/src/github.com/kardianos/govendor/run/modify.go:152
github.com/kardianos/govendor/run.(*runner).run
	/go/src/github.com/kardianos/govendor/run/run.go:98
github.com/kardianos/govendor/run.Run
	/go/src/github.com/kardianos/govendor/run/run.go:44
main.main
	/go/src/github.com/kardianos/govendor/main.go:35
runtime.main
	/usr/local/go/src/runtime/proc.go:195
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337
```

**Comment by kobenauf** [comment]
Note in @fahernandez comment above there is no line break in the code.  Make sure you don't have `.inst` rather than `insteadOf`.
`git config url.'...'.insteadOf "https://github.com"`

**Comment by kobenauf** [comment]
This issue is a bit old now, but when you create the personal access token on github, choose "Full control of private repositories".
