### ISSUE TITLE
"govendor get" does not create $GOPATH/bin/pkgname like `go get` does

### ISSUE THREAD

**Issue by anthonyfok** [kardianos/govendor#330]
According to `govendor -h`:

            get      Like "go get" but copies dependencies into a "vendor" folder.

So, the expectation is that `govendor get` would, just like `go get`, download, compile and install packages and dependencies, with the difference that dependencies are copied into a "vendor" folder.

So, if `go get` ends up compiling and installing a new binary executable in $GOPATH/bin, then so should `govendor get`, except it doesn't, not unless the end user `cd` to somewhere deep enough inside the $GOPATH/src directory first, i.e. `govendor get`'s behavior is affected by the CWD in an unexpected way.

And, while `govendor get -h` mentions a `-v` verbose mode:

```
govendor get [options] (import-path)...
	Download package into GOPATH, put all dependencies into vendor folder.
	Options:
		-insecure    allow downloading over insecure connection
		-v           verbose mode
```

unfortunately, unlike `go get -v`, `govendor get -v` does not print any output whatsoever, precluding the end users to see what `govendor get` is doing in the background, and whether it succeeds or not.

### Background

After Hugo (the static website generator) adapted `govendor` as its vendoring solution, the installation instruction was changed from

    go get github.com/gohugoio/hugo

to

    go get github.com/kardianos/govendor
    govendor get github.com/gohugoio/hugo

which is just one extra command, and still looks nice and elegant, and it works for some users, but not for others, and it is becoming confusing.

### Steps to reproduce
```
    $ cd ~
    $ export GOPATH=/tmp/gopath
    $ export PATH=$PATH:$GOPATH/bin
    $ go get github.com/kardianos/govendor
    $ govendor get github.com/gohugoio/hugo
    $ ls -l $GOPATH/bin
    -rwxr-xr-x 1 john john 11162153 Jul  4 10:27 govendor
```

### Workaround: Trial 1
```
    $ cd $GOPATH/src
    $ govendor get github.com/gohugoio/hugo
    $ ls -l $GOPATH/bin
    -rwxr-xr-x 1 john john 11162153 Jul  4 10:27 govendor
```

Nope, `CWD = $GOPATH/src` doesn't work.

### Workaround: Trial 2
```
    $ cd $GOPATH/src/github.com
    $ govendor get github.com/gohugoio/hugo
    $ ls -l $GOPATH/bin
    -rwxr-xr-x 1 john john 11162153 Jul  4 10:27 govendor
    -rwxr-xr-x 1 john john 18659717 Jul  4 10:49 hugo
```

Cool, `CWD = $GOPATH/src/github.com` does work!

### Workaround: Trial 3
```
    $ rm -f $GOPATH/bin/hugo
    $ ls -l $GOPATH/bin
    -rwxr-xr-x 1 john john 11162153 Jul  4 10:27 govendor

    $ mkdir $GOPATH/src/something-random
    $ cd $GOPATH/src/something-random
    $ govendor get github.com/gohugoio/hugo
    $ ls -l $GOPATH/bin
    -rwxr-xr-x 1 john john 11162153 Jul  4 10:27 govendor
    -rwxr-xr-x 1 john john 18659717 Jul  4 10:49 hugo
```

Okay, now that is strange, `CWD = $GOPATH/src/something-random` works too!

Tested on Linux using the latest Debian sid (soon after the Debian 9 Stretch release) on amd64.

----

Dear Govendor developers, could you please shed some light on this issue?

I mean, while the Hugo developers, or other package developers using Govendor, could add a `cd` workaround like this:

    go get github.com/kardianos/govendor
    cd $GOPATH/src/github.com
    govendor get github.com/gohugoio/hugo

it doesn't look elegant any more, and still kind of confusing.

Is `govendor get` indeed the right command to use here?
If so, please let me know, and I would be more than happy to study the code and to submit a Pull Request so that `govendor get` would behave consistently regardless of CWD.

Many thanks!

**Comment by kardianos** [comment]
Thank you for the detailed description and problem statement. I don't have an immediate answer. I'll look into this.

**Comment by anthonyfok** [comment]
Thanks a million, Daniel!
