### ISSUE TITLE
Why govendor puts all sub packages to vendor.json?

### ISSUE THREAD

**Issue by spaiz** [kardianos/govendor#333]
Hi.
Say I'm using:

```
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
```

in my project. Why 

`govendor add +external`

generates vendor.js with lot of garbage like this,

                 {
			"checksumSHA1": "f7zg170Rm9Jh1QKLCpOD2dGvPTo=",
			"path": "github.com/aws/aws-sdk-go/aws",
			"revision": "69836214e899aa2562455259e32bd48a412ed036",
			"revisionTime": "2017-06-23T20:55:00Z"
		},
		{
			"checksumSHA1": "Y20DEtMtbfE9qTtmoi2NYV1x7aA=",
			"path": "github.com/aws/aws-sdk-go/aws/session",
			"revision": "69836214e899aa2562455259e32bd48a412ed036",
			"revisionTime": "2017-06-23T20:55:00Z"
		},
		{
			"checksumSHA1": "fEviiLbCHyTuedwpXTJSFNeu7FA=",
			"path": "github.com/aws/aws-sdk-go/service/s3",
			"revision": "69836214e899aa2562455259e32bd48a412ed036",
			"revisionTime": "2017-06-23T20:55:00Z"
		}

instead of inserting only the main package?
Thanks.

P.S.
For now, we may edit vendor.json manually and use:

`			"tree": true
`

flag. But maybe there is a way to generate vendor.js to include only top-level packages?

**Comment by kardianos** [comment]
govendor doesn't pay attention to "repo" only "package".
