### ISSUE TITLE
`govendor update` error - not a go package or not in GOPATH

### ISSUE THREAD

**Issue by cswarth** [kardianos/govendor#335]
I'm running into that horrible "not a go package or not in GOPATH" error message (#169) now and I cannot seem to get past it.

`govendor fetch` seems to do something useful but `govendor update` always fails.
```
$ govendor fetch -v  google.golang.org/grpc
Get version "google.golang.org/grpc"@v1.0.3
        Found exact version "v1.0.3"

$ govendor update -v  google.golang.org/grpc
Error: Package "google.golang.org/grpc" not a go package or not in GOPATH.
```
What is this error message suposed to mean?  "google.golang.org/grpc" is a Go package so the error message is misleading.

My goal is to update the vendored `grpc` package and the vendor.json file to the latest version of `grcp`.  Is there any way to do that from the govendor commandline?  Do I have to wipe out the vendor.json file and all the vendored packages and start from govendor init again?

**Comment by kardianos** [comment]
Does your environment have a GOPATH defined? What is the output of `go env`?

**Comment by cswarth** [comment]
Thanks for taking a look at this.  I posted a repo with what I hope is a reproducible test case, 
https://github.com/cswarth/govend-test

I included a shell script that sets GOPATH and runs `govendor` the way we have been running it internally.   

```
$ govendor --version
v1.0.8
```

**Comment by kbariotis** [comment]
I am experiencing the exact same thing on latest MacOS and fresh install of `go` and `govendor` (using homebrew).

Tried to export GOPATH manually and still the same thing.

**Comment by kaey** [comment]
govendor update copies package from your GOPATH into vendor dir. If package is not in your GOPATH, then there is nothing to copy.

**Comment by stuartluscombe** [comment]
I am getting this same error when trying to run `govendor get github.com/gohugoio/hugo`. I reached out to the maintainers of that repo and they requested I bring up the issue here.

Error:
```
stuart@stuart-HP-EliteBook-745-G2 ~/go/bin $ govendor get github.com/gohugoio/hugo
Error: Package "/home/stuart/go\n/src/github.com/gohugoio/hugo" not a go package or not in GOPATH.
```

```
stuart@stuart-HP-EliteBook-745-G2 ~/go/bin $ go env
GOARCH="amd64"
GOBIN="/home/stuart/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/stuart/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build347036260=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

Running `go get github.com/gohugoio/hugo` does pull down a number of packages into $GOPATH/src, but this is not the supported method for the application. I'm confused as to why there is a random \n in the error message.

**Comment by whitetower957** [comment]
I met the same question too, and it's can be solved?

**Comment by diofeher** [comment]
I had the same error, how can I solve this?

**Comment by danilrafiqi** [comment]
same error, how to solve ?
