### ISSUE TITLE
panic: Empty package path

### ISSUE THREAD

**Issue by cg831344** [kardianos/govendor#339]
1. govendor init
2. govendor list

The following appears:

goroutine 1 [running]:
github.com/kardianos/govendor/context.(*Context).setPackage(0xc0421a6000, 0xc042171800, 0x31, 0xc042171800, 0x0, 0xc042171800, 0x0, 0xc042008240, 0x31, 0x10002, ...)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/context/resolve.go:322 +0x7aa
github.com/kardianos/govendor/context.(*Context).addFileImports(0xc0421a6000, 0xc042171800, 0x39, 0xc042008240, 0x31, 0x30, 0x1, 0xc042171800)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/context/resolve.go:205 +0xf43
github.com/kardianos/govendor/context.(*Context).loadPackage.func1(0xc042171800, 0x39, 0x374000, 0xc0421d8300, 0x0, 0x0, 0x0, 0x39)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/context/resolve.go:55 +0x290
github.com/kardianos/govendor/internal/vfilepath.walk(0xc042171800, 0x39, 0x374000, 0xc0421d8300, 0xc042002c60, 0x0, 0x0)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:19 +0x88
github.com/kardianos/govendor/internal/vfilepath.walk(0xc04200ce40, 0x30, 0x374000, 0xc042010a20, 0xc042002c60, 0x0, 0x1)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x414
github.com/kardianos/govendor/internal/vfilepath.Walk(0xc04200ce40, 0x30, 0xc042002c60, 0x30, 0x0)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:82 +0xdc
github.com/kardianos/govendor/context.(*Context).loadPackage(0xc0421a6000, 0x0, 0x0)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/context/resolve.go:72 +0x180
github.com/kardianos/govendor/context.(*Context).Status(0xc0421a6000, 0xaf8a60, 0x4, 0x4, 0x0, 0x0)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/context/status.go:259 +0x4c
github.com/kardianos/govendor/run.(*runner).List(0xc042089e78, 0xafadc0, 0xc04205e008, 0xc04204c3f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/run/list.go:50 +0x367
github.com/kardianos/govendor/run.(*runner).run(0xc042089e78, 0xafadc0, 0xc04205e008, 0xc04204c3e0, 0x2, 0x2, 0xafa2c0, 0xc042089ee7, 0x0, 0x0, ...)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/run/run.go:85 +0xcc4
github.com/kardianos/govendor/run.Run(0xafadc0, 0xc04205e008, 0xc04204c3e0, 0x2, 0x2, 0xafa2c0, 0xc042089ee7, 0x902347, 0x12, 0xafbd80)
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/run/run.go:44 +0x94
main.main()
        C:/Users/Administrator/GoglandProjects/study/src/github.com/kardianos/govendor/main.go:35 +0xe8

**Comment by cg831344** [comment]
go=1.8.3

**Comment by bleleve** [comment]
Hello,

Same error for me. Sorry I am new to Golang, I will try to explain what happened as best as possible.

I have executed "govendor fetch gopkg.in/yaml.v2" and I got the following error: "panic: Empty package path". The cmd was run inside the src folder in my GOPATH and the vendor/vendor.json was created previously by "govendor init" without any error.

I have Go 1.8.3 too on Windows 10 (x64) with the last govendor.

```
D:\MyFolder\src>govendor add gopkg.in/yaml.v2
panic: Empty package path

goroutine 1 [running]:
github.com/kardianos/govendor/context.(*Context).setPackage(0xc042178a00, 0xc042169880, 0x2f, 0xc042169880, 0x0, 0xc042169880, 0x0, 0xc042177ec0, 0x2f, 0x10002, ...)
        D:/MyFolder/src/github.com/kardianos/govendor/context/resolve.go:322 +0x7aa
github.com/kardianos/govendor/context.(*Context).addFileImports(0xc042178a00, 0xc042169880, 0x36, 0xc042177ec0, 0x2f, 0x2e, 0x1, 0xc042169880)
        D:/MyFolder/src/github.com/kardianos/govendor/context/resolve.go:205 +0xf43
github.com/kardianos/govendor/context.(*Context).loadPackage.func1(0xc042169880, 0x36, 0x1160000, 0xc0421984e0, 0x0, 0x0, 0xc042003b80, 0x36)
        D:/MyFolder/src/github.com/kardianos/govendor/context/resolve.go:55 +0x290
github.com/kardianos/govendor/internal/vfilepath.walk(0xc042169880, 0x36, 0x1160000, 0xc0421984e0, 0xc042003b00, 0x0, 0x0)
        D:/MyFolder/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:19 +0x88
github.com/kardianos/govendor/internal/vfilepath.walk(0xc042196870, 0x2e, 0x1160000, 0xc0421982a0, 0xc042003b00, 0x0, 0x1)
        D:/MyFolder/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x414
github.com/kardianos/govendor/internal/vfilepath.Walk(0xc042196870, 0x2e, 0xc042003b00, 0x2e, 0x0)
        D:/MyFolder/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:82 +0xdc
github.com/kardianos/govendor/context.(*Context).loadPackage(0xc042178a00, 0xc0421965a0, 0xc042089890)
        D:/MyFolder/src/github.com/kardianos/govendor/context/resolve.go:72 +0x180
github.com/kardianos/govendor/context.(*Context).modify(0xc042178a00, 0xc0421753b0, 0xc04204c401, 0xc042089bad, 0x0, 0x3, 0xffffffffffffffff, 0x8)
        D:/MyFolder/src/github.com/kardianos/govendor/context/modify.go:232 +0xfc
github.com/kardianos/govendor/context.(*Context).ModifyImport(0xc042178a00, 0xc0421753b0, 0xc04205c001, 0xc042089bad, 0x0, 0x3, 0x0, 0x0)
        D:/MyFolder/src/github.com/kardianos/govendor/context/modify.go:183 +0x194
github.com/kardianos/govendor/run.(*runner).Modify(0xc042089e78, 0xafadc0, 0xc04205e008, 0xc04205c080, 0x1, 0x1, 0x1, 0xafa2c0, 0xc042089ee7, 0xc042002340, ...)
        D:/MyFolder/src/github.com/kardianos/govendor/run/modify.go:105 +0x61d
github.com/kardianos/govendor/run.(*runner).run(0xc042089e78, 0xafadc0, 0xc04205e008, 0xc04205c060, 0x3, 0x3, 0xafa2c0, 0xc042089ee7, 0x0, 0x0, ...)
        D:/MyFolder/src/github.com/kardianos/govendor/run/run.go:98 +0x41b
github.com/kardianos/govendor/run.Run(0xafadc0, 0xc04205e008, 0xc04205c060, 0x3, 0x3, 0xafa2c0, 0xc042089ee7, 0x902347, 0x12, 0xafbd80)
        D:/MyFolder/src/github.com/kardianos/govendor/run/run.go:44 +0x94
main.main()
        D:/MyFolder/src/github.com/kardianos/govendor/main.go:35 +0xe8
```

Best regards,
Benoît.

**Comment by kevinjulian** [comment]
i got same issue. how you deal with this? @cg831344

**Comment by cg831344** [comment]
@kevinjulian I change it,use go dep
