### ISSUE TITLE
make "govendor list" output easier to read and parse

### ISSUE THREAD

**Issue by kardianos** [kardianos/govendor#34]
@jacobsa mentioned that "govendor list" wasn't the easiest to pick apart with a sed one liner. While you shouldn't need to do that too often, it should be reasonable to do.

I have also noticed the syntax for vendored projects are a bit verbose. That should be cleaned up.

Maybe something like:
```
v <canonical-path>  (align with space) <"::" vendor path from project root>
v co2/pk2       ::vendor/co2/pk2
```

**Comment by jacobsa** [comment]
Seems sane. Alternatively, a flag that turns off the extra stuff and prints only the package names (perhaps with the one character status)?

**Comment by kardianos** [comment]
I have a flag already -v to list packages that import said dependency. I could only show the vendor path if the -v flag = true. Then normal output would be:
v <canonical-path>

**Comment by jacobsa** [comment]
Assuming you mean the output would be the following (your comment seems truncated):

    v co2/pk2

then I agree. This is actually what I would expect given the presence of the `-v` flag.

**Comment by kardianos** [comment]
If you wouldn't mind, checkout master and see if that is better.

**Comment by jacobsa** [comment]
Looks good to me, thanks!
