### ISSUE TITLE
why `govendor fetch` does not fetch all files? 

### ISSUE THREAD

**Issue by sgon00** [kardianos/govendor#340]
I want to install gorm so I did this:

```bash
$ govendor fetch github.com/jinzhu/gorm
```

But the files installed are:

```bash
$ ls
association.go      callback_query_preload.go  dialect.go           field.go               main.go          search.go
callback_create.go  callback_row_query.go      dialect_mysql.go     interface.go           model.go         test_all.sh
callback_delete.go  callback_save.go           dialect_postgres.go  join_table_handler.go  model_struct.go  utils.go
callback.go         callback_update.go         dialect_sqlite3.go   License                README.md        wercker.yml
callback_query.go   dialect_common.go          errors.go            logger.go              scope.go
```

There are many files missing so that this library does not work at all. 

The correct installed files should be:

```bash
~/go/src/github.com/jinzhu/gorm]$ ls
association.go             callback_update.go        errors.go              migration_test.go           scope_test.go
association_test.go        create_test.go            errors_test.go         model.go                    search.go
callback_create.go         customize_column_test.go  field.go               model_struct.go             search_test.go
callback_delete.go         delete_test.go            field_test.go          multi_primary_keys_test.go  test_all.sh
callback.go                dialect_common.go         interface.go           pointer_test.go             update_test.go
callback_query.go          dialect.go                join_table_handler.go  polymorphic_test.go         utils.go
callback_query_preload.go  dialect_mysql.go          join_table_test.go     preload_test.go             utils_test.go
callback_row_query.go      dialect_postgres.go       License                query_test.go               wercker.yml
callback_save.go           dialects                  logger.go              README.md
callbacks_test.go          dialect_sqlite3.go        main.go                scaner_test.go
callback_system_test.go    embedded_struct_test.go   main_test.go           scope.go
```

Is this a bug? or What I did wrong? 

PS: I don't want to use `govendor add +external` command to fix this problem. I just want to use `govendor fetch` command. Thanks.

**Comment by kaey** [comment]
Test files are ignored by default, you need to remove "test" from "ignore" in vendor.json.
As for subpackages, you can vendor whole tree with ```govendor fetch github.com/jinzhu/gorm/^```

**Comment by sgon00** [comment]
@kaey Thank you very much for your help. `govendor fetch github.com/jinzhu/gorm/^` does work very well. I think the doc and FAQ should state this clearly. The doc and FAQ only talk about using `/^` to include other resources such as C and HTML files, but it doesn't state that `/^` is also useful for getting sub-packages. To me, resource files are different from sub-package files.

**Comment by kaey** [comment]
Actually, Go has no notion of subpackages and I don't see any reason to vendor package you don't depend on.

**Comment by sgon00** [comment]
@kaey `github.com/jinzhu/gorm/dialects/` contains required driver packages which govendor doesn't fetch by default. so `/^` is required to make `gorm` work. With the words `I don't see any reason to vendor package you don't depend on.`, I don't quite understand what you mean. Do you mean all sub-packages are useless?

**Comment by kaey** [comment]
You still have to blank import a package to use it (```import _ github.com/jinzhu/gorm/dialects/mysql```).
And if you do that, ```govendor fetch +outside``` will correctly vendor it.

**Comment by sgon00** [comment]
@kaey thanks a lot for this tip. I am sorry that I still have three more questions:

(1) Is `govendor fetch +outside` the same as `govendor fetch +out`? _README.md_ uses `+outside` argument, but _FAQ.md_ uses `+out`.

(2) What is the recommended workflow of govendor? 

* I was using `govendor init`, `govendor fetch <package>` before. 
* After your first suggestion with `/^`,  I tried to use `govendor init`, `govendor fetch <package>/^`. 
* After your second suggestion, I am thinking to do `govendor init`, `vim main.go`, `govendor fetch +outside`. 

(3) This is not related to this github issue. 

* If I only install gorm and related dependency packages to the vendor directory by using govendor, and I use `go run main.go` in my project which uses gorm. every time I run `go run main.go`, it has to compile something by `cc1` compiler. Thus, it's very slow. Everytime I execute `go run main.go`, it will take about 40 seconds to complete. 
* If I install gorm and its dependencies globally without using govendor such as `go get -u github.com/jinzhu/gorm`, `go run main.go` will compile once only and all further execution will only take less than 1 second. I am not sure if my words make sense in English or not and if you understand what I mean. I am a golang newbie. I don't know what the cause is and how to fix this issue if I only want to use vendor packages instead of using `go get`. 

Thank you very much for your time and help.

**Comment by sgon00** [comment]
I workaround my third issue by executing `go build -i`. I am not sure if this is the correct way to fix it. And in the future if I upgrade vendor dependencies, do I have to re-run `go build -i` again?

**Comment by kaey** [comment]
>(1) Is govendor fetch +outside the same as govendor fetch +out? README.md uses +outside 
argument, but FAQ.md uses +out.

```govendor fetch +o``` also works.

>(2) What is the recommended workflow of govendor? I am thinking to do govendor init, vim main.go, govendor fetch +outside

this

>And in the future if I upgrade vendor dependencies, do I have to re-run go build -i again?

Yes.

**Comment by sgon00** [comment]
@kaey got it. thank you very much for your help. :)

**Comment by Kaijun** [comment]
@kaey i also faced the same issue. I know how it works, but, 
what's the best practice under the following circumstance while using govendor:

1. at the very beginning of my project, i decided to use the package: `gorm`
2. i haven't referenced any package/subpackage in my program yet.
3. i wanna use `govendor fetch` to pull the package into my `vendor` folder, not in my GOPATH

but now, using `govendor fetch` still pulls the partial repository, should use `govendor fetch xxx/^` instead?
if yes, how do i clean up the vendor packages which is not referenced after the development is done?

or should i actually fetch the package into my GOPATH at first and use `add` to copy it into the vendor folder?

**Comment by sgon00** [comment]
@Kaijun I think the above posts have already covered your question. You can simply create your `main.go` and `import` what packages you will use and then execute `govendor fetch +outside` which will fetch all dependencies that you will depend on.
