### ISSUE TITLE
Any tips for migrating Sirupsen>sirupsen?

### ISSUE THREAD

**Issue by therealplato** [kardianos/govendor#347]
I'm encountering issues due to some subfolders vendoring `github.com/Sirupsen/logrus` and others vendoring `github.com/sirupsen/logrus`.

I'm manually going through dozens of folders and running:
```
gofmt -w -r '"github.com/Sirupsen/logrus" -> "github.com/sirupsen/logrus"' *.go
rm -rf vendor/ && govendor init
govendor fetch +outside
```

this is obviously pretty slow. i don't trust my gopath to have up to date packages so I don't want to use govendor add. I tried `govendor remove github.com/Sirupsen/logrus` but the entry remains in the manifest.json file (and by default I assume it is not safe to manually edit a generated file.)

What is the correct workflow to replace a package with a differently-cased package?

**Comment by kaey** [comment]
Looks like Sirupsen changed his name to lowercase recently.
Best way is to ask library authors to change import paths in their repos.

I don't know what manifest.json are you talking about (govendor uses vendor.json), but after you update import paths with ```gofmt -r```, ```govendor remove +u``` should clean everything up.
