### ISSUE TITLE
Use default GOPATH when it's missing from the environment

### ISSUE THREAD

**Issue by ShanTulshi** [kardianos/govendor#349]
I'm new to Go, but in the event that `$GOPATH` is not set in the environment, should it use the default GOPATH instead? This could be done by just `exec`ing `go env GOPATH` instead of getting GOPATH from the environment.

**Comment by kardianos** [comment]
Yep, I didn't notice that instance of using GOPATH. Elsewhere I have switched to querying `go env`.
