### ISSUE TITLE
Add tests to vendoring only for specific packages

### ISSUE THREAD

**Issue by brunetto** [kardianos/govendor#359]
Hi, 
I'm sorry if it is trivial but I was not able to find any hint.
Is there a way to add tests only for specific packages in the vendor folder?
I can ignore the tests for all the packages with "ignore" in vendor.json file or, without it, all the tests for all the packages are added.

**Comment by kardianos** [comment]
Nope. There is no way to do a package specific ignore requirement.

**Comment by brunetto** [comment]
Ok, thanks... and is there a way to avoid having tests ignored in `vendor.json` after `govendor init`?

**Comment by kardianos** [comment]
You can always remove that after a govendor init. It is just what I consider a "sane default".

**Comment by brunetto** [comment]
Yeah it is a sane default that unfortunately does not apply to my employer default pipeline. I'm trying to find the best way to deal with it. Thanks a lot.
