### ISSUE TITLE
`govendor list` doesn't ignore dependencies of dependency tests, despite ignore tags

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#36]
I'm using govendor at 0d86ae9bf4b668294924306ec5dc3fe7d6d6b954.

[Here](https://gist.github.com/jacobsa/358306654373a7f0de33) is a gist for a small program that uses `golang.org/x/oauth2/google`. The latter package has a test that depends on `google.golang.org/appengine`, but the package itself does not.

When I use `govendor init` to set up a `vendor.json` file for my program, the file says to ignore tests, as expected:

    "ignore": "test",

However, `govendor list` still shows the test dependency:

    m google.golang.org/appengine
    m google.golang.org/appengine/urlfetch

I know this is not a real dependency of my code or any of its tests, because I used `go get -u -t ./...` to install all of the dependencies, and yet it is still missing.

To reproduce:

    # Download the code, then download its dependencies.
    git clone https://gist.github.com/358306654373a7f0de33.git $GOPATH/src/foo
    cd $GOPATH/src/foo
    go get -v -u -t ./...
    
    # Set up vendor.json, which says to ignore tests
    govendor init
    
    # List dependencies
    govendor list

**Comment by kardianos** [comment]
@jacobsa here is what I see on my system:
```
daniel@kink ~/s/test6> govendor list -v google.golang.org/appengine
m google.golang.org/appengine
  └── golang.org/x/oauth2/google

daniel@kink ~/s/g/x/o/google> pt google.golang.org/appengine
appengine_hook.go:
9:import "google.golang.org/appengine"

daniel@kink ~/s/g/x/o/google> cat appengine_hook.go 
// Copyright 2015 The oauth2 Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build appengine appenginevm

package google

import "google.golang.org/appengine"

func init() {
	appengineTokenFunc = appengine.AccessToken
}
```
From what I can tell, appengine is referenced outside of the test files.

**Comment by jacobsa** [comment]
Interesting. Of course `appengine_hook.go` is irrelevant for me, because I'm not running on App Engine. It's as if this were in a file labelled `+build plan9`; i.e. for a different OS or architecture. Does it make sense for govendor to ignore such files, or is that too special-casey?

**Comment by kardianos** [comment]
You could always specify in the "vendor.json" file:
```
"ignore": "test appengine",
```
This would ignore both test file and file with the appengine build tag.
...

My design for the vendor ignore is opt-out, designed to be the opposite of the build file directive which (when specified) is opt in. My rational for that is that typically you would want to be cross platform is applicable, but selectively opt out of tags, tests, architectures as desired. It isn't perfect, but it avoids a lot of complexity while still getting what most people (I think) would want. Comments welcome on the design.

**Comment by jacobsa** [comment]
Viewed that way it makes sense; I'm happy with that philosophy. Maybe it's worth sticking something to that effect in the readme?
