### ISSUE TITLE
go version issue

### ISSUE THREAD

**Issue by developer-guy** [kardianos/govendor#366]
Hi,

I have golang in version go1.9.1 when i try this command 

> go get -u github.com/kardianos/govendor

i am getting the following error : 

 github.com/kardianos/govendor/vendor/golang.org/x/sys/unix
flag provided but not defined: -goversion
usage: compile [options] file.go...
  -%	debug non-static initializers
  -+	compiling runtime
  -B	disable bounds checking
  -D path
    	set relative path for local imports
  -E	debug symbol export
  -I directory
    	add directory to import search path
  -K	debug missing line numbers
  -N	disable optimizations
  -S	print assembly listing
  -V	print compiler version
  -W	debug parse tree after type checking
  -asmhdr file
    	write assembly header to file
  -bench file
    	append benchmark times to file
  -buildid id
    	record id as the build id in the export metadata
.....

Why am i getting this error ?

**Comment by kardianos** [comment]
You probably have a cached old copy of something.
try: `go get -u -a github.com/kardianos/govendor`
maybe
