### ISSUE TITLE
what is "vt" status? what is the "t"?

### ISSUE THREAD

**Issue by sgon00** [kardianos/govendor#367]
First, I have to say "govendor" README.md/FAQ etc.. are really hard to understand for a newbie like me. I tried to find a tutorial or a book about govendor by google but failed. Whatever....

When I do `govendor list`, I see many `vt` status. I tried very hard to read everything about govendor in github and google, but I failed to find a single place where it mentions what the status `"t"` is. Thank you very much for your help. 

PS: Could anyone please write a good documentation for govender? for example, I have no idea what the difference is between `govendor install +local` and `go install`.

**Comment by kardianos** [comment]
`t` stands for "tree". It says the package is vendored (copied locally) and not just that package, but all folders and files under it too.
Normal vendoring in govendor just grabs a single package.

**Comment by sgon00** [comment]
@kardianos Thank you very much for your quick reply. Just two more newbie questions:

(1) What is the best practice to vendor the required sub-package?
 
For the code:

```go
import (
    "github.com/jinzhu/gorm"
    _ "github.com/jinzhu/gorm/dialects/sqlite"
)
```

`govendor fetch github.com/jinzhu/gorm` will not work. It requires the sub-folder `dialects/sqlite`.

(a) `govendor fetch github.com/jinzhu/gorm/^` works, but some people say this is not good to do because it fetches more than I need. I am not sure if this is the best practice.
(b) `govendor fetch +outside` works only if I have the import codes. Is this the best practice? What if I don't write any codes yet and want to fetch what I need before writing any codes?
(c) any more better options? 

(2) Can you please explain what the difference is between `govendor install +local` and `go install`?

Thank you very much.
