### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [kardianos/govendor#369]
Based on https://github.com/kardianos/govendor/releases and https://github.com/kardianos/govendor/releases/latest I cannot tell if 1.0.8 or 1.0.9 is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by kardianos** [comment]
1.0.9
I need to fix up the GitHub release auth for builds it looks like.

**Comment by ilovezfs** [comment]
@kardianos thanks. Voilà https://github.com/Homebrew/homebrew-core/pull/19972
