### ISSUE TITLE
Telling govendor to ignore dependencies' tests causes it to ignore my tests, too

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#37]
In issue #24 I complained about `govendor add` pulling in the tests of the packages on which I depend. The solution in 0d86ae9bf4b668294924306ec5dc3fe7d6d6b954 was to add the `ignore` field to `vendor.json`, containing a list of tag to ignore.

I had assumed that this caused `govendor list`, `govendor add`, etc. to ignore those tags in the dependencies, but it also ignores them for my package. So, for example, the dependencies of *my* tests are also not pulled in. This isn't what I want—I'm looking for a hermetic build of my tests, too.

Assume I have a package named `foo`, with a sub-package named `foo/bar`. When I run `govendor add` from within the directory `$GOPATH/foo`, I want it to pull in all of the dependencies of `foo`, of `foo/bar`, and of each of their tests. I don't want it to pull in the tests of any of those dependencies.

Is there any way to achieve the above?

**Comment by kardianos** [comment]
Oh dear. Yes, I failed to correctly apply this only to vendor files. Thank you for pointing it out. I'll work on a fix.
