### ISSUE TITLE
vendor in vendor, different version package problem

### ISSUE THREAD

**Issue by rudyfly** [kardianos/govendor#378]
Such as my project import A and B package, package A is old, its version is v1.0, package B is new, its version is v2.0. But package A alse import B, because package A is old, so it imports more older package B, B's version is v1.0, so it causes build error, how to solve it??
```
-- Myproject
    |-- vendor
        |-- A
            |-- vendor
                |-- B  // version is v1.0
            |-- a.go // imports and uses B, but version is v1.0
        |-- B  // version is 2.0
    |-- my.go  //import A, version is v1.0, also import B version is v2.0
```

**Comment by kaedys** [comment]
This isn't really a govendor problem.  This is a fundamental problem in software engineering in general.  The solution is generally to update package A, or clone it and update it yourself if no newer version is available.  

https://en.wikipedia.org/wiki/Dependency_hell
