### ISSUE TITLE
`govendor remove` requires me to first download the package to be removed

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#38]
I have a repo with `github.com/jacobsa/gcloud/gcs/gcstesting` vendored. I don't actually need this dependency, so I want to remove it. But `govendor remove` refuses to do so until I download it to `$GOPATH`, just for the sake of deleting it locally:

```
% govendor remove github.com/jacobsa/gcloud/gcs/gcstesting
Error: Package "github.com/jacobsa/gcloud/gcs/gcstesting" not a go package or not in GOPATH.

% go get github.com/jacobsa/gcloud/gcs/gcstesting
% govendor remove github.com/jacobsa/gcloud/gcs/gcstesting
```

**Comment by kardianos** [comment]
I need to add a test for this to make sure I don't break this again. Thanks for raising the issue.
