### ISSUE TITLE
can't install govendor on windows

### ISSUE THREAD

**Issue by charlietianx** [kardianos/govendor#382]
I have run "go get -u github.com/kardianos/govendor" and execute "go install".The govendor.exe is in the directory "D:\mygo\bin".But when I run "govendor",it says the command doesn't exist.Why?

my paths:

**C:\Users\Administrator>echo %GOPATH%**
D:\mygo

**C:\Users\Administrator>echo %PATH%**
$GOPATH\bin;$GOPATH;D:\curl-7.57.0\src;C:\Program Files\Git\bin;C:\ProgramData\O
racle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\w
indows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Lenovo\Fingerprint Mana
ger Pro\;C:\Program Files\OpenVPN\bin;C:\Program Files\Git\cmd;D:\Go\bin

The error msg:
**C:\Users\Administrator>govendor**
'govendor' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by wuxiaoxiaoshen** [comment]
You need to set $GOPATH/bin   which is D:\mygo\bin into your path on windows。

**Comment by charlietianx** [comment]
Thank you. my setting is wrong.It should be %GOPATH% on win, not $GOPATH. @wuxiaoxiaoshen
