### ISSUE TITLE
go list +unused - add tag to specify target OS

### ISSUE THREAD

**Issue by krasi-georgiev** [kardianos/govendor#389]
running `govendor -u` on 
https://github.com/prometheus/prometheus 
shows  `golang.org/x/sys/windows/registry` as unused which is a false positive since this is used in
`vendor/golang.org/x/sys/windows/svc/eventlog/install.go`

I guess the problem is that I am running this on linux and this file is only build-able on windows (`// +build windows`).

I tried  `GOOS=windows govendor list +unused` , but that didn't change the output.

Would it make sense to add another flag to specify supported OS so that only shows unused packages after including dependencies for all supported OS-es ?

**Comment by kaey** [comment]
```
[kaey@kwn prometheus]$ govendor list +u
 vu github.com/dgryski/go-bits
 vu golang.org/x/sys/windows
 vu golang.org/x/sys/windows/registry
 vu golang.org/x/sys/windows/svc/eventlog
```

Doesn't look like it's imported anywhere, same goes for go-bits.
```
[kaey@kwn prometheus]$ grep -nr golang.org/x/sys/windows *
vendor/golang.org/x/sys/windows/syscall.go:22:package windows // import "golang.org/x/sys/windows"
vendor/golang.org/x/sys/windows/svc/eventlog/install.go:12:     "golang.org/x/sys/windows"
vendor/golang.org/x/sys/windows/svc/eventlog/install.go:13:     "golang.org/x/sys/windows/registry"
vendor/golang.org/x/sys/windows/svc/eventlog/log.go:15: "golang.org/x/sys/windows"
vendor/golang.org/x/sys/windows/registry/zsyscall_windows.go:6: "golang.org/x/sys/windows"
vendor/vendor.json:974:                 "path": "golang.org/x/sys/windows",
vendor/vendor.json:980:                 "path": "golang.org/x/sys/windows/registry",
vendor/vendor.json:986:                 "path": "golang.org/x/sys/windows/svc/eventlog",
```

Also they should add appengine to ignore list to hide those missing packages, unless the support appengine of course.
```
[kaey@kwn prometheus]$ govendor list +m
  m appengine
  m appengine_internal
  m appengine_internal/base
  m github.com/gophercloud/gophercloud/openstack/identity/v2
  m github.com/gophercloud/gophercloud/openstack/identity/v3
```

gophercloud imports are also a mistake which can be fixed by running
```
govendor remove github.com/gophercloud/gophercloud/openstack/identity/v2
govendor remove github.com/gophercloud/gophercloud/openstack/identity/v3
```

**Comment by krasi-georgiev** [comment]
as an example
`golang.org/x/sys/windows/registry`
is used in
`vendor/golang.org/x/sys/windows/svc/eventlog/install.go`

**Comment by kaey** [comment]
golang.org/x/sys/windows/svc/eventlog is not imported by any main package and thus considered unused.

**Comment by krasi-georgiev** [comment]
What about
`github.com/sasha-s/go-deadlock`
this is only used in
`vendor/github.com/cockroachdb/cockroach/pkg/util/syncutil/mutex_deadlock.go`
but doesn't show in `govendor list +missing`

I would assume that anything added at vendoring stage shouldn't  be considered `unused` when listing dependandcies.

**Comment by krasi-georgiev** [comment]
@kaey ping

**Comment by krasi-georgiev** [comment]
bump.

**Comment by kardianos** [comment]
I'm not seeing a problem with govendor:
```
daniel@conk ~/s/g/p/prometheus> govendor list -v github.com/sasha-s/go-deadlock
 v  github.com/sasha-s/go-deadlock ::/vendor/github.com/sasha-s/go-deadlock    
    └──  v  github.com/prometheus/prometheus/vendor/github.com/cockroachdb/cockroach/pkg/util/syncutil
daniel@conk ~/s/g/p/prometheus> govendor list -v github.com/cockroachdb/cockroach/pkg/util/syncutil
 v  github.com/cockroachdb/cockroach/pkg/util/syncutil ::/vendor/github.com/cockroachdb/cockroach/pkg/util/syncutil    
    └──  v  github.com/prometheus/prometheus/vendor/github.com/cockroachdb/cockroach/pkg/util/protoutil
daniel@conk ~/s/g/p/prometheus> govendor list -v github.com/cockroachdb/cockroach/pkg/util/protoutil
 v  github.com/cockroachdb/cockroach/pkg/util/protoutil ::/vendor/github.com/cockroachdb/cockroach/pkg/util/protoutil    
    └──  l  github.com/prometheus/prometheus/web/api/v2
```

**Comment by krasi-georgiev** [comment]
yep you are right , not sure where I saw that.
