### ISSUE TITLE
Vendor file at "vendor" not found

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#39]
Attempting to remove and re-add all vendored dependencies at GoogleCloudPlatform/gcsfuse@e46ae9b (in order to pick up govendor's new support for ignoring tests) causes govendor to delete the `vendor/` directory and confuse itself:

```
% govendor remove +u
% govendor remove +v
% govendor add +e
Error: Vendor file at "vendor" not found.

GO15VENDOREXPERIMENT="1"
It is possible this project requires changing the above env var
or the project is not initialized.
```

I suppose either `govendor remove` should not delete the directory, or `govendor add` should not require it to be present.

**Comment by steelx** [comment]
type this `govendor init` then try rest of the cmd's
