### ISSUE TITLE
Govendor retrieving original repo instead of the forked one

### ISSUE THREAD

**Issue by mamhaidly** [kardianos/govendor#402]
I am trying to add a dependency to a forked repo to my heroku app. The original repo is github.com/fullsailor/pkcs7 and the forked repo is github.com/groob/pkcs7. Govendor is retrieving the original repo.
I tried using the ^ and :: operators (exactly as mentioned in the ReadMe file) and it is not working.

This issue is exactly as this one (https://github.com/kardianos/govendor/issues/147)

**Comment by alexseedkou** [comment]
So I solved the problem. The way I solved my issue is to delete the corresponding dependency in $GOPATH/.cache/govendor/{your dependency}. After this I run the the fetch and it works.

**Comment by mamhaidly** [comment]
I migrated to dep, it is the official experiment for a Golang dependency manager. It is supported by heroku. 
I will close the issue since you got a fix @alexseedkou
