### ISSUE TITLE
[question] how to install all dependencies?

### ISSUE THREAD

**Issue by ozbillwang** [kardianos/govendor#419]
So I can `govendor fetch <package>` for each dependencie, but how to install all dependencies? Do I have to fetch them one by one?

Currently I run below script to do the job
```
govendor list -no-status |grep -v <my own package name> |while read line
do
  govendor fetch $line
done

govendor build -o <my own package name> .
```

Any simpler way that I can run `govendor fetch` to get all dependencies? such as:

```
govendor fetch +all

or

govendor fetch +v

```

**Comment by kaey** [comment]
```govendor fetch +m``` or ```govendor fetch +o```
See https://github.com/kardianos/govendor#status

**Comment by ozbillwang** [comment]
Thanks a lot @kaey

**Comment by sgehrman** [comment]
Been searching for this, why isn't this clearly in the docs?
