### ISSUE TITLE
binary size is different 

### ISSUE THREAD

**Issue by ozbillwang** [kardianos/govendor#420]
Anyone found that when run with `go get ./...` and `govendor fetch <package>`, the final generated  binaries are different size?

Why?

**Comment by kardianos** [comment]
They may build from different versions, resulting in different sizes.

**Comment by ozbillwang** [comment]
I build in same docker golang:apline image.

**Comment by kardianos** [comment]
Different versions of the package dependencies. Also, some packages will live in /vendor/ while the get version won't. This will result in different debugging symbol paths to be stored I think.
