### ISSUE TITLE
Update vendor for AIX support

### ISSUE THREAD

**Issue by Helflym** [kardianos/govendor#427]
Hi, 

Is it possible to update **golang.org/x/sys/unix** and **Bowery/prompt** under vendor in order to allow AIX support ? It seems to be enough. All tests are passing locally after that. 

It don't think making a PR just for that is relevant. Tell me if you want one anyway. 

Thanks in advance. 

<del>**Edit:** I've forgotten that I'd manually updated **Bowery/prompt** because my PR isn't yet accepted... So you can update golang.org/x/sys/unix but Bowery/prompt will need to be updated once my https://github.com/Bowery/prompt/pull/21 is accepted. I'll warn you when this is possible. Sorry about that delay. </del>

**Edit2:** PR in Bowery/prompt has been accepted. Therefore, everything can be updated.

**Comment by kaey** [comment]
Send a PR, it will be faster this way.
