### ISSUE TITLE
Error: CreateFile src: The system cannot find the file specified？

### ISSUE THREAD

**Issue by Aruforce** [kardianos/govendor#429]
![govendor ](https://user-images.githubusercontent.com/24619012/56802567-f778b200-6852-11e9-988c-89097d59384e.png)

is there any thing  with config? or use?

**Comment by Aruforce** [comment]
I follow FAQ ,but could not fix it ?

**Comment by kardianos** [comment]
```
cd C:\GoWork\src
mkdir myproject
cd myproject
govendor init
```

That being said, if you are starting a new project, use go modules.

**Comment by Aruforce** [comment]
@kardianos  it seems that on windows \ will be transt to \\... when using git bash instead of cmd or powershell..try to debug..but ...did not find where is wrong.... sad... i will follow your advice for gou module...

**Comment by miyazawatomoka** [comment]
I think it is  a bug in windows...
