### ISSUE TITLE
`govendor update` no longer ignoring test files

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#43]
I'm using govendor at 0a72ef19c20f33601809f0b99cb47e12a060385d.

Despite [my vendor.json file](https://github.com/GoogleCloudPlatform/gcsfuse/blob/dc6b7c1d5d9b9aab6bc9bb601d2308c2b10dceaa/vendor.json) saying to ignore the tag `test`, `govendor update` is still pulling in test files for me. Is it possible this has regressed with recent changes?

To reproduce, grab the latest version of jacobsa/gcloud:

    go get -u -v github.com/jacobsa/gcloud/gcs

Then check out googlecloudplatform/gcsfuse@dc6b7c1d5d9b9aab6bc9bb601d2308c2b10dceaa and attempt to update it:

```
% govendor update github.com/jacobsa/gcloud/gcs
% git status
HEAD detached at dc6b7c1
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   vendor.json
        modified:   vendor/github.com/jacobsa/gcloud/gcs/compose_objects.go
        modified:   vendor/github.com/jacobsa/gcloud/gcs/requests.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        vendor/github.com/jacobsa/gcloud/gcs/conn_test.go
        vendor/github.com/jacobsa/gcloud/gcs/integration_test.go

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by kardianos** [comment]
Confirmed. I can reproduce with a small update to a unit test. I think the regression happened when I updated it to not work on local files.

**Comment by kardianos** [comment]
Ha ha! Ok, the reason it is failing is because I'm ignoring files on copy (opt-out) rather the list file to copy (opt-in). When it lists files for packages that are already vendored the files to ignore are not present (it is looking at the vendor directory) so it doesn't opt-out of the test files for the copy. Let me think about the fix...
