### ISSUE TITLE
govendor fetch +m not woring for xxhash

### ISSUE THREAD

**Issue by bryceyang** [kardianos/govendor#437]
<img width="459" alt="Screen Shot 2019-10-25 at 11 23 23 PM" src="https://user-images.githubusercontent.com/9302617/67583567-71e0ab00-f77e-11e9-9790-f2974ab6c3c5.png">

`govendor list` reminds me that the [xxhash](https://github.com/cespare/xxhash) package was missing in my vendor dir. 
So I simply typed `govendor fetch +m`. The command successfully executed with no popped error. But when I use `govendor list`, the package is still marked as missing.

Why does this happen? Please tell me what should I do.

**Comment by kaey** [comment]
/vX deps are not supported by govendor and there are no plans to fix it.
Your best bet is to switch to modules.

**Comment by bryceyang** [comment]
Got it. Thanks.
