### ISSUE TITLE
design: address handling remote packages

### ISSUE THREAD

**Issue by kardianos** [kardianos/govendor#44]
This issue is to track a design that will:
 1. Update the vendor folder based on the content of vendor.json #30 
 2. Fetch missing packages recursively #33 
 3. Fetch a full repo into GOPATH at the revision specified in vendor.json #35 
 4. Update or add a package from a remote path and version.

**Comment by kardianos** [comment]
The CLI can support (2) and (4) by adding a "-u" flag to the "update" and "add" commands. New flag in the context for AddRemote and UpdateRemote.

(4) will also require supporting reading import paths to the add/update command like: "my/import/path@abcd0123" or "my/import/...@v12345".

(1) will probably use AddUpdateRemote, filling in the revision in for each package.

**Comment by kardianos** [comment]
Current thinking is to add one primary command: `govendor fetch [-u]`
And one helper command: `govendor get [-u]`
And add a new meta status called `+dependency = +ext +ven +m`

 * `fetch` will be used to get packages that are not in vendor folder currently, like a network add command.
 * `fetch -u` will be used to get or update packages into the vendor folder, like a network add/update command.
 * `get [-u]` will first run `go get [-u]` (or equiv) then run `govendor fetch` (no -u). This allows a new project to be fetched remotely and the vendor folder populated. Remote project must already have a vendor folder.

**Comment by kardianos** [comment]
In addition to the above, path input parameters will be adjusted so that if they will be split on the first "@" rune. To the right of the "@" will be passed into the vcs fetch command to get a specific version. To the left of the "@" will be the path.
`path@version`

**Comment by kardianos** [comment]
Feedback from Peter Bourgon, might want to hold off on `govendor get`. Confusing with fetch, other commands require a workspace to already exist.

**Comment by kardianos** [comment]
Chris Hines and Robert Melton describe a hybrid approach. 
Chris: Copy third party code into project, clone at revision for internal related projects.
Robert: Put third party unmodified code into vendor dir, put modified and own code into project dir.

**Comment by kardianos** [comment]
Idea: add a package field called "track": "branch-name".
Then `govendor fetch -u mypkg` will update to the latest under the "track" branch.

**Comment by FrenchBen** [comment]
Not sure if this is the right place, but it would be nice if the recursion was smart enough to prevent this error:
`govendor add +e`
`Error: Package "github.com/some/app/vendor/github.com/some/package" already in vendor.

I may be using the wrong command, but if we look at something like `npm install` it checks the existing packages and adds what's missing

**Comment by kardianos** [comment]
@FrenchBen: Internally add and update are (almost) the exact same code path. I just have additional checks for add. That error shouldn't happen when adding external packages. Can send the steps to reproduce that from `add +external`?

I don't want to use the "install" sub-command, but would be fine with the idea to add or update command. Any idea for a word to use? Maybe "merge" or "latest" or ....?

**Comment by kardianos** [comment]
@FrenchBen I could also see combining update into add, so there is only "update", then if you really want to just add, then you could use a flag.

**Comment by FrenchBen** [comment]
I think combining `update` and `add` would be the cleanest.
How to reproduce:
```
$ govendor list +e
 e github.com/some/package-1
 e github.com/some/package-2
 e github.com/some/package-3
$ govendor add github.com/some/package-1
$ govendor list +e
 e github.com/some/package-1
 e github.com/some/package-2
 e github.com/some/package-3
$ govendor add +e
Error: Package "github.com/some/app/vendor/github.com/some/package-1" already in vendor.
```

**Comment by kardianos** [comment]
This will be addressed with the fetch and sync sub-commands. See: https://github.com/kardianos/govendor/blob/master/DESIGN.md

Feedback welcome.

**Comment by FrenchBen** [comment]
:+1:

**Comment by kardianos** [comment]
Now in master. Fetch has a few TODOs with resolving conflicts.

**Comment by FrenchBen** [comment]
![woohoo](https://cloud.githubusercontent.com/assets/3965324/13830323/1f9d4c9a-eb89-11e5-9ae9-18f99e09a6f0.jpeg)
