### ISSUE TITLE
Fails to remove import comment if go file has no imports.

### ISSUE THREAD

**Issue by vishr** [kardianos/govendor#45]
Getting error while trying to add vendor code using the command

`govendor add +ext github.com/garyburd/redigo/redis`

> code in directory .../foo/internal/github.com/garyburd/redigo/redis expects import "github.com/garyburd/redigo/redis"

Sample code

```go
package main

import "github.com/garyburd/redigo/redis"
import "fmt"

func main() {
    p := redis.Pool{}
    fmt.Printf("%v", p.Wait)
}
```

**Comment by kardianos** [comment]
I'm going to need more information to reproduce. When I tested it appeared
to work correctly. Do you have "GO15VENDOREXPERIMENT=1"? Is this in a
larger project?

-Daniel

**Comment by kardianos** [comment]
What revision are you using of govendor?

**Comment by vishr** [comment]
The sample code provided above is the only code where I tested it. I am using the latest govendor tool. Did you try to run or build the example? That's when I get the error.

**Comment by kardianos** [comment]
govendor is failing to scrub the import comment. Thank you for the report. I'll look into and provide a fix soon.

**Comment by vishr** [comment]
It works, thank you.
