### ISSUE TITLE
feature: add "check status" and "check diff" sub commands.

### ISSUE THREAD

**Issue by cep21** [kardianos/govendor#48]
I'm worried about being unable to verify that the code vendored inside /vendor/... is the exact code referenced by the vendor-spec file.  Is there a way to verify this?  Some kind of "govendor check" command?

**Comment by kardianos** [comment]
@cep21 Maybe... govendor can omit files based on tags and test status, so a direct compare might give false positives. The biggest advantage for a command like this for me is to compare it to a different source or revision, especially to check for local changes or remote changes. Maybe: `govendor check status [+status] [import paths]` and `govendor check diff [+status] [import paths]` . 

There might be ramifications with the remote command design too.

Thoughts?

**Comment by cep21** [comment]
That sounds reasonable.  The "omit files based on tags and test status" part should still be reverifyable since that ignored information is stored in the vendor spec, right?

**Comment by kardianos** [comment]
@cep21 Correct. The tags that are ignored is stored in the vendor-spec.

**Comment by kardianos** [comment]
This will be addressed in the upcoming changes. See: https://github.com/kardianos/govendor/blob/master/DESIGN.md

Feedback welcome.

**Comment by jzila** [comment]
@kardianos that `DESIGN.md` file is a dead link. I'm curious as to how vendored code can be verified.

**Comment by kardianos** [comment]
https://github.com/kardianos/govendor/blob/fetch/doc/design.md

**Comment by jzila** [comment]
@kardianos great, thanks!

**Comment by kardianos** [comment]
vendor checksum with sub-commands `status` and `sync` in master now.
