### ISSUE TITLE
govendor migrate doesn't work

### ISSUE THREAD

**Issue by harshavardhana** [kardianos/govendor#51]
```
$ govendor migrate
Error: open /Users/harsha/mygo/src/github.com/minio/minio/Godeps/Godeps.json: no such file or directory
```

We do not use Godeps instead we use Golang's standard GO15VENDOREXPERIMENT=1 

```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/harsha/mygo"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

```
$ go version
go version go1.5.1 darwin/amd64
```

**Comment by kardianos** [comment]
If you're using Godeps, last time I looked, it would always would use Godeps/Godeps.json.

At what revision of minio were you using this on? What revision of Godeps do you use?

**Comment by harshavardhana** [comment]
> At what revision of minio were you using this on? What revision of Godeps do you use?

We do not use Godeps, we just use GO15VENDOREXPERIMENT=1 and use govendor to vendorize the project.

**Comment by kardianos** [comment]
oh!
That would explain what I was seeing. Let me take a look; probably a bug, one sec.

**Comment by kardianos** [comment]
Hmmm, Could you ensure you have the latest version of "govendor"?
```
go get -u github.com/kardianos/govendor
```
Then in your repo root, run "govendor migrate", it appeared to work for me, using latest.

**Comment by harshavardhana** [comment]
> Then in your repo root, run "govendor migrate", it appeared to work for me, using latest.

It worked!
