### ISSUE TITLE
feature: add quiet flag to suppress the first column of output

### ISSUE THREAD

**Issue by jmunson** [kardianos/govendor#52]
When using a vendor/ directory, any go tool that uses ./... will run against all vendored code.  I wish this would change upstream, but for now I've worked around it by using govendor list.

Unfortunately to use it in places I would otherwise use ./..., I have to strip the first column of output.

So for example if I wanted to run gometalinter against all local code, I use:
```gometalinter $(govendor list +program +local |cut -f2 -d" ")```

This works nicely, but it would be nice to do something like
```gometalinter $(govendor list -q +program +local)```

It's not a particularly vital option -- piping to cut isnt a huge deal, but I doubt I'm the only one trying to use govendor like this so I think it would be nice to have as an option.

**Comment by kardianos** [comment]
Sounds reasonable.

**Comment by pquerna** [comment]
+1, would be helpful.  using some awk right now in a similar fashion to @jmunson 's examples

**Comment by kardianos** [comment]
Proposing list sub-command "-no-status" flag name. Opinions?
