### ISSUE TITLE
Allow configurable destination directory

### ISSUE THREAD

**Issue by captncraig** [kardianos/govendor#53]
One problem I have is that a lot of tools will traverse into the `internal` directory if I do for example `go vet ./...`

It causes a lot of false positives and things like that when I have a lot of dependencies. If I put them into an underscore directory like `_third_party`, then it does not have this problem. Could we add an option to make the destination directory configurable?

**Comment by kardianos** [comment]
Not a bad request. However the direction I see vendoring going right now is to use the "vendor" directory with what is now the "GO15VENDOREXPERIMENT" flag. I know it isn't even the default, but the plan is to turn it on by default in go1.6.

**Comment by kardianos** [comment]
To follow up, is there a reason not to transition to the "vendor" folder experiment? The actual code change to add a parameter is tiny. 
 * What are your immediate needs?
 * What is your long range plan?

**Comment by captncraig** [comment]
I do plan to move to vendor, but not until it is the default bahaviour. I suppose at that time I will need to confront the problem of vendored code being included with vet and such anyway, until I find a good way to exclude those packages. I'm sure I can come up with a fancy bash incantation to invoke vet on only my code or something like that. 

If this feature was implemented, I would certainly use it, but if you chose not to, I would also understand.

**Comment by kardianos** [comment]
I could see allow setting an environment variable to set the directory
location. The change would be so small, it would probably be worth it.
Would that work for you?

**Comment by kardianos** [comment]
I'm open to other ideas as well.

**Comment by captncraig** [comment]
That sounds good to me.
