### ISSUE TITLE
rewrite: Check and fix import paths for dependencies already vendored

### ISSUE THREAD

**Issue by ansel1** [kardianos/govendor#56]
Say I've vendor a dependency with import re-writing.

Then another developer comes along and adds an import statement to another source file for the same package, but doesn't refer to the vendored copy.  Would be great if `govender add +e` fixed these un-prefixed import statements.

They happen quite frequently in our environment, as our IDE tries to help with import statements, but doesn't prioritize the vendored packages.

**Comment by kardianos** [comment]
This is a good idea.

I am trying to move code to using the "vendor" folder completely, so if this is an easy fix, it might be done, but for the most part I want to focus effort on the vendor folder, not import path rewrites.

**Comment by ansel1** [comment]
that's reasonable.  Do one thing well.

**Comment by kardianos** [comment]
govendor on the default branch now only supports the vendor folder. A new branch called "rewrite" supports import path rewrites.
