### ISSUE TITLE
govendor remove +all is very dangerous

### ISSUE THREAD

**Issue by ansel1** [kardianos/govendor#57]
I was expecting this to just unvendor those packages listed in vendor.json, but it instead deleted all the files in my project package (even the non-.go files), and a number of packages where either half-removed or entirely removed from my $GOPATH.

I understand the command I probably should have run is `govendor remove +v`, so I'm not sure if remove +all is even semantically meaningful, but it definitely shouldn't have done what it did.

**Comment by kardianos** [comment]
I kinda chuckled when I read this title and thought, wow, that would be bad...

So I agree with you that some of the status should only be used with the "list" sub-command. The "add" and "remove" should only act on some of them.

**Comment by ansel1** [comment]
`remove` can also be very dangerous when specifying specific packages.  I was in a sub-package of a project.  I did `gevendor remove github.com/jinzhu/gorm`.  That removed the gorm from the vendor folder.  Run `gevendor remove github.com/jinzhu/gorm` again.  That removes gorm from my $GOPATH.

Seems like there should be circuit breaker that ensures that under no circumstances should govendor be deleting things outside of the vendor folder.

**Comment by kardianos** [comment]
Agreed on all counts. govendor has such a breaker for rewrites. govendor needs one for remove as well. Thanks.
