### ISSUE TITLE
rewrite: remove +p leaves the package entry in the vendor.json

### ISSUE THREAD

**Issue by ansel1** [kardianos/govendor#58]
I was experimenting with vendoring some external main packages which build command line tools we use.

Try this:

    mkdir $GOPATH/src/asdf && cd $GOPATH/src/asdf
    govendor init
    govendor add github.com/jstemmer/go-junit-report
    gevendor remove github.com/jstemmer/go-junit-report

go-junit-report is removed from the internal folder, but the entry remains in vendor.json.

**Comment by kardianos** [comment]
Thanks for the report. I'll look into this.

**Comment by kardianos** [comment]
govendor on the default branch now only supports the vendor folder. A new branch called "rewrite" supports import path rewrites.
