### ISSUE TITLE
rewrite: main packages mixed in normal package don't have imports rewritten, resulting in cyclic dependencies

### ISSUE THREAD

**Issue by ansel1** [kardianos/govendor#59]
try this, in an empty package, after `govendor init`:

    govendor add github.com/lib/pq
    govendor list

output:

    u github.com/lib/pq
    e github.com/lib/pq/oid

Looks like an external dependency was missed.  Try adding it:

    govendor add +e
    govendor list

output:

    v github.com/lib/pq
    v github.com/lib/pq/oid

Those should be unused, since I have no source files at all.  I believe the reason they appear as `v` is because they refer to each other.

    > govendor list -v
    v github.com/lib/pq ::/internal/github.com/lib/pq
      └── gitlab.protectv.local/ncryptify/russ.git/internal/github.com/lib/pq/oid
    v github.com/lib/pq/oid ::/internal/github.com/lib/pq/oid
      └── gitlab.protectv.local/ncryptify/russ.git/internal/github.com/lib/pq

The `oid` package has some normal source files in package "oid", and one source in package "main" with an "ignore" build tag.  That main source file's import statement is never rewritten by govendor, even though I don't currently have govendor configured to ignore the "ignore" build tag.

The workaround to at least avoid the import cycle is to ignore the "ignore" build tag in vendor.json

**Comment by kardianos** [comment]
Thanks for the report. I'll look into this.

**Comment by kardianos** [comment]
govendor on the default branch now only supports the vendor folder. A new branch called "rewrite" supports import path rewrites.
