### ISSUE TITLE
Using GO15VENDOREXPERIMENT with packages which have import re-writing vendored dependencies

### ISSUE THREAD

**Issue by ansel1** [kardianos/govendor#60]
Try adding govendor itself to a project with GO15VENDOREXPERIMENT set.  Then run `govendor list`.  It will show `github.com/dchest/safefile` as both "u" and "e".  This is because govendor correctly detected `github.com/dchest/safefile` as a dependency of govendor, and vendored it, but govendor vendors `github.com/dchest/safefile` itself, using import rewriting.  The tool did not rewrite those import statement from `github.com/kardianos/govendor/internal/github.com/dchest/safefile` back to `github.com/dchest/safefile`.

In the process of flattening out the vendored transitive dependencies, the primary dependency's sources need to have their import statements rewritten to match the vendoring style current in force.

**Comment by kardianos** [comment]
Right now govendor supports both import path rewriting and the vendor folder. In order to switch from import path rewriting to vendoring, the user is expected to use "govendor migrate". So before "govendor list" is called, it should first be migrated when the flag is set to 1.

Does that make sense? Or did I miss a point?

**Comment by ansel1** [comment]
Ok...well, I was starting with a fresh project that wasn't using either.  I had GO15VENDOREXPERIMENT set first, then did `govendor init` and `govendor add +e`.

That mostly worked, vendoring everything, without import rewriting.  The problem came when I did `govender add github.com/kardianos/govendor`.  That vendored `govendor` alright, but the vendored copy still contained import statements referring to `github.com/kardianos/govendor/internal/github.com/dchest/safefile`.  And *that* internal package *was not* vendored.  Instead, it vendored `github.com/dchest/safefile`.  That's probably the correct thing to do (flattening nested dependencies), but then the import statements in the vendored copy of `github.com/kardianos/govendor` need to be fixed.

**Comment by kardianos** [comment]
True. I ran into this myself. Honestly this is why it is important to agree on a single method. If we use the vendor folder, all packages should switch to using this. That way everyone can agree on what happens.

The trouble comes in is that when govendor is using the vendor folder, it assumes all other files (including the "internal" files) are package files; it doesn't search for other "vendor.json" files as that is now defined to live inside the "vendor" folder root. (see vendor-spec). 

I guess I would advise to use in one mode or another mode. In this case I plan to leave the rewrite until 1.6 comes out.

I'll leave this issue open, I'm not sure how many people have imports rewritten with govendor that would need to mix with the new vendor folder. Thoughts welcome.

**Comment by ansel1** [comment]
That seems reasonable, but then something else the tool could have done that would have worked is vendored `github.com/kardianos/govendor/internal/github.com/dchest/safefile`, which it didn't.  It's weird.  It vendored `github.com/dchest/safefile`...so it's like, it recognized that safefile was a transitive dependency, and tried to flatten it.  Even wierder, the it not flatten the other two packages in govendor's `internal` folder, `gt` and `pathos`.  Those is it copied into `vendor/github.com/kardianos/govendor/internal/gt` and `vendor/github.com/kardianos/govendor/internal/pathos`.

**Comment by kardianos** [comment]
I'll look into it for sure. I think it did read the vendor file, but didn't rewrite the imports (wrong mode).

I think the fix is to only read vendor files in the vendor folder per the spec.

**Comment by kardianos** [comment]
This should be fixed. But regardless, I don't have the time to support two modes.

govendor on the default branch now only supports the vendor folder. A new branch called "rewrite" supports import path rewrites.
