### ISSUE TITLE
vendoring github.com/mattn/go-sqlite3 does not include required C files

### ISSUE THREAD

**Issue by ansel1** [kardianos/govendor#61]
govendor should probably include the C files when vendoring projects.

**Comment by kardianos** [comment]
This is a known problem. I actually have thought about the best way to support something like this but haven't come to firm conclusions.

govendor will copy C files if they are in the same directory. If they are in a different sub-directory, then it doesn't know to pull those files in as well. There are several ways you could approach this situation:

 1. ask go-sqlite3 to put in a stub go file in the C directory and put an import statement that depend on that in the main package.
 2. Make a "manafest file that controls what dependency a package needs.
 3. Add an option to allow fetching an entire tree in govendor, regardless of the perceived dependencies.

I think (2) is a bad option. I like (1) the best, but I understand that might not always be an option. It is probably practical to add (3), as some package might include resource files as well. In the vendor file you could then note to also copy all sub-directories as well when updating.

**Comment by ansel1** [comment]
Hmm...I guess (3) is probably best.  I was thinking, just treat *.c and *.cpp as if they were *.go files and include all of them, no matter where they lie in the source tree, but there could be other file types required by a cgo build.

**Comment by kardianos** [comment]
The issue at hand is that govendor doesn't copy repositories; it copies packages. So if C and CPP files are within the same directory, it will copy them. It just doesn't know to copy that sub-directory.

I agree with you that (3) would be a good option to have in cases like this.

**Comment by kardianos** [comment]
@ansel1 Would you be willing to test the "tree" branch and provide feedback:

I'm hoping to get some feedback before merging it in.

**Comment by kardianos** [comment]
vendoring now as a tree like `govendor add github.com/mattn/go-sqlite3/^` will add all subfolders too.
Fixed with the addition of tree feature.
