### ISSUE TITLE
vendor file loaded with entries for non vendored packages

### ISSUE THREAD

**Issue by ardan-bkennedy** [kardianos/govendor#66]
using github.com/ardanlabs/kit

Remove and re-create the vendor folder
On the command line navigate to the vendor folder
$ govendor add gopkg.in/mgo.v2

Look at the vendor.json file. Every import is loaded into the file though only this one package was vendored.

**Comment by kardianos** [comment]
As you noted, I'm unable to reproduce this at this time. It may have to do with the origin path where they came from before. I'll leave this open for now and might try to reproduce it when I have a bit more time.

**Comment by kardianos** [comment]
Unable to reproduce.
