### ISSUE TITLE
Consider adding command "vendor backport"

### ISSUE THREAD

**Issue by kardianos** [kardianos/govendor#7]
vendor backport

Copy from the local internal folder out to the GOPATH vendor path. In addition to simply copying files, we would need to support import comment rewrites, not just removal.

**Comment by gaillard** [comment]
Not sure if your looking for these kind of comments but I would keep this repo small. I think the tool that will get used the most is the one that simply copies and rewrites imports as well as delete and unwrites the imports. I would not add this command and would also remove init and update.

**Comment by kardianos** [comment]
I have yet to find a convincing use case for this. Closing as won't add for now.
