### ISSUE TITLE
feature: Add an installation section to the README

### ISSUE THREAD

**Issue by penguinpowernz** [kardianos/govendor#73]
I can't figure out how to install this thing.  Please help noobs like me and add an installation section to the README.

Cheers :)

**Comment by kardianos** [comment]
go get github.com/kardianos/govendor
?

I can add a section to README too.

**Comment by penguinpowernz** [comment]
Ah right sorry my envvars weren't setup properly....

```sh
cd ~/src/golang
export GOPATH=`pwd`
export PATH="$PATH:$GOPATH/bin"
# ALL GOOD NOW
```
