### ISSUE TITLE
Missing license files

### ISSUE THREAD

**Issue by grobie** [kardianos/govendor#77]
govendor does not seem to migrate `LICENSE` files (and similar license related files). This violates the license of many projects.

**Comment by grobie** [comment]
godeps had the same issue https://github.com/tools/godep/issues/245.

**Comment by kardianos** [comment]
Agreed this is an issue. I'll look into fixing next. Thanks.

**Comment by juliusv** [comment]
Related discussion in Godep about it: https://github.com/tools/godep/issues/245

**Comment by kardianos** [comment]
Thanks. This should be a relatively easy fix to do; I'm not too concerned. I just need to update a single function to correct it.

**Comment by grobie** [comment]
My biggest concern is how to identify all possible license related files. Looking at the godep issue there seem to be quite a few odd ones despite the common `LICENSE` and `NOTICE` ones.

**Comment by grobie** [comment]
The second challenge might be LICENSE files which are at the root of a repository and not necessarily at the package location.

**Comment by kardianos** [comment]
Unlike godeps, govendor copies all files over for a given project directory. So if the license is in the same package, it is a noop. When govendor ignores test files, it does so as a subtraction from all files.

So the required change will be to recurse down and discover license files. I'll read the godep issue to discover what filters I should apply.

There will be another change needed for the empty directory remove function, but again that should be simple enough.
