### ISSUE TITLE
govendor equivalent for git status --porcelain

### ISSUE THREAD

**Issue by myitcv** [kardianos/govendor#79]
Apologies if I've missed this somewhere, but I believe there is merit in a `govendor` option equivalent in behaviour and output of `git status --porcelain`.

Let's assume we setup `govendor` for a given project as follows:

```bash
$ govendor init
$ govendor add gopkg.in/check.v1
$ govendor update gopkg.in/check.v1
```

At this point, `vendor/vendor.json` will look something like this:

```json
{
        "comment": "",
        "ignore": "test",
        "package": [
                {
                        "path": "gopkg.in/check.v1",
                        "revision": "5b76b26efe7f426789852e983fbde4de62c42282",
                        "revisionTime": "2014-07-09T11:41:00-03:00"
                }
        ]
}
```

Now assume we make a change to a file in the vendored copy, e.g. `vendor/gopkg.in/check.v1/check.go`. The vendored copy, specifically `vendor/gopkg.in/check.v1/check.go`, has now been modified relative to commit `5b76b26efe7f426789852e983fbde4de62c42282`.

What we need at this point is a `govendor` command (`govendor status` perhaps?) that shows the modification status, with output similar to:

```
$ govendor status
Package gopkg.in/check.v1
Modifications compared to 5b76b26efe7f426789852e983fbde4de62c42282:

        modified:   vendor/gopkg.in/check.v1/check.go
```

## What are the use cases for this command?

There are two main use cases:

1. At this point `vendor.json` is effectively out of date. To say the vendored copy is equivalent to commit `5b76b26efe7f426789852e983fbde4de62c42282` is incorrect. We want to _prevent_ situations like this and so we would, for example, fail a CI build in case the vendored copy contained any modifications when compared to the referenced commit, i.e. the build would be failed if `govendor status` gave any output
2. We currently have no guarantee that the referenced commit exists in the remote repository `gopkg.in/check.v1`, only our local equivalent repository. Having such a check (which would typically be run on a CI server for example) would allow us to verify this independently

Any thoughts on this?

A way of achieving the same result would be via [`govendor restore`](https://github.com/kardianos/govendor/issues/35) command which would ensure the vendored copy is identical to the commit referenced in `vendor.json`. Then a simple `git status` would uncover effectively the reverse modification set (which would be enough for us, because we simply want to ensure the modification set is the empty set)

**Comment by kardianos** [comment]
@myitcv I've read this and have some thoughts on it. There is merit to what you propose. However, I would also want to be able to say "This package is modified, but changes were on purpose and should be kept and propagated." *maybe* storing a patch flle of the diff...

Why would you vendor something and then modify it?
 * Remove extra files that added dependencies I don't want or use (rare, but happens) and aren't contained with a tag.
 * If someone wants to patch a standard lib like "crypto/tls", they may want modify it on purpose.

So you could hash the content of all the files, using a sort on the file names first, and have a single hash that represents the content. to enable something like this. And unless you stored each hash separately or did something too clever, you might not know which files changed until you did a diff on the files. 

All that being said, I would want to think for a bit about the value this adds, even though I'm not directly against it.

**Comment by myitcv** [comment]
> ...
> So you could hash the content of all the files, using a sort on the file names first, and have a single 
hash that represents the content.

This sounds well beyond the scope of a tool like `govendor` and rather more the realm of `git`. 

For the cases you describe (which I agree are valid use cases), surely it's easier to either:

1. maintain a fork of a package you're interested in where you can pull in changes from upstream as well as make any custom modifications etc
2. create your own repo which contains a subset of another repo (this would cover the `crypto/tls` example)

_in both cases setting the `origin` accordingly_

Then you would simply use the additional mode proposed in this issue to verify that the vendored copy of a package (for either case 1 or 2 above) matches, file-by-file, the `origin` at the specified commit.

Thoughts?

**Comment by kardianos** [comment]
For a feature defined as: "provide a simple way for a user to ensure the content of the vendor folder has not been altered after copying", I think the easiest way to determine if the contents of vendor is true is to hash and store the hash when they are copied into vendor. However, it is true that you could simply fetch the original source and compare on demand. The difference would be speed and a dependency on the remote availability.

Let me know if I misunderstood the feature definition as defined by the above user story.

**Comment by myitcv** [comment]
> The difference would be speed and a dependency on the remote availability.

True. But note that this also catches the scenario (assuming the remote is available) when you are referencing a local commit that _should_ have been pushed remotely (i.e. under normal operation, with the remote available, everyone should be able to reference the commit mentioned in `vendor.json`)

I tend to consider availability of the remote, whilst an important consideration, to be an orthogonal concern to reproducibility of the build.

Incidentally, I've started using a different vendoring approach that uses multiple `GOPATH`'s and implemented some basic tooling myself locally (for now)

**Comment by kardianos** [comment]
@myitcv I would be interested in hearing more about your use case and why you decided to go with that approach, and what your tooling looks like, simply to understand more people's workflow.

**Comment by myitcv** [comment]
@kardianos - I will add more details to this thread when I get a chance

**Comment by kardianos** [comment]
Cool. We can always reopen if needed. I'm just trying to clean house.
