### ISSUE TITLE
Ignore error when parsing import paths

### ISSUE THREAD

**Issue by tv42** [kardianos/govendor#83]
`govendor` doesn't seem to provide the usual `goX.Y` build tags, which leads to some annoying behavior:

```console
~$ mkdir z
~$ cd z
~/z$ export GOPATH=$PWD
~/z$ go get -d golang.org/x/net/http2
~/z$ mkdir -p src/example.com/blargh
~/z$ cd src/example.com/blargh/
~/z/src/example.com/blargh$ govendor init
~/z/src/example.com/blargh$ govendor add golang.org/x/net/http2/h2demo
~/z/src/example.com/blargh$ go get -d camlistore.org
package camlistore.org: no buildable Go source files in /home/tv/z/src/camlistore.org
~/z/src/example.com/blargh$ govendor add golang.org/x/net/http2/h2demo
Error: /home/tv/z/src/camlistore.org/depcheck/min_go_version.go:21:8: invalid import path: `

****************************************************************************

                 Camlistore requires Go 1.3 or later.

****************************************************************************
`
govendor add [options] ( +status or import-path-filter )
	Copy one or more packages into the vendor folder.
	Options:
		-n           dry run and print actions that would be taken
		-tree        copy package(s) and all sub-folders under each package
		
		The following may be replaced with something else in the future.
		-short       if conflict, take short path 
		-long        if conflict, take long path
~/z/src/example.com/blargh$ 
```

**Comment by kardianos** [comment]
Yes and no. This is actually an interesting use case. Thanks for bringing it up.

govendor does *not* respect your environment build tags, but it does read and selectively ignore build tags that you specify in the "vendor.json" file. By default it ignores the "test" build flag.

This is the designed behavior; I want to vendor all os and arch files by default, unless explicitly ignored.

The issue in this case is that I don't handle go version build tags in a smart manner.
We have `// +build !go1.3`. Should govendor have some type of min build flag or something for the go version, and ignore older files?

Maybe an option is needed minGoVersion: "go1.3" which would then ignore such files.

Or, if there is a go parse error, just abort and include the file anyway. Will need to think about that.

Thanks again for bringing this up.

**Comment by tv42** [comment]
In an ideal world, people wouldn't need to encode error messages in import paths.. :-/

**Comment by kardianos** [comment]
For reference: https://camlistore.googlesource.com/camlistore/+/master/depcheck/min_go_version.go

**Comment by kardianos** [comment]
I think the correct thing to do is to ignore this error when parsing the file. That will correct this issue.
