### ISSUE TITLE
README example issue

### ISSUE THREAD

**Issue by FrenchBen** [kardianos/govendor#84]
In the README.md there is a section at the bottom, which has examples, such as:
```
Examples:
    $ govendor list -no-status +local
    $ govendor list +vend,prog +local,program
    $ govendor list +local,!prog
```

The issue is that in many shell env, the use of `!` is treated as a 'recall last command' - Following the CLI examples, running:
`$ govendor list +local,!prog`
expands into:
`$ govendor list +local,govendor list +vend,prog +local,program`

**Comment by kardianos** [comment]
That's not very nice. I was using fish, not bash. *sigh*

I'll think of a new negation operator.

**Comment by FrenchBen** [comment]
:+1: Thanks!

**Comment by FrenchBen** [comment]
:+1: thanks for the quick turn-around!
