### ISSUE TITLE
Don't remove import comments

### ISSUE THREAD

**Issue by cespare** [kardianos/govendor#85]
What's the reason for removing import comments? They're ignored in the Go 1.5 vendor experiment:

> Import comments are ignored in vendored packages.

I'd prefer if my vendoring tool didn't make edits to the code. Is it possible to add an option to not remove import comments, or just change the behavior?

**Comment by kardianos** [comment]
A hold over from import path rewriting. Agree, should remove.

**Comment by kardianos** [comment]
@cespare I just checked. govendor doesn't remove import comments when moving files over. Can you give me an example where that seems to be the case?

**Comment by cespare** [comment]
I didn't try it. I was going off this feature listed in the readme:

> Package import comment removal

and also some code which does import comment removal.

Perhaps only the rewrite branch removes import comments? If so, maybe the readme just needs an update.

**Comment by kardianos** [comment]
Thanks for noticing. I've updated the README.

**Comment by cespare** [comment]
Glad it was as easy as that :)

**Comment by fatih** [comment]
I need to remove the import comments as part of a custom script. Is there a way to do it with govendor?

**Comment by kardianos** [comment]
@fatih Have you tried using "gorename"?

**Comment by fatih** [comment]
@kardianos gorename doesn't allow me to rename `import comments`. For now I've just added these non Go ast aware script:

```
files=$(grep -rl  '// import ".*"' .)
for file in $(grep -rl  '// import ".*"' .); do
	sed -i '' 's%// import ".*"%%' $file 
done
```

And this doesn't cover of course the case for import comments of `/* ... */`. I would be more than happy if you could provide a hidden flag or something else. I'm using `govendor` for a project to extract a package from a huge monorepo which is already using the `vendor` package. And then rewriting the import paths myself via `gofmt`. Unfortunately `gomvpkg` doesn't work well for directories with sub packages, and `gofmt` doesn't have a rewrite rule to rename or strip `import comments`.

**Comment by kardianos** [comment]
Out of curiosity, what do you need this for?

**Comment by fatih** [comment]
@kardianos checkout the issue https://github.com/prometheus/prometheus/issues/1720 

Currently you can't use the package `promql`. I've exctracted it to a standalone package with a completely different import path, such as `foo/promql`. Just removing the `vendor` package and then using the `promql` package via public facing packages don't work, because `promql` depends on the dependencies that are vendored inside the `prometheus` repo. So I have to extract the package, with the dependencies from the repo itself. To access the vendored packages (see issue), I have to rename the `vendor` package to something else and rewrite the import paths.

**Comment by kardianos** [comment]
Ah. Yeah, govendor isn't designed to extract a package tree.

If you look at the issue list, there is an open issue to try to use a package as both a command with copied dependencies and as a library package.

I don't have a great answer for that. Okay, I do. Move your vendor folder into the `cmd/` folder and vendor your "library" packages into that vendor folder. If you keep it in the files in the same repo git should store them in the same way. When you make a library change, you can just `govendor update github.com/prometheus/prometheus/...` to update what the cmds use. That is the solution I would propose.

**Comment by fatih** [comment]
@kardianos you are right. I'm aware that `govendor` is not suitable, I'm just using it partially and I had to remove the import comments, saw this issue and thought I mention, maybe there is a hidden option or setting I could use. Thanks for your help.
