### ISSUE TITLE
dependency packages of _test.go

### ISSUE THREAD

**Issue by houbin217jz** [kardianos/govendor#9]
Vendor is awesome. However I noticed that vendor detects and puts all the dependency packages into internal folder including dependencies of _test.go files. 
For example, when I use `gorp + lib/pq`, it will also puts following packages and their dependencies.
```
github.com/go-sql-driver/mysql
github.com/mattn/go-sqlite3
github.com/ziutek/mymysql/godrv
```
These packages are used just in gorp_test.go and should be excluded. 

Also I think it's better to clarify that how to due with _test.go dependencies in vendor-spec.

**Comment by kardianos** [comment]
I can confirm this is an issue. I need to think if there should be a switch to also look at test files. Thanks for tagging this.

**Comment by anonx** [comment]
I don't think this is an issue. Yeah those packages are only used in `*_test.go`. So what? That means you wouldn't end-up with broken tests if the packages have changed.
And if you really don't want to include some specific import path there is always `vendor remove` available.
Right? Or am I missing something?

**Comment by anonx** [comment]
Looks like you expect the same behaviour as `godep` has. But that's an issue of `godep` rather than a feature: https://github.com/tools/godep/issues/185

**Comment by kardianos** [comment]
I think the default behavior that I would want is to copy over the test files, but don't copy over or rewrite the test file dependencies. This also implies creating a indicator of such package in list (test only).

I would still want an option, probably at the project level, to include such dependencies.

**Comment by ilackarms** [comment]
any progress on this issue?

**Comment by tedsuo** [comment]
Hi @kardianos,

To be clear, the current behavior is that vendor copies over the test file dependencies, but does not rewrite the import paths for the dependencies (the import paths for the regular dependencies are  rewritten in the test files though).  So the packages are vendored but not referenced.

For us, it's important that we have reproducible builds, so we want the test dependencies vendored.  Right now as a hack around the lack of linking we are pulling the packages back out of the vendor folder and into the main gopath before running tests.  But we would gladly submit a pull request to rewrite import paths.

Cheers,
Ted

**Comment by kardianos** [comment]
@ilackarms This issue (and any other changes) are pending adding operational test. I've stubbed the test I want to see but I haven't filled it in yet.

**Comment by kardianos** [comment]
@tedsuo That's odd. I'd like to say the vendor tool right now treats all go files equal. It totally ignores build tags and file suffixes. Now if you don't have the dependency in your gopath and the test dependency is marked with a "m" then you need to get those before it will rewrite them.

I'm 99% sure this is the case, but this is one of the reasons my next step is to add an operational test(s). Could you confirm? "vendor list"
