### ISSUE TITLE
feature: add "root" to vendor.json file?

### ISSUE THREAD

**Issue by kardianos** [kardianos/govendor#93]
@freeformz
Would it be beneficial to heroku type services to include a "rootPath" field in the top of vendor.json file? It would correlate to the relative path (under GOPATH) that the vendor folder lives in.

**Comment by kardianos** [comment]
If so, suggestions on names?

**Comment by freeformz** [comment]
Yes if I'm understanding correctly. This would make it much easier to determine where to put code pushed to us for proper package naming.

**Comment by kardianos** [comment]
The new field in govendor's vendor.json file would look like:
{
    "rootPath": "github.com/kardianos/govendor",
    ...
}

**Comment by freeformz** [comment]
Seems to me your really talking about a package, not a path (even though packages are expressed as a path).

**Comment by kardianos** [comment]
The value in "rootPath" would be the following:
$GOPATH/src/$(rootPath)/vendor/vendor.json
So that could be a package, but it might not have any go files in it.

This is redundant with the package import comment. However, it is trivial to automatically add here. But,.. then again, it is kinda off topic in a way. Still on the fence.

**Comment by freeformz** [comment]
Where in `vendor/vendor.json` would this be?

**Comment by kardianos** [comment]
```json
{
    "rootPath": "github.com/kardianos/govendor",
    "ignore": "test",
    "comment": "",
    "package": [
        ...
    ]
}
```

**Comment by freeformz** [comment]
This is equivalent to godep's ImportPath AFACT.

**Comment by kardianos** [comment]
Yes.

**Comment by freeformz** [comment]
I don't understand what's meant by `redundant with the package import comment` though.

**Comment by kardianos** [comment]
This field "rootPath" or "ImportPath" seems to contain the same information as a package import comment. Makes me hesitant to include it. Maybe it's alright...

**Comment by freeformz** [comment]
It just makes it easy to determine where the code is supposed to live. Not everything uses import comments.
